import PAUndecidable

#check PAUndecidable.haltingCode_re
#check PAUndecidable.haltingCode_not_computable
#check PAUndecidable.haltingCode_iff_pa_provable
#check PAUndecidable.peano_arithmetic_instance_theoremhood_not_computable
#check PAUndecidable.peano_arithmetic_theoremhood_not_decidable

#print axioms PAUndecidable.haltingCode_re
#print axioms PAUndecidable.haltingCode_not_computable
#print axioms PAUndecidable.haltingCode_iff_pa_provable
#print axioms PAUndecidable.peano_arithmetic_instance_theoremhood_not_computable
#print axioms PAUndecidable.peano_arithmetic_theoremhood_not_decidable
