(** Kernel-assumption audit for the finite-axiomatizability reduction. *)

From PAFiniteBasisReduction Require Import
  FiniteBasisReduction HierarchyReduction FiniteSkolemHull
  CanonicalSelector CanonicalSelectorPA SkolemProgramCode FiniteBetaCoding
  ProgramTrace TotalProgramRows EvaluatorCutContract StandardTraceRows
  CanonicalTotalRows StandardTraceFunctionality TotalTraceEvaluator
  NonstandardHFFin TwoNonisomorphicModels TraceContractRealization.

Import PAFiniteBasisReduction PAHierarchyReduction.
Import PAFiniteSkolemHull PACanonicalSelector.
Import PACanonicalSelectorPA.
Import PASkolemProgramCode.
Import PAFiniteBetaCoding.
Import PAProgramTrace.
Import PATotalProgramRows.
Import PAEvaluatorCutContract.
Import PAStandardTraceRows.
Import PACanonicalTotalRows.
Import PAStandardTraceFunctionality.
Import PATotalTraceEvaluator.
Import PATraceContractRealization.
Import PATwoNonisomorphicModels.

Check FirstOrderPAModel.
Check RawPAIso.
Check NumeralGenerated.
Check standardPAModel.
Check nonstandardPAModel_exists.
Check peano_arithmetic_has_two_nonisomorphic_models.

Print Assumptions peano_arithmetic_has_two_nonisomorphic_models.

Check DeductivelyFinitelyAxiomatizable.
Check HasFiniteFragmentBasis.
Check finite_axiomatization_gives_finite_fragment_basis.
Check finite_fragment_basis_gives_finite_axiomatization.
Check finite_axiomatizable_iff_has_finite_fragment_basis.
Check PAInductionFragmentStrictness.
Check PAFiniteFragmentStrictness.
Check ConsistentList.
Check PA_finite_fragment_consistent.
Check finite_fragment_strictness_of_induction_fragment_strictness.
Check finite_fragment_strictness_of_mostowski.
Check PA_finite_fragment_strictness_excludes_finite_basis.
Check PA_finite_fragment_strictness_iff_no_finite_basis.
Check peano_arithmetic_not_finitely_axiomatizable_of_fragment_strictness.
Check peano_arithmetic_not_finitely_axiomatizable_iff_fragment_strictness.
Check PA_induction_fragment_strictness_excludes_finite_basis.
Check peano_arithmetic_not_finitely_axiomatizable_of_induction_strictness.
Check PA_finite_axiomatizable_iff_has_finite_fragment_basis.
Check term_rank.
Check formula_rank.
Check term_rank_enum.
Check term_rank_enum_spec.
Check term_rank_bounded_finite.
Check formula_rank_enum.
Check formula_rank_enum_spec.
Check formula_rank_bounded_finite.
Check RawPAModel.
Check raw_term_eval.
Check raw_formula_sat.
Check raw_PA_Prov_soundness.
Check PARankFragment.
Check PA_rank_fragment_enum.
Check PA_rank_fragment_enum_spec.
Check PA_rank_fragment_finite.
Check PA_rank_fragment_subset_ax_s.
Check PA_rank_fragment_mono.
Check PA_axiom_bounded_by_rank.
Check finite_PA_fragment_bounded_by_rank.
Check RawModelSatisfies.
Check RawModelFalsifies.
Check BProv_not_of_raw_countermodel.
Check PA_rank_fragment_separation_of_raw_countermodel.
Check PA_rank_fragment_misses_induction_of_raw_countermodel.
Check TwoChain.
Check two_chain_raw_model.
Check two_chain_rank_zero_model.
Check zero_or_successor_formula.
Check two_chain_falsifies_zero_or_successor_induction.
Check PA_rank_zero_fragment_misses_zero_or_successor_induction.
Check PA_rank_zero_fragment_strict.
Check PA_rank_zero_fragment_separation.
Check PARankFragmentStrictness.
Check PARankFragmentRawCountermodelStrictness.
Check rank_fragment_strictness_of_raw_countermodels.
Check induction_fragment_strictness_of_rank_fragment_strictness.
Check finite_fragment_strictness_of_rank_fragment_strictness.
Check peano_arithmetic_not_finitely_axiomatizable_of_rank_fragment_strictness.
Check skolemHull_satisfies_rank_fragment_at_rank.
Check skolemHull_formula_elementary.
Check skolemHull_satisfies_rank_fragment.
Check rawCanonicalSelectorGraph.
Check rawCanonicalSelectorGraph_total.
Check rawCanonicalSelectorGraph_functional.
Check canonicalSelectorFormula.
Check raw_canonicalSelectorFormula.
Check raw_canonicalSelectorFormula_exists_unique.
Check canonicalSkolemHull_satisfies_rank_fragment.
Check raw_sat_of_BProv_axs_context.
Check raw_not_lt_zero.
Check raw_lt_succ_cases.
Check raw_le_or_gt.
Check raw_le_antisymm.
Check raw_order_trichotomy.
Check raw_definable_induction.
Check raw_definable_least_witness.
Check raw_definable_least_number_of_pa.
Check rawCanonicalSelectorGraph_total_of_pa.
Check rawCanonicalSelectorGraph_functional_of_pa.
Check raw_canonicalSelectorFormula_exists_unique_of_pa.
Check canonicalSkolemHull_satisfies_rank_fragment_of_pa.
Check fofamRawPAModel.
Check fofam_raw_pa_satisfies.
Check fofam_raw_definable_least_number.
Check fofam_raw_order_trichotomy.
Check fofamCanonicalSelector.
Check fofamCanonicalSelector_formula_exists_unique.
Check fofamCanonicalSkolemHull_satisfies_rank_fragment.
Check polynomialPair.
Check polynomialPair_injective.
Check polynomialNode.
Check skolemProgramCode.
Check skolemProgramArgsCode.
Check polynomialUnpair_pair.
Check scheduleSkolemCode.
Check scheduleSkolemCode_program.
Check scheduleSkolemCode_args.
Check decodeSkolemProgram.
Check decodeSkolemProgramArgs.
Check decodeSkolemProgram_code.
Check decodeSkolemProgramArgs_code.
Check skolemProgramCode_injective.
Check skolemProgramArgsCode_injective.
Check scheduled_children_smaller.
Check scheduled_program_children_smaller.
Check scheduled_args_children_smaller.
Check RawBetaEntry.
Check raw_sat_betaTermTermAt_iff.
Check raw_sat_betaEntryExistsPrefixTermAt_iff.
Check raw_sat_betaPrependExistsTermAt_iff.
Check raw_betaPrefixCRTAccumulator_self.
Check raw_betaCodeExtension_exists.
Check betaCodeExtensionSelectorBody.
Check raw_sat_betaCodeExtensionSelectorBody_iff.
Check rawCanonicalBetaExtensionCode_spec.
Check rawCanonicalFiniteBetaCode_spec.
Check finite_list_beta_code.
Check finite_vector_beta_code.
Check canonicalFiniteBetaPrograms.
Check finite_beta_code_in_canonical_skolem_hull.
Check rawBetaEntry_functional.
Check raw_sat_evaluator_iff.
Check raw_sat_evaluator_of_standard_table.
Check decodeFixedArgs_children_smaller.
Check decoded_choose_children_smaller.
Check normalizeTraceProgram_eval.
Check normalizeTraceProgram_trace.
Check totalRowProgram_trace.
Check finite_total_row_beta_programs.
Check EvaluatorContract.
Check skolemHull_evaluator_contract_of_ambient_pa.
Check raw_sat_cutAt_iff_standard.
Check raw_not_sat_sealed_cutAt_induction.
Check peano_arithmetic_not_finitely_axiomatizable_of_contracts.
Check StandardRowWitness.
Check standardRowWitness_of_sat_programCases.
Check sat_programCases_of_standardRowWitness.
Check canonicalStandardRowWitness_or_zero.
Check standardRowWitness_output_eq_of_child_entries.
Check StandardProgramTable_entries_eq.
Check traceEvaluator_standardCode_functional.
Check finite_total_row_beta_hull.
Check canonical_total_row_programStep.
Check traceEvaluator_total_at_totalRow.
Check traceEvaluator_standardCode_total.
Check traceConstructionRank.
Check trace_contractCountermodels.
Check peano_arithmetic_not_finitely_axiomatizable.
Check Sat_tag_relativize.
Check Sentence_candidateExists.
Check Sentence_starBound.
Check Sat_tag_candidateAt_iff.
Check Sat_tag_starBound_iff.
Check Sentences_NonstandardHFFinTheory.
Check finite_NonstandardHFFinTheory_tag_model.
Check NonstandardHFFinTheory_consistent.
Check NonstandardHFFinTheory_model.
Check nonstandardHFFin_fofam_exists.
Check nonstandardHFFin_translated_bounds_exists.
Check nonstandardHFFin_raw_bounds_exists.

Print Assumptions finite_axiomatization_gives_finite_fragment_basis.
Print Assumptions finite_fragment_basis_gives_finite_axiomatization.
Print Assumptions finite_axiomatizable_iff_has_finite_fragment_basis.
Print Assumptions PA_finite_fragment_consistent.
Print Assumptions finite_fragment_strictness_of_induction_fragment_strictness.
Print Assumptions finite_fragment_strictness_of_mostowski.
Print Assumptions PA_finite_fragment_strictness_excludes_finite_basis.
Print Assumptions PA_finite_fragment_strictness_iff_no_finite_basis.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_fragment_strictness.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_iff_fragment_strictness.
Print Assumptions PA_induction_fragment_strictness_excludes_finite_basis.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_induction_strictness.
Print Assumptions PA_finite_axiomatizable_iff_has_finite_fragment_basis.
Print Assumptions term_rank_enum_spec.
Print Assumptions term_rank_bounded_finite.
Print Assumptions formula_rank_enum_spec.
Print Assumptions formula_rank_bounded_finite.
Print Assumptions PA_rank_fragment_enum_spec.
Print Assumptions PA_rank_fragment_finite.
Print Assumptions PA_rank_fragment_subset_ax_s.
Print Assumptions PA_rank_fragment_mono.
Print Assumptions PA_axiom_bounded_by_rank.
Print Assumptions finite_PA_fragment_bounded_by_rank.
Print Assumptions raw_PA_Prov_soundness.
Print Assumptions BProv_not_of_raw_countermodel.
Print Assumptions PA_rank_fragment_separation_of_raw_countermodel.
Print Assumptions PA_rank_fragment_misses_induction_of_raw_countermodel.
Print Assumptions two_chain_rank_zero_model.
Print Assumptions two_chain_falsifies_zero_or_successor_induction.
Print Assumptions PA_rank_zero_fragment_misses_zero_or_successor_induction.
Print Assumptions PA_rank_zero_fragment_strict.
Print Assumptions PA_rank_zero_fragment_separation.
Print Assumptions rank_fragment_strictness_of_raw_countermodels.
Print Assumptions induction_fragment_strictness_of_rank_fragment_strictness.
Print Assumptions finite_fragment_strictness_of_rank_fragment_strictness.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_rank_fragment_strictness.
Print Assumptions skolemHull_satisfies_rank_fragment_at_rank.
Print Assumptions skolemHull_formula_elementary.
Print Assumptions skolemHull_satisfies_rank_fragment.
Print Assumptions rawCanonicalSelectorGraph_total.
Print Assumptions rawCanonicalSelectorGraph_functional.
Print Assumptions raw_canonicalSelectorFormula.
Print Assumptions raw_canonicalSelectorFormula_exists_unique.
Print Assumptions canonicalSkolemHull_satisfies_rank_fragment.
Print Assumptions raw_sat_of_BProv_axs_context.
Print Assumptions raw_order_trichotomy.
Print Assumptions raw_definable_induction.
Print Assumptions raw_definable_least_number_of_pa.
Print Assumptions raw_canonicalSelectorFormula_exists_unique_of_pa.
Print Assumptions canonicalSkolemHull_satisfies_rank_fragment_of_pa.
Print Assumptions fofam_raw_pa_satisfies.
Print Assumptions fofamCanonicalSelector_formula_exists_unique.
Print Assumptions fofamCanonicalSkolemHull_satisfies_rank_fragment.
Print Assumptions polynomialPair_injective.
Print Assumptions polynomialUnpair_pair.
Print Assumptions scheduleSkolemCode_program.
Print Assumptions decodeSkolemCode_roundtrip_mutual.
Print Assumptions skolemProgramCode_injective.
Print Assumptions scheduled_children_smaller.
Print Assumptions scheduled_program_children_smaller.
Print Assumptions raw_sat_betaTermTermAt_iff.
Print Assumptions raw_betaPrefixCRTAccumulator_self.
Print Assumptions raw_betaCodeExtension_exists.
Print Assumptions raw_sat_betaCodeExtensionSelectorBody_iff.
Print Assumptions rawCanonicalBetaExtensionCode_spec.
Print Assumptions rawCanonicalFiniteBetaCode_spec.
Print Assumptions finite_list_beta_code.
Print Assumptions finite_vector_beta_code.
Print Assumptions canonicalFiniteBetaPrograms.
Print Assumptions finite_beta_code_in_canonical_skolem_hull.
Print Assumptions rawBetaEntry_functional.
Print Assumptions raw_sat_evaluator_iff.
Print Assumptions decodeFixedArgs_children_smaller.
Print Assumptions normalizeTraceProgram_eval.
Print Assumptions totalRowProgram_trace.
Print Assumptions finite_total_row_beta_programs.
Print Assumptions skolemHull_evaluator_contract_of_ambient_pa.
Print Assumptions raw_not_sat_sealed_cutAt_induction.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_contracts.
Print Assumptions standardRowWitness_of_sat_programCases.
Print Assumptions sat_programCases_of_standardRowWitness.
Print Assumptions canonicalStandardRowWitness_or_zero.
Print Assumptions standardRowWitness_output_eq_of_child_entries.
Print Assumptions StandardProgramTable_entries_eq.
Print Assumptions traceEvaluator_standardCode_functional.
Print Assumptions finite_total_row_beta_hull.
Print Assumptions canonical_total_row_programStep.
Print Assumptions traceEvaluator_standardCode_total.
Print Assumptions trace_contractCountermodels.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable.
Print Assumptions Sat_tag_starBound_iff.
Print Assumptions NonstandardHFFinTheory_consistent.
Print Assumptions nonstandardHFFin_fofam_exists.
Print Assumptions nonstandardHFFin_raw_bounds_exists.
