(** Kernel-assumption audit for the finite-axiomatizability reduction. *)

From PAFiniteBasisReduction Require Import
  FiniteBasisReduction HierarchyReduction NonstandardHFFin.

Import PAFiniteBasisReduction PAHierarchyReduction.

Check DeductivelyFinitelyAxiomatizable.
Check HasFiniteFragmentBasis.
Check finite_axiomatization_gives_finite_fragment_basis.
Check finite_fragment_basis_gives_finite_axiomatization.
Check finite_axiomatizable_iff_has_finite_fragment_basis.
Check PAInductionFragmentStrictness.
Check PAFiniteFragmentStrictness.
Check ConsistentList.
Check PA_finite_fragment_consistent.
Check finite_fragment_strictness_of_induction_fragment_strictness.
Check finite_fragment_strictness_of_mostowski.
Check PA_finite_fragment_strictness_excludes_finite_basis.
Check PA_finite_fragment_strictness_iff_no_finite_basis.
Check peano_arithmetic_not_finitely_axiomatizable_of_fragment_strictness.
Check peano_arithmetic_not_finitely_axiomatizable_iff_fragment_strictness.
Check PA_induction_fragment_strictness_excludes_finite_basis.
Check peano_arithmetic_not_finitely_axiomatizable_of_induction_strictness.
Check PA_finite_axiomatizable_iff_has_finite_fragment_basis.
Check term_rank.
Check formula_rank.
Check term_rank_enum.
Check term_rank_enum_spec.
Check term_rank_bounded_finite.
Check formula_rank_enum.
Check formula_rank_enum_spec.
Check formula_rank_bounded_finite.
Check RawPAModel.
Check raw_term_eval.
Check raw_formula_sat.
Check raw_PA_Prov_soundness.
Check PARankFragment.
Check PA_rank_fragment_enum.
Check PA_rank_fragment_enum_spec.
Check PA_rank_fragment_finite.
Check PA_rank_fragment_subset_ax_s.
Check PA_rank_fragment_mono.
Check PA_axiom_bounded_by_rank.
Check finite_PA_fragment_bounded_by_rank.
Check RawModelSatisfies.
Check RawModelFalsifies.
Check BProv_not_of_raw_countermodel.
Check PA_rank_fragment_separation_of_raw_countermodel.
Check PA_rank_fragment_misses_induction_of_raw_countermodel.
Check TwoChain.
Check two_chain_raw_model.
Check two_chain_rank_zero_model.
Check zero_or_successor_formula.
Check two_chain_falsifies_zero_or_successor_induction.
Check PA_rank_zero_fragment_misses_zero_or_successor_induction.
Check PA_rank_zero_fragment_strict.
Check PA_rank_zero_fragment_separation.
Check PARankFragmentStrictness.
Check PARankFragmentRawCountermodelStrictness.
Check rank_fragment_strictness_of_raw_countermodels.
Check induction_fragment_strictness_of_rank_fragment_strictness.
Check finite_fragment_strictness_of_rank_fragment_strictness.
Check peano_arithmetic_not_finitely_axiomatizable_of_rank_fragment_strictness.
Check Sat_tag_relativize.
Check Sentence_candidateExists.
Check Sentence_starBound.
Check Sat_tag_candidateAt_iff.
Check Sat_tag_starBound_iff.
Check Sentences_NonstandardHFFinTheory.
Check finite_NonstandardHFFinTheory_tag_model.
Check NonstandardHFFinTheory_consistent.
Check NonstandardHFFinTheory_model.
Check nonstandardHFFin_fofam_exists.
Check nonstandardHFFin_translated_bounds_exists.
Check nonstandardHFFin_raw_bounds_exists.

Print Assumptions finite_axiomatization_gives_finite_fragment_basis.
Print Assumptions finite_fragment_basis_gives_finite_axiomatization.
Print Assumptions finite_axiomatizable_iff_has_finite_fragment_basis.
Print Assumptions PA_finite_fragment_consistent.
Print Assumptions finite_fragment_strictness_of_induction_fragment_strictness.
Print Assumptions finite_fragment_strictness_of_mostowski.
Print Assumptions PA_finite_fragment_strictness_excludes_finite_basis.
Print Assumptions PA_finite_fragment_strictness_iff_no_finite_basis.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_fragment_strictness.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_iff_fragment_strictness.
Print Assumptions PA_induction_fragment_strictness_excludes_finite_basis.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_induction_strictness.
Print Assumptions PA_finite_axiomatizable_iff_has_finite_fragment_basis.
Print Assumptions term_rank_enum_spec.
Print Assumptions term_rank_bounded_finite.
Print Assumptions formula_rank_enum_spec.
Print Assumptions formula_rank_bounded_finite.
Print Assumptions PA_rank_fragment_enum_spec.
Print Assumptions PA_rank_fragment_finite.
Print Assumptions PA_rank_fragment_subset_ax_s.
Print Assumptions PA_rank_fragment_mono.
Print Assumptions PA_axiom_bounded_by_rank.
Print Assumptions finite_PA_fragment_bounded_by_rank.
Print Assumptions raw_PA_Prov_soundness.
Print Assumptions BProv_not_of_raw_countermodel.
Print Assumptions PA_rank_fragment_separation_of_raw_countermodel.
Print Assumptions PA_rank_fragment_misses_induction_of_raw_countermodel.
Print Assumptions two_chain_rank_zero_model.
Print Assumptions two_chain_falsifies_zero_or_successor_induction.
Print Assumptions PA_rank_zero_fragment_misses_zero_or_successor_induction.
Print Assumptions PA_rank_zero_fragment_strict.
Print Assumptions PA_rank_zero_fragment_separation.
Print Assumptions rank_fragment_strictness_of_raw_countermodels.
Print Assumptions induction_fragment_strictness_of_rank_fragment_strictness.
Print Assumptions finite_fragment_strictness_of_rank_fragment_strictness.
Print Assumptions peano_arithmetic_not_finitely_axiomatizable_of_rank_fragment_strictness.
Print Assumptions Sat_tag_starBound_iff.
Print Assumptions NonstandardHFFinTheory_consistent.
Print Assumptions nonstandardHFFin_fofam_exists.
Print Assumptions nonstandardHFFin_raw_bounds_exists.
