(**
  Finite Skolem hulls inside raw arithmetic structures.

  For a fixed syntax rank [selectorRank], [SkolemProgram] is the finite-tree
  language generated by a distinguished seed, the arithmetic operations, and
  one witness selector for every formula in [formula_rank_enum selectorRank].
  Its values form a raw arithmetic substructure.  The central theorem below
  proves rank-bounded elementarity of this substructure whenever the formula
  rank is at most the selector rank: existential witnesses and
  counterexamples to universal formulas are both among the selectors.

  This construction deliberately uses [RawPAModel], not [PA.Model]: the
  latter already contains a meta-level induction field and therefore cannot
  serve as a countermodel to an induction fragment.
*)

From Stdlib Require Import List Arith Lia Classical ClassicalEpsilon
  ClassicalDescription ProofIrrelevance Logic.FunctionalExtensionality.
From FirstOrder Require Import Fol.
From PAHF Require Import PAHF.
From PAFiniteBasisReduction Require Import HierarchyReduction.

Import ListNotations.
Import PAHierarchyReduction.

Module PAFiniteSkolemHull.

(** Raw evaluation and satisfaction depend only on free variables. *)
Lemma raw_term_eval_ext_free : forall (M : RawPAModel)
    (t : PA.term) (e e' : nat -> M),
  (forall n, PA.Term.Free n t -> e n = e' n) ->
  raw_term_eval M e t = raw_term_eval M e' t.
Proof.
  intros M t.
  induction t as [n | | a IHa | a IHa b IHb | a IHa b IHb];
    simpl; intros e e' h; try reflexivity.
  - apply h. reflexivity.
  - now rewrite (IHa e e' h).
  - rewrite (IHa e e' (fun n hn => h n (or_introl hn))).
    rewrite (IHb e e' (fun n hn => h n (or_intror hn))).
    reflexivity.
  - rewrite (IHa e e' (fun n hn => h n (or_introl hn))).
    rewrite (IHb e e' (fun n hn => h n (or_intror hn))).
    reflexivity.
Qed.

Lemma raw_formula_sat_ext_free : forall (M : RawPAModel)
    (phi : PA.formula) (e e' : nat -> M),
  (forall n, PA.Formula.Free n phi -> e n = e' n) ->
  (raw_formula_sat M e phi <-> raw_formula_sat M e' phi).
Proof.
  intros M phi.
  induction phi as [a b | | a IHa b IHb | a IHa b IHb |
      a IHa b IHb | a IHa | a IHa];
    simpl; intros e e' h.
  - rewrite (raw_term_eval_ext_free M a e e'
      (fun n hn => h n (or_introl hn))).
    rewrite (raw_term_eval_ext_free M b e e'
      (fun n hn => h n (or_intror hn))).
    reflexivity.
  - reflexivity.
  - split; intros hp hi.
    + apply (proj1 (IHb e e' (fun n hn => h n (or_intror hn)))).
      apply hp.
      apply (proj2 (IHa e e' (fun n hn => h n (or_introl hn)))).
      exact hi.
    + apply (proj2 (IHb e e' (fun n hn => h n (or_intror hn)))).
      apply hp.
      apply (proj1 (IHa e e' (fun n hn => h n (or_introl hn)))).
      exact hi.
  - split; intros [ha hb]; split.
    + apply (proj1 (IHa e e' (fun n hn => h n (or_introl hn)))); exact ha.
    + apply (proj1 (IHb e e' (fun n hn => h n (or_intror hn)))); exact hb.
    + apply (proj2 (IHa e e' (fun n hn => h n (or_introl hn)))); exact ha.
    + apply (proj2 (IHb e e' (fun n hn => h n (or_intror hn)))); exact hb.
  - split; intros hp.
    + destruct hp as [ha | hb].
      * left. apply (proj1 (IHa e e'
          (fun n hn => h n (or_introl hn)))); exact ha.
      * right. apply (proj1 (IHb e e'
          (fun n hn => h n (or_intror hn)))); exact hb.
    + destruct hp as [ha | hb].
      * left. apply (proj2 (IHa e e'
          (fun n hn => h n (or_introl hn)))); exact ha.
      * right. apply (proj2 (IHb e e'
          (fun n hn => h n (or_intror hn)))); exact hb.
  - split; intros hall d.
    + apply (proj1 (IHa (scons M d e) (scons M d e')
        (fun n hn => match n as k return
          PA.Formula.Free k a ->
          scons M d e k = scons M d e' k
        with
        | 0 => fun _ => eq_refl
        | S k => fun hk => h k hk
        end hn))).
      exact (hall d).
    + apply (proj2 (IHa (scons M d e) (scons M d e')
        (fun n hn => match n as k return
          PA.Formula.Free k a ->
          scons M d e k = scons M d e' k
        with
        | 0 => fun _ => eq_refl
        | S k => fun hk => h k hk
        end hn))).
      exact (hall d).
  - split; intros hex.
    + destruct hex as [d hd]. exists d.
      apply (proj1 (IHa (scons M d e) (scons M d e')
        (fun n hn => match n as k return
          PA.Formula.Free k a ->
          scons M d e k = scons M d e' k
        with
        | 0 => fun _ => eq_refl
        | S k => fun hk => h k hk
        end hn))).
      exact hd.
    + destruct hex as [d hd]. exists d.
      apply (proj2 (IHa (scons M d e) (scons M d e')
        (fun n hn => match n as k return
          PA.Formula.Free k a ->
          scons M d e k = scons M d e' k
        with
        | 0 => fun _ => eq_refl
        | S k => fun hk => h k hk
        end hn))).
      exact hd.
Qed.

(** A finite-tree program language.  Selector indices refer to positions in
    [formula_rank_enum selectorRank]; hence a later arithmetization needs only
    finitely many fixed formula branches, never a truth predicate. *)
Inductive SkolemProgram : Type :=
| spSeed : SkolemProgram
| spZero : SkolemProgram
| spSucc : SkolemProgram -> SkolemProgram
| spAdd : SkolemProgram -> SkolemProgram -> SkolemProgram
| spMul : SkolemProgram -> SkolemProgram -> SkolemProgram
| spChoose : nat -> SkolemProgramArgs -> SkolemProgram
with SkolemProgramArgs : Type :=
| spaNil : SkolemProgramArgs
| spaCons : SkolemProgram -> SkolemProgramArgs -> SkolemProgramArgs.

Scheme SkolemProgram_ind' := Induction for SkolemProgram Sort Prop
with SkolemProgramArgs_ind' := Induction for SkolemProgramArgs Sort Prop.
Combined Scheme SkolemProgram_mutind from SkolemProgram_ind',
  SkolemProgramArgs_ind'.

Definition selectorBody (selectorRank i : nat) : PA.formula :=
  nth i (formula_rank_enum selectorRank) PA.pBot.

Lemma nth_of_In : forall (A : Type) (default x : A) xs,
  In x xs -> exists i, nth i xs default = x.
Proof.
  intros A default x xs.
  induction xs as [|a xs IH]; simpl; intro hx.
  - contradiction.
  - destruct hx as [hx | hx].
    + subst a. exists 0. reflexivity.
    + destruct (IH hx) as [i hi].
      exists (S i). exact hi.
Qed.

Lemma selectorBody_complete : forall selectorRank body,
  formula_rank body <= selectorRank ->
  exists i, selectorBody selectorRank i = body.
Proof.
  intros selectorRank body hrank.
  unfold selectorBody.
  apply (nth_of_In PA.formula PA.pBot body).
  exact (formula_rank_enum_complete selectorRank body hrank).
Qed.

Definition rawSkolemWitness (M : RawPAModel) (body : PA.formula)
    (e : nat -> M) : M :=
  epsilon (inhabits (raw_zero M))
    (fun d => raw_formula_sat M (scons M d e) body).

Lemma rawSkolemWitness_spec : forall (M : RawPAModel) body e,
  (exists d, raw_formula_sat M (scons M d e) body) ->
  raw_formula_sat M
    (scons M (rawSkolemWitness M body e) e) body.
Proof.
  intros M body e hex.
  unfold rawSkolemWitness.
  exact (epsilon_spec (inhabits (raw_zero M))
    (fun d => raw_formula_sat M (scons M d e) body) hex).
Qed.

Section Evaluation.

Context (M : RawPAModel) (seed : M) (selectorRank : nat)
  (selector : PA.formula -> (nat -> M) -> M).

Fixpoint skolemProgramEval (p : SkolemProgram) : M :=
  match p with
  | spSeed => seed
  | spZero => raw_zero M
  | spSucc a => raw_succ M (skolemProgramEval a)
  | spAdd a b => raw_add M (skolemProgramEval a) (skolemProgramEval b)
  | spMul a b => raw_mul M (skolemProgramEval a) (skolemProgramEval b)
  | spChoose i args =>
      selector (selectorBody selectorRank i)
        (fun n => skolemProgramArgsEval args n)
  end
with skolemProgramArgsEval (args : SkolemProgramArgs) (n : nat) : M :=
  match args, n with
  | spaNil, _ => raw_zero M
  | spaCons p _, 0 => skolemProgramEval p
  | spaCons _ ps, S k => skolemProgramArgsEval ps k
  end.

Definition SkolemHull : Type :=
  { x : M | exists p : SkolemProgram, skolemProgramEval p = x }.

Definition skolemHullZero : SkolemHull :=
  exist _ (raw_zero M) (ex_intro _ spZero eq_refl).

Definition skolemHullSeed : SkolemHull :=
  exist _ seed (ex_intro _ spSeed eq_refl).

Definition skolemHullSucc (x : SkolemHull) : SkolemHull.
Proof.
  refine (exist _ (raw_succ M (proj1_sig x)) _).
  destruct (proj2_sig x) as [p hp].
  exists (spSucc p). simpl. now rewrite hp.
Defined.

Definition skolemHullAdd (x y : SkolemHull) : SkolemHull.
Proof.
  refine (exist _ (raw_add M (proj1_sig x) (proj1_sig y)) _).
  destruct (proj2_sig x) as [p hp].
  destruct (proj2_sig y) as [q hq].
  exists (spAdd p q). simpl. now rewrite hp, hq.
Defined.

Definition skolemHullMul (x y : SkolemHull) : SkolemHull.
Proof.
  refine (exist _ (raw_mul M (proj1_sig x) (proj1_sig y)) _).
  destruct (proj2_sig x) as [p hp].
  destruct (proj2_sig y) as [q hq].
  exists (spMul p q). simpl. now rewrite hp, hq.
Defined.

Definition skolemHullRawModel : RawPAModel :=
  {| raw_carrier := SkolemHull;
     raw_zero := skolemHullZero;
     raw_succ := skolemHullSucc;
     raw_add := skolemHullAdd;
     raw_mul := skolemHullMul |}.

Definition skolemHullVal (x : skolemHullRawModel) : M := proj1_sig x.

Lemma skolemHullVal_zero :
  skolemHullVal (raw_zero skolemHullRawModel) = raw_zero M.
Proof. reflexivity. Qed.

Lemma skolemHullVal_succ : forall x,
  skolemHullVal (raw_succ skolemHullRawModel x) =
  raw_succ M (skolemHullVal x).
Proof. reflexivity. Qed.

Lemma skolemHullVal_add : forall x y,
  skolemHullVal (raw_add skolemHullRawModel x y) =
  raw_add M (skolemHullVal x) (skolemHullVal y).
Proof. reflexivity. Qed.

Lemma skolemHullVal_mul : forall x y,
  skolemHullVal (raw_mul skolemHullRawModel x y) =
  raw_mul M (skolemHullVal x) (skolemHullVal y).
Proof. reflexivity. Qed.

Lemma skolemHullVal_scons : forall (x : SkolemHull)
    (e : nat -> SkolemHull),
  (fun n => skolemHullVal (scons SkolemHull x e n)) =
  scons M (skolemHullVal x) (fun n => skolemHullVal (e n)).
Proof.
  intros x e.
  apply functional_extensionality.
  intros [|n]; reflexivity.
Qed.

Lemma skolemHull_term_eval : forall (e : nat -> skolemHullRawModel) t,
  skolemHullVal (raw_term_eval skolemHullRawModel e t) =
  raw_term_eval M (fun n => skolemHullVal (e n)) t.
Proof.
  intros e t.
  induction t; cbn [raw_term_eval].
  - reflexivity.
  - reflexivity.
  - change (raw_succ M
      (skolemHullVal (raw_term_eval skolemHullRawModel e t)) =
      raw_succ M
        (raw_term_eval M (fun n => skolemHullVal (e n)) t)).
    now rewrite IHt.
  - change (raw_add M
      (skolemHullVal (raw_term_eval skolemHullRawModel e t1))
      (skolemHullVal (raw_term_eval skolemHullRawModel e t2)) =
      raw_add M
        (raw_term_eval M (fun n => skolemHullVal (e n)) t1)
        (raw_term_eval M (fun n => skolemHullVal (e n)) t2)).
    now rewrite IHt1, IHt2.
  - change (raw_mul M
      (skolemHullVal (raw_term_eval skolemHullRawModel e t1))
      (skolemHullVal (raw_term_eval skolemHullRawModel e t2)) =
      raw_mul M
        (raw_term_eval M (fun n => skolemHullVal (e n)) t1)
        (raw_term_eval M (fun n => skolemHullVal (e n)) t2)).
    now rewrite IHt1, IHt2.
Qed.

(** Choose one program representing each hull element.  This is external
    classical choice over the image predicate; it adds no axiom to the raw
    arithmetic structure. *)
Definition skolemHullProgram (x : SkolemHull) : SkolemProgram :=
  proj1_sig (constructive_indefinite_description
    (fun p : SkolemProgram => skolemProgramEval p = proj1_sig x)
    (proj2_sig x)).

Lemma skolemHullProgram_spec : forall x : SkolemHull,
  skolemProgramEval (skolemHullProgram x) = proj1_sig x.
Proof.
  intro x.
  unfold skolemHullProgram.
  exact (proj2_sig (constructive_indefinite_description
    (fun p : SkolemProgram => skolemProgramEval p = proj1_sig x)
    (proj2_sig x))).
Qed.

Fixpoint skolemProgramArgsOfEnv (k : nat)
    (e : nat -> SkolemHull) : SkolemProgramArgs :=
  match k with
  | 0 => spaNil
  | S j => spaCons (skolemHullProgram (e 0))
      (skolemProgramArgsOfEnv j (fun n => e (S n)))
  end.

Lemma skolemProgramArgsOfEnv_spec : forall k (e : nat -> SkolemHull) n,
  n < k ->
  skolemProgramArgsEval (skolemProgramArgsOfEnv k e) n =
  skolemHullVal (e n).
Proof.
  induction k as [|k IH]; intros e [|n] hn; simpl in *; try lia.
  - apply skolemHullProgram_spec.
  - apply (IH (fun j => e (S j)) n). lia.
Qed.

Definition skolemHullChoose (i : nat) (args : SkolemProgramArgs) :
    SkolemHull :=
  exist _ (skolemProgramEval (spChoose i args))
    (ex_intro _ (spChoose i args) eq_refl).

Lemma skolemHullChoose_val : forall i args,
  skolemHullVal (skolemHullChoose i args) =
  selector (selectorBody selectorRank i)
    (fun n => skolemProgramArgsEval args n).
Proof. reflexivity. Qed.

Lemma skolemArgs_scons_agree_free :
  forall (body : PA.formula) (e : nat -> SkolemHull) d n,
    PA.Formula.Free n body ->
    scons M d
      (fun j => skolemProgramArgsEval
        (skolemProgramArgsOfEnv (PA.Formula.bound body) e) j) n =
    scons M d (fun j => skolemHullVal (e j)) n.
Proof.
  intros body e d [|n] hfree; simpl.
  - reflexivity.
  - apply skolemProgramArgsOfEnv_spec.
    pose proof (PA.Formula.free_lt_bound body (S n) hfree).
    lia.
Qed.

(** Rank-bounded Tarski--Vaught theorem.  The same selector rank is enough:
    existential formulas select witnesses for their strictly smaller bodies,
    while the negated body used for a universal formula has rank no larger
    than the universal formula itself. *)
Theorem skolemHull_formula_elementary : forall k phi,
  (forall body env,
    (exists d, raw_formula_sat M (scons M d env) body) ->
    raw_formula_sat M (scons M (selector body env) env) body) ->
  formula_rank phi <= k ->
  k <= selectorRank ->
  forall e : nat -> skolemHullRawModel,
    (raw_formula_sat skolemHullRawModel e phi <->
     raw_formula_sat M (fun n => skolemHullVal (e n)) phi).
Proof.
  intros k phi.
  revert k.
  induction phi as [a b | | a IHa b IHb | a IHa b IHb |
      a IHa b IHb | a IHa | a IHa];
    intros k hselector hrank hselectors e; simpl in hrank |- *.
  - change ((raw_term_eval skolemHullRawModel e a =
      raw_term_eval skolemHullRawModel e b) <->
      raw_term_eval M (fun n => skolemHullVal (e n)) a =
      raw_term_eval M (fun n => skolemHullVal (e n)) b).
    split; intro heq.
    + apply (f_equal skolemHullVal) in heq.
      now rewrite !skolemHull_term_eval in heq.
    + assert (hval :
          skolemHullVal (raw_term_eval skolemHullRawModel e a) =
          skolemHullVal (raw_term_eval skolemHullRawModel e b)).
      {
        now rewrite !skolemHull_term_eval.
      }
      destruct (raw_term_eval skolemHullRawModel e a) as [x hx].
      destruct (raw_term_eval skolemHullRawModel e b) as [y hy].
      simpl in hval. subst y.
      f_equal. apply proof_irrelevance.
  - reflexivity.
  - assert (hra : formula_rank a <= k).
    { pose proof (Nat.le_max_l (formula_rank a) (formula_rank b)). lia. }
    assert (hrb : formula_rank b <= k).
    { pose proof (Nat.le_max_r (formula_rank a) (formula_rank b)). lia. }
    rewrite (IHa k hselector hra hselectors e),
      (IHb k hselector hrb hselectors e).
    reflexivity.
  - assert (hra : formula_rank a <= k).
    { pose proof (Nat.le_max_l (formula_rank a) (formula_rank b)). lia. }
    assert (hrb : formula_rank b <= k).
    { pose proof (Nat.le_max_r (formula_rank a) (formula_rank b)). lia. }
    rewrite (IHa k hselector hra hselectors e),
      (IHb k hselector hrb hselectors e).
    reflexivity.
  - assert (hra : formula_rank a <= k).
    { pose proof (Nat.le_max_l (formula_rank a) (formula_rank b)). lia. }
    assert (hrb : formula_rank b <= k).
    { pose proof (Nat.le_max_r (formula_rank a) (formula_rank b)). lia. }
    rewrite (IHa k hselector hra hselectors e),
      (IHb k hselector hrb hselectors e).
    reflexivity.
  - assert (hra : formula_rank a <= k) by lia.
    split.
    + intros hall d.
      apply NNPP. intro hnot.
      set (negBody := PA.pImp a PA.pBot).
      assert (hrneg : formula_rank negBody <= selectorRank).
      {
        unfold negBody. simpl.
        pose proof (formula_rank_positive a) as hpositive.
        replace (Nat.max (formula_rank a) 1) with (formula_rank a)
          by (symmetry; apply Nat.max_l; lia).
        lia.
      }
      destruct (selectorBody_complete selectorRank negBody hrneg)
        as [i hi].
      set (args := skolemProgramArgsOfEnv
        (PA.Formula.bound negBody) e).
      assert (hexActual : exists x : M,
          raw_formula_sat M
            (scons M x (fun n => skolemHullVal (e n))) negBody).
      {
        exists d. unfold negBody. simpl. exact hnot.
      }
      assert (hexCanonical : exists x : M,
          raw_formula_sat M
            (scons M x (fun n => skolemProgramArgsEval args n))
            negBody).
      {
        destruct hexActual as [x hx]. exists x.
        assert (henv : forall n, PA.Formula.Free n negBody ->
            scons M x (fun n => skolemHullVal (e n)) n =
            scons M x (fun n => skolemProgramArgsEval args n) n).
        {
          intros n hn.
          symmetry.
          unfold args.
          apply skolemArgs_scons_agree_free. exact hn.
        }
        apply (proj1 (raw_formula_sat_ext_free M negBody
          (scons M x (fun n => skolemHullVal (e n)))
          (scons M x (fun n => skolemProgramArgsEval args n)) henv)).
        exact hx.
      }
      pose (w := skolemHullChoose i args).
      assert (hnegCanonical :
          raw_formula_sat M
            (scons M (skolemHullVal w)
              (fun n => skolemProgramArgsEval args n)) negBody).
      {
        unfold w.
        rewrite skolemHullChoose_val, hi.
        apply hselector.
        exact hexCanonical.
      }
      assert (hnegActual :
          raw_formula_sat M
            (scons M (skolemHullVal w)
              (fun n => skolemHullVal (e n))) negBody).
      {
        assert (henv : forall n, PA.Formula.Free n negBody ->
            scons M (skolemHullVal w)
              (fun n => skolemProgramArgsEval args n) n =
            scons M (skolemHullVal w)
              (fun n => skolemHullVal (e n)) n).
        {
          intros n hn.
          unfold args.
          apply skolemArgs_scons_agree_free. exact hn.
        }
        apply (proj1 (raw_formula_sat_ext_free M negBody
          (scons M (skolemHullVal w)
            (fun n => skolemProgramArgsEval args n))
          (scons M (skolemHullVal w)
            (fun n => skolemHullVal (e n))) henv)).
        exact hnegCanonical.
      }
      unfold negBody in hnegActual. simpl in hnegActual.
      apply hnegActual.
      pose proof (proj1
        (IHa k hselector hra hselectors (scons SkolemHull w e))
        (hall w)) as ha.
      rewrite skolemHullVal_scons in ha.
      exact ha.
    + intros hall w.
      apply (proj2 (IHa k hselector hra hselectors
        (scons SkolemHull w e))).
      rewrite skolemHullVal_scons.
      exact (hall (skolemHullVal w)).
  - assert (hra : formula_rank a <= k) by lia.
    split.
    + intros [w hw].
      exists (skolemHullVal w).
      pose proof (proj1
        (IHa k hselector hra hselectors (scons SkolemHull w e)) hw) as ha.
      rewrite skolemHullVal_scons in ha.
      exact ha.
    + intros [d hd].
      assert (hrbody : formula_rank a <= selectorRank) by lia.
      destruct (selectorBody_complete selectorRank a hrbody) as [i hi].
      set (args := skolemProgramArgsOfEnv (PA.Formula.bound a) e).
      assert (hexCanonical : exists x : M,
          raw_formula_sat M
            (scons M x (fun n => skolemProgramArgsEval args n)) a).
      {
        exists d.
        assert (henv : forall n, PA.Formula.Free n a ->
            scons M d (fun n => skolemHullVal (e n)) n =
            scons M d (fun n => skolemProgramArgsEval args n) n).
        {
          intros n hn.
          symmetry.
          unfold args.
          apply skolemArgs_scons_agree_free. exact hn.
        }
        apply (proj1 (raw_formula_sat_ext_free M a
          (scons M d (fun n => skolemHullVal (e n)))
          (scons M d (fun n => skolemProgramArgsEval args n)) henv)).
        exact hd.
      }
      pose (w := skolemHullChoose i args).
      exists w.
      apply (proj2 (IHa k hselector hra hselectors
        (scons SkolemHull w e))).
      rewrite skolemHullVal_scons.
      assert (hwCanonical :
          raw_formula_sat M
            (scons M (skolemHullVal w)
              (fun n => skolemProgramArgsEval args n)) a).
      {
        unfold w.
        rewrite skolemHullChoose_val, hi.
        apply hselector.
        exact hexCanonical.
      }
      assert (henv : forall n, PA.Formula.Free n a ->
          scons M (skolemHullVal w)
            (fun n => skolemProgramArgsEval args n) n =
          scons M (skolemHullVal w)
            (fun n => skolemHullVal (e n)) n).
      {
        intros n hn.
        unfold args.
        apply skolemArgs_scons_agree_free. exact hn.
      }
      apply (proj1 (raw_formula_sat_ext_free M a
        (scons M (skolemHullVal w)
          (fun n => skolemProgramArgsEval args n))
        (scons M (skolemHullVal w)
          (fun n => skolemHullVal (e n))) henv)).
      exact hwCanonical.
Qed.

End Evaluation.

(** A convenient finite syntax bound for all sealed axioms in a canonical
    rank fragment.  Taking the maximum after sealing avoids any separate
    argument about environments of closed formulas. *)
Fixpoint formulaListRankMax (fs : list PA.formula) : nat :=
  match fs with
  | [] => 0
  | phi :: rest => Nat.max (formula_rank phi) (formulaListRankMax rest)
  end.

Lemma formulaListRankMax_spec : forall fs phi,
  In phi fs -> formula_rank phi <= formulaListRankMax fs.
Proof.
  induction fs as [|a fs IH]; simpl; intros phi hphi.
  - contradiction.
  - destruct hphi as [hphi | hphi].
    + subst phi. apply Nat.le_max_l.
    + eapply Nat.le_trans.
      * apply IH. exact hphi.
      * apply Nat.le_max_r.
Qed.

Definition rankFragmentSyntaxRank (n : nat) : nat :=
  formulaListRankMax (PA_rank_fragment_enum n).

Lemma rankFragmentSyntaxRank_spec : forall n phi,
  PARankFragment n phi ->
  formula_rank phi <= rankFragmentSyntaxRank n.
Proof.
  intros n phi hphi.
  unfold rankFragmentSyntaxRank.
  apply formulaListRankMax_spec.
  apply (proj2 (PA_rank_fragment_enum_spec n phi)).
  exact hphi.
Qed.

Definition SelectorWitnesses (M : RawPAModel)
    (selector : PA.formula -> (nat -> M) -> M) : Prop :=
  forall body env,
    (exists d, raw_formula_sat M (scons M d env) body) ->
    raw_formula_sat M (scons M (selector body env) env) body.

Lemma rawSkolemWitness_witnesses : forall M,
  SelectorWitnesses M (rawSkolemWitness M).
Proof.
  intros M body env hex.
  exact (rawSkolemWitness_spec M body env hex).
Qed.

(** Any ambient raw model of full PA transfers the entire canonical fragment
    to a finite Skolem hull at any sufficiently large support rank.  No
    arithmetic induction is hidden in the carrier: it enters solely through
    the ambient validity assumption. *)
Theorem skolemHull_satisfies_rank_fragment_at_rank :
  forall (M : RawPAModel) (seed : M) n selectorRank selector,
    rankFragmentSyntaxRank n <= selectorRank ->
    SelectorWitnesses M selector ->
    RawModelSatisfies M PA.Formula.Ax_s ->
    RawModelSatisfies
      (skolemHullRawModel M seed selectorRank selector)
      (PARankFragment n).
Proof.
  intros M seed n selectorRank selector hRank hselector hPA phi hphi e.
  apply (proj2 (skolemHull_formula_elementary M seed
    selectorRank selector
    (rankFragmentSyntaxRank n) phi hselector
    (rankFragmentSyntaxRank_spec n phi hphi)
    hRank e)).
  exact (hPA phi (PA_rank_fragment_subset_ax_s n phi hphi)
    (fun j => skolemHullVal M seed selectorRank
      selector (e j))).
Qed.

(** Backwards-compatible specialization at the first trivially larger
    support rank. *)
Theorem skolemHull_satisfies_rank_fragment :
  forall (M : RawPAModel) (seed : M) n selector,
    SelectorWitnesses M selector ->
    RawModelSatisfies M PA.Formula.Ax_s ->
    RawModelSatisfies
      (skolemHullRawModel M seed (S (rankFragmentSyntaxRank n)) selector)
      (PARankFragment n).
Proof.
  intros M seed n selector hselector hPA.
  apply skolemHull_satisfies_rank_fragment_at_rank.
  - exact (Nat.le_succ_diag_r (rankFragmentSyntaxRank n)).
  - exact hselector.
  - exact hPA.
Qed.

End PAFiniteSkolemHull.
