import LeanProofs.FermatFour
import LeanProofs.FloorSqrtSum
import LeanProofs.RationalFloorOrbit
import LeanProofs.TinyExponentTower
import LeanProofs.TrigGoldenRatio
import LeanProofs.ArctanSquareIdentity
import LeanProofs.Nicod
