import BusyBeaver.BB4.Certificates.R05.A14.Guided.Common

set_option maxRecDepth 10000

namespace SetTheory.BusyBeaver.BB4.Certificates.R05A14Guided

open Certificates

def work_a00_a15_a02 : Guided.Work :=
  after [a00, a15, a02]

def certificate_a00_a15_a02 : Guided.Certificate :=
  Guided.Certificate.branch16
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.branch16
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1))
    (Guided.Certificate.branch16
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)))
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)
    (Guided.Certificate.bool1)

theorem verified_a00_a15_a02 :
    work_a00_a15_a02.check certificate_a00_a15_a02 = true := by
  decide

end SetTheory.BusyBeaver.BB4.Certificates.R05A14Guided
