name = "PAUndecidable"
defaultTargets = ["PAUndecidable", "PAUndecidable.Audit"]

[[lean_lib]]
name = "PAUndecidable"

[[lean_lib]]
name = "Foundation"
srcDir = "../../../../lib/FormalizedFormalLogic-Foundation"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.32.0"
