name = "MonotonicityOfEntailment"
defaultTargets = ["MonotonicityOfEntailment"]

[[lean_lib]]
name = "NaturalDeduction"
srcDir = "../../NaturalDeduction/Lean"

[[lean_lib]]
name = "MonotonicityOfEntailment"
