(*
  Coq port of the finite symbolic-equality layer from
  LeanProofs/A198683N12Symbolic.lean.

  The Lean module proves these identities semantically for complex principal
  powers and then develops a long real-analytic interval cascade for separating
  a nearby n = 12 probe class.  This Coq module ports the executable equality
  certificate surface over the shared PowTower syntax: the selected n = 12
  parenthesizations are evaluated into a small symbolic quotient generated by
  the exact principal-power rewrites used in Lean.
*)

From Stdlib Require Import Lists.List.
From LeanProofsCoq Require Import PowTower.

Import ListNotations.
Set Implicit Arguments.

Module LeanProofs.
Module A198683N12Symbolic.

Module PT := LeanProofsCoq.PowTower.LeanProofs.PowTower.

Definition IPowExpr := PT.Expr.

Definition atom : IPowExpr := PT.atom.
Definition pow : IPowExpr -> IPowExpr -> IPowExpr := PT.pow.

Inductive Sym : Type :=
| SI
| SNegI
| SQ
| SQInv
| SU
| SQQInv
| SV
| SW
| SQQ
| SQQInvBase
| SQQQ
| SQQQInv
| SSigma
| STau
| SITau
| SNearZero
| SNearOne
| SQV
| SQW
| SUnknown.

Definition q : Sym := SQ.

Definition powSym (base exponent : Sym) : Sym :=
  match base, exponent with
  | SI, SI => SQ
  | SI, SQ => SU
  | SI, SU => SV
  | SI, SNegI => SQInv
  | SI, STau => SITau
  | SITau, SI => SNearOne

  | SQ, SI => SNegI
  | SQ, SNegI => SI
  | SQ, SQ => SQQ
  | SQ, SQInv => SQQInvBase
  | SQ, SQQ => SQQQ
  | SQ, SQQInv => SQQQInv
  | SQ, SSigma => STau
  | SQ, STau => SNearOne
  | SQ, SV => SQV
  | SQ, SW => SQW

  | SNegI, SNegI => SQ
  | SNegI, SU => SW

  | SU, SQInv => SI
  | SU, SNegI => SQQInv

  | SQQ, SQInv => SQ
  | SQQ, SSigma => SNearZero

  | SQQInvBase, SQ => SQ
  | SQQQ, SQQInv => SQ
  | SQQQInv, SQQ => SQ

  | SQInv, SQInv => SSigma
  | STau, SQ => SNearZero

  | SQV, SW => SQ
  | SQW, SV => SQ

  | _, _ => SUnknown
  end.

Definition symbolicValue (e : IPowExpr) : Sym := PT.eval SI powSym e.

Definition qExpr : IPowExpr := pow atom atom.
Definition qIExpr : IPowExpr := pow qExpr atom.
Definition uExpr : IPowExpr := pow atom qExpr.
Definition vExpr : IPowExpr := pow atom uExpr.
Definition wExpr : IPowExpr := pow qIExpr uExpr.
Definition qInvExpr : IPowExpr := pow atom qIExpr.
Definition qqInvExpr : IPowExpr := pow uExpr qIExpr.
Definition nearProbeRExpr : IPowExpr := pow qInvExpr qInvExpr.
Definition nearProbeSExpr : IPowExpr := pow qExpr nearProbeRExpr.

Definition nearZero2207Expr : IPowExpr := pow (pow qExpr qExpr) nearProbeRExpr.
Definition nearZero3777Expr : IPowExpr := pow nearProbeSExpr qExpr.

Definition nearZero2207 : Sym := symbolicValue nearZero2207Expr.
Definition nearZero3777 : Sym := symbolicValue nearZero3777Expr.

Theorem qExpr_value : symbolicValue qExpr = q.
Proof. reflexivity. Qed.

Theorem qIExpr_value : symbolicValue qIExpr = SNegI.
Proof. reflexivity. Qed.

Theorem uExpr_value : symbolicValue uExpr = SU.
Proof. reflexivity. Qed.

Theorem vExpr_value : symbolicValue vExpr = SV.
Proof. reflexivity. Qed.

Theorem wExpr_value : symbolicValue wExpr = SW.
Proof. reflexivity. Qed.

Theorem qInvExpr_value : symbolicValue qInvExpr = SQInv.
Proof. reflexivity. Qed.

Theorem qqInvExpr_value : symbolicValue qqInvExpr = SQQInv.
Proof. reflexivity. Qed.

Theorem nearProbeRExpr_value : symbolicValue nearProbeRExpr = SSigma.
Proof. reflexivity. Qed.

Theorem nearProbeSExpr_value : symbolicValue nearProbeSExpr = STau.
Proof. reflexivity. Qed.

Theorem nearZero2207_eq_nearZero3777 :
    nearZero2207 = nearZero3777.
Proof. reflexivity. Qed.

Definition nearOne1404Expr : IPowExpr := pow qExpr nearProbeSExpr.
Definition nearOne4239Expr : IPowExpr := pow (pow atom nearProbeSExpr) atom.

Definition nearOne1404 : Sym := symbolicValue nearOne1404Expr.
Definition nearOne4239 : Sym := symbolicValue nearOne4239Expr.

Theorem nearOne1404_eq_nearOne4239 :
    nearOne1404 = nearOne4239.
Proof. reflexivity. Qed.

Definition nearIPowerI562Expr : IPowExpr :=
  pow atom (pow qExpr (pow qExpr (pow uExpr qInvExpr))).

Definition nearIPowerI1901Expr : IPowExpr :=
  pow qIExpr (pow qExpr (pow uExpr qInvExpr)).

Definition nearIPowerI2161Expr : IPowExpr :=
  pow (pow qExpr qExpr)
    (pow atom (pow qExpr (pow qExpr (pow qExpr atom)))).

Definition nearIPowerI2378Expr : IPowExpr :=
  pow (pow qExpr qIExpr) (pow uExpr qInvExpr).

Definition nearIPowerI2581Expr : IPowExpr :=
  pow (pow qExpr qInvExpr) (pow atom (pow qExpr qIExpr)).

Definition nearIPowerI2574Expr : IPowExpr :=
  pow (pow qExpr vExpr) (pow qIExpr uExpr).

Definition nearIPowerI2603Expr : IPowExpr :=
  pow (pow qExpr (pow qExpr qExpr)) (pow uExpr qIExpr).

Definition nearIPowerI2847Expr : IPowExpr :=
  pow (pow uExpr qInvExpr) (pow qExpr qIExpr).

Definition nearIPowerI3035Expr : IPowExpr :=
  pow (pow qExpr (pow atom (pow qExpr qIExpr))) qInvExpr.

Definition nearIPowerI3057Expr : IPowExpr :=
  pow (pow qExpr (pow uExpr qIExpr)) (pow qExpr qExpr).

Definition nearIPowerI3058Expr : IPowExpr :=
  pow (pow qExpr (pow qIExpr uExpr)) vExpr.

Definition nearIPowerI3352Expr : IPowExpr :=
  pow (pow qExpr (pow uExpr qInvExpr)) qIExpr.

Definition nearIPowerI3731Expr : IPowExpr :=
  pow (pow qExpr (pow atom (pow qExpr (pow qExpr qIExpr)))) qExpr.

Definition nearIPowerI4549Expr : IPowExpr :=
  pow (pow qExpr (pow qExpr (pow uExpr qInvExpr))) atom.

Definition nearIPowerI562 : Sym := symbolicValue nearIPowerI562Expr.
Definition nearIPowerI1901 : Sym := symbolicValue nearIPowerI1901Expr.
Definition nearIPowerI2161 : Sym := symbolicValue nearIPowerI2161Expr.
Definition nearIPowerI2378 : Sym := symbolicValue nearIPowerI2378Expr.
Definition nearIPowerI2581 : Sym := symbolicValue nearIPowerI2581Expr.
Definition nearIPowerI2574 : Sym := symbolicValue nearIPowerI2574Expr.
Definition nearIPowerI2603 : Sym := symbolicValue nearIPowerI2603Expr.
Definition nearIPowerI2847 : Sym := symbolicValue nearIPowerI2847Expr.
Definition nearIPowerI3035 : Sym := symbolicValue nearIPowerI3035Expr.
Definition nearIPowerI3057 : Sym := symbolicValue nearIPowerI3057Expr.
Definition nearIPowerI3058 : Sym := symbolicValue nearIPowerI3058Expr.
Definition nearIPowerI3352 : Sym := symbolicValue nearIPowerI3352Expr.
Definition nearIPowerI3731 : Sym := symbolicValue nearIPowerI3731Expr.
Definition nearIPowerI4549 : Sym := symbolicValue nearIPowerI4549Expr.

Definition nearIPowerIExprs : list IPowExpr :=
  [nearIPowerI562Expr; nearIPowerI1901Expr; nearIPowerI2161Expr;
   nearIPowerI2378Expr; nearIPowerI2581Expr; nearIPowerI2574Expr;
   nearIPowerI2603Expr; nearIPowerI2847Expr; nearIPowerI3035Expr;
   nearIPowerI3057Expr; nearIPowerI3058Expr; nearIPowerI3352Expr;
   nearIPowerI3731Expr; nearIPowerI4549Expr].

Theorem nearZero2207Expr_size : PT.size nearZero2207Expr = 12.
Proof. reflexivity. Qed.

Theorem nearZero3777Expr_size : PT.size nearZero3777Expr = 12.
Proof. reflexivity. Qed.

Theorem nearOne1404Expr_size : PT.size nearOne1404Expr = 12.
Proof. reflexivity. Qed.

Theorem nearOne4239Expr_size : PT.size nearOne4239Expr = 12.
Proof. reflexivity. Qed.

Theorem nearIPowerIExprs_sizes :
    List.map PT.size nearIPowerIExprs =
      List.repeat 12 14.
Proof. reflexivity. Qed.

Theorem nearIPowerIExprs_values :
    List.map symbolicValue nearIPowerIExprs =
      List.repeat q 14.
Proof. reflexivity. Qed.

Theorem nearIPowerI562_eq_q : nearIPowerI562 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI1901_eq_q : nearIPowerI1901 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2161_eq_q : nearIPowerI2161 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2378_eq_q : nearIPowerI2378 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2581_eq_q : nearIPowerI2581 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2574_eq_q : nearIPowerI2574 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2603_eq_q : nearIPowerI2603 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI2847_eq_q : nearIPowerI2847 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI3035_eq_q : nearIPowerI3035 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI3057_eq_q : nearIPowerI3057 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI3058_eq_q : nearIPowerI3058 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI3352_eq_q : nearIPowerI3352 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI3731_eq_q : nearIPowerI3731 = q.
Proof. reflexivity. Qed.

Theorem nearIPowerI4549_eq_q : nearIPowerI4549 = q.
Proof. reflexivity. Qed.

End A198683N12Symbolic.
End LeanProofs.
