/-
  Audit.lean — the Lean analogue of the Coq files' trailing `Check` /
  `Print Assumptions` commands: type-check the headline results and print
  the axioms each depends on.  Expected: only Lean's standard classical
  axioms (`Classical.choice`, `propext`, `Quot.sound`) — no `sorry`.
-/
import SetTheory

open SetTheory

-- the headline: full deductive equivalence T ⊢ φ ⟺ ZF ⊢ φ
#check @T_iff_ZF
#print axioms T_iff_ZF
#print axioms T_iff_ZF_via_theory_equiv

-- syntactic directions and same-models
#check @ZF_implies_T
#check @T_implies_ZF
#check @T_ZF_same_models
#print axioms T_ZF_same_models

-- Gödel completeness layer
#check @completeness
#check @prov_iff_valid
#check @completeness_inf
#check @completeness_inf_context
#check @theory_equiv
#check @BProv_ax
#check @BProv_of_Prov
#check @BProv_lift
#check @BProv_cut
#check @BProv_theory_mono
#check @BProv_eqElim
#check @BProv_eqSym
#check @BProv_eqTrans
#check @soundness_BProv
#print axioms prov_iff_valid

-- calculus soundness and the deep reverse (internal recursion theorem)
#check @soundness
#check @ClosureFO_of_ZF
#print axioms ClosureFO_of_ZF

-- Busy Beaver domination interface
#check @BusyBeaver.sigma_mono_of_pos
#check @BusyBeaver.score_le_sigma_of_atMost
#check @BusyBeaver.sigma_eventually_dominates_every_total_recursive
#check @BusyBeaver.sigma_eventually_dominates_every_totalRecursiveInRadoModel
#check @BusyBeaver.sigma_eventually_dominates_every_totalRecursiveEventuallyInRadoModel
#check @BusyBeaver.KnownValues.sigma1Champion_haltsWithScore
#check @BusyBeaver.KnownValues.sigma2Champion_haltsWithScore
#check @BusyBeaver.KnownValues.sigma3Champion_haltsWithScore
#check @BusyBeaver.KnownValues.sigma4Champion_haltsWithScore
#check @BusyBeaver.KnownValues.upperBound_one
#check @BusyBeaver.KnownValues.sigma_one_eq_one
#check @BusyBeaver.KnownValues.a028444_values_through_four_from_upperBounds
#check @BusyBeaver.KnownValues.a028444_values_through_four_from_remainingUpperBounds
#print axioms BusyBeaver.sigma_mono_of_pos
#print axioms BusyBeaver.score_le_sigma_of_atMost
#print axioms BusyBeaver.sigma_eventually_dominates_every_total_recursive
#print axioms BusyBeaver.sigma_eventually_dominates_every_totalRecursiveInRadoModel
#print axioms BusyBeaver.sigma_eventually_dominates_every_totalRecursiveEventuallyInRadoModel
#print axioms BusyBeaver.KnownValues.sigma4Champion_haltsWithScore
#print axioms BusyBeaver.KnownValues.sigma_one_eq_one
#print axioms BusyBeaver.KnownValues.a028444_values_through_four_from_upperBounds
#print axioms BusyBeaver.KnownValues.a028444_values_through_four_from_remainingUpperBounds

-- PA/HF Ackermann/von-Neumann semantic bi-interpretability checkpoint
#check @PA.Formula.Ax
#check @PA.Formula.sat_axiom
#check @PA.Formula.Ax_s
#check @PA.Formula.sat_axiom_s
#check @AckermannHF.not_mem_zero_of_double
#check @AckermannHF.mem_succ_double_iff
#check @AckermannHF.mem_succ_odd_double_iff
#check @AckermannHF.mem_succ_of_double_mem_succ
#check @PA.Formula.HFMemTrace_pred_of_succ_double
#check @PA.Formula.HFMemTrace_pred_of_succ_odd_double
#check @PA.Formula.HFMemTrace_pred_of_succ_div2Step
#check @AckermannHF.mem_succ_double_not_mem_succ_odd_double_of_mem_not_mem
#check @AckermannHF.mem_succ_double_not_mem_succ_double_of_mem_not_mem
#check @AckermannHF.mem_succ_odd_double_not_mem_succ_double_of_mem_not_mem
#check @AckermannHF.mem_succ_odd_double_not_mem_succ_odd_double_of_mem_not_mem
#check @PA.Formula.Prov
#check @PA.Formula.Prov_weaken
#check @PA.Formula.Prov_cons
#check @PA.Formula.rename_ext
#check @PA.Formula.rename_comp
#check @PA.Formula.subst_rename
#check @PA.Formula.rename_subst
#check @PA.Term.subst_comp
#check @PA.Term.subst_rename_succ_up
#check @PA.Term.upSubst_comp
#check @PA.Term.subst_ext_free
#check @PA.Term.subst_id
#check @PA.Formula.subst_comp
#check @PA.Formula.subst_rename_succ_up
#check @PA.Formula.subst_ext_free
#check @PA.Formula.subst_id
#check @PA.Formula.subst_eq_of_sentence
#check @PA.Formula.subst_instTerm_rename_up
#check @PA.Formula.subst_instTerm_subst_up
#check @PA.Formula.term_subst_var_rename
#check @PA.Formula.subst_var_rename
#check @PA.Formula.term_subst_instTerm_var
#check @PA.Formula.subst_instTerm_var
#check @PA.Formula.Prov_rename
#check @PA.Formula.Prov_subst
#check @PA.Formula.Prov_cut
#check @PA.Formula.term_subst_instTerm_rename_succ
#check @PA.Formula.term_subst_instTerm_rename_two_succ
#check @PA.Formula.term_subst_upSubst_instTerm_rename_two_succ
#check @PA.Formula.term_subst_upSubst_instTerm_rename_three_succ
#check @PA.Formula.term_subst_up_up_instTerm_rename_three_succ
#check @PA.Formula.term_subst_up_up_instTerm_rename_two_var_zero
#check @PA.Formula.term_subst_up_up_instTerm_rename_four_succ
#check @PA.Formula.term_subst_up_up_up_instTerm_rename_four_succ
#check @PA.Formula.term_subst_up_up_up_instTerm_rename_five_succ
#check @PA.Formula.term_subst_up_up_up_up_instTerm_rename_five_succ
#check @PA.Formula.term_subst_up_up_up_up_up_instTerm_rename_six_succ
#check @PA.Formula.term_subst_up_up_up_up_up_up_instTerm_rename_seven_succ
#check PA.Formula.iterUpSubst
#check @PA.Formula.term_subst_iterUpSubst_instTerm_var_rename_add_succ
#check @PA.Formula.term_subst_iterUpSubst_instTerm_rename_add_succ
#check @PA.Formula.term_rename_up_succ_rename_succ
#check @PA.Formula.term_subst_instTerm_rename_up_up_succ
#check @PA.Formula.subst_instTerm_rename_succ
#check @PA.Formula.subst_instTerm_var_zero_rename_up_succ
#check @PA.Formula.subst_instTerm_var_zero_up_var_one_rename_up_up_succ_twice
#check @PA.Formula.soundness
#check @PA.Formula.BProv
#check @PA.Formula.BProv_mono
#check @PA.Formula.BProv_weaken_nil
#check @PA.Formula.BProv_ax
#check @PA.Formula.BProv_of_Prov
#check @PA.Formula.BProv_rename_of_sentences
#check @PA.Formula.BProv_subst_of_sentences
#check @PA.Formula.BProv_mp
#check @PA.Formula.BProv_lift
#check @PA.Formula.BProv_cut
#check @PA.Formula.BProv_theory_mono
#check @PA.Formula.BProv_eqElim
#check @PA.Formula.BProv_eqRefl
#check @PA.Formula.BProv_eqSym
#check @PA.Formula.BProv_eqTrans
#check @PA.Formula.BProv_eq_congr_term
#check @PA.Formula.BProv_eq_congr_succ
#check @PA.Formula.BProv_eq_congr_add_left
#check @PA.Formula.BProv_eq_congr_add_right
#check @PA.Formula.BProv_eq_congr_add
#check @PA.Formula.BProv_eq_congr_mul_left
#check @PA.Formula.BProv_eq_congr_mul_right
#check @PA.Formula.BProv_eq_congr_mul
#check @PA.Formula.BProv_context_cons
#check @PA.Formula.BProv_rename_succ_context_cons_of_sentences
#check @PA.Formula.BProv_impI
#check @PA.Formula.BProv_impI_after_prefix
#check @PA.Formula.BProv_andI
#check @PA.Formula.BProv_botE
#check @PA.Formula.BProv_andE1
#check @PA.Formula.BProv_andE2
#check @PA.Formula.BProv_orI1
#check @PA.Formula.BProv_orI2
#check @PA.Formula.BProv_orE
#check @PA.Formula.BProv_allE
#check @PA.Formula.BProv_exI
#check @PA.Formula.BProv_allI_of_sentences
#check @PA.Formula.BProv_closeN_nil_of_sentences
#check @PA.Formula.BProv_exE_of_sentences
#check @PA.Formula.BProv_closeN_allE_rename
#check @PA.Formula.BProv_sealPA_allE_rename
#check @PA.Formula.soundness_BProv
#check @PA.Term.Free
#check @PA.Term.free_lt_bound
#check @PA.Term.numeral
#check @PA.Term.addRightNumeral
#check @PA.Term.mulRightNumeral
#check @PA.Term.numeralValue
#check @PA.Term.eval_numeral
#check @PA.Term.numeralValue_natModel
#check @PA.Term.eval_numeral_natModel
#check @PA.Term.rename_numeral
#check @PA.Term.subst_numeral
#check @PA.Term.numeral_succ
#check @PA.Term.addRightNumeral_numeral
#check @PA.Term.rename_ext
#check @PA.Term.rename_ext_free
#check @PA.Term.rename_id
#check @PA.Term.rename_comp
#check @PA.Term.subst_ext
#check @PA.Term.subst_rename
#check @PA.Term.rename_subst
#check @PA.Formula.substTermAt
#check @PA.Formula.substTermAt_zero
#check @PA.Formula.upSubst_substTermAt
#check @PA.Formula.Free
#check @PA.Formula.Sentence
#check @PA.Formula.Sentences
#check @PA.Formula.rename_ext_free
#check @PA.Formula.rename_id
#check @PA.Formula.rename_eq_of_sentence
#check @PA.Formula.sealPA_sentence
#check @PA.Formula.sentence_ax_s
#check @PA.Formula.BProv_inductionForm_mp
#check @PA.Formula.Ax_s_succInj
#check @PA.Formula.Ax_s_zeroNotSucc
#check @PA.Formula.Ax_s_addZero
#check @PA.Formula.Ax_s_addSucc
#check @PA.Formula.Ax_s_mulZero
#check @PA.Formula.Ax_s_mulSucc
#check @PA.Formula.Ax_s_induction
#check @PA.Formula.BProv_Ax_s_of_sealPA_rename
#check @PA.Formula.BProv_Ax_s_succInj_rename
#check @PA.Formula.BProv_Ax_s_succInj
#check @PA.Formula.BProv_Ax_s_succInj_terms
#check @PA.Formula.BProv_Ax_s_zeroNotSucc_rename
#check @PA.Formula.BProv_Ax_s_zeroNotSucc
#check @PA.Formula.BProv_Ax_s_zeroNotSucc_term
#check @PA.Formula.BProv_Ax_s_addZero_rename
#check @PA.Formula.BProv_Ax_s_addZero
#check @PA.Formula.BProv_Ax_s_addZero_term
#check @PA.Formula.BProv_Ax_s_addSucc_rename
#check @PA.Formula.BProv_Ax_s_addSucc
#check @PA.Formula.BProv_Ax_s_addSucc_terms
#check @PA.Formula.BProv_Ax_s_zero_add_all
#check @PA.Formula.BProv_Ax_s_zero_add_term
#check @PA.Formula.BProv_Ax_s_succ_add_all
#check @PA.Formula.BProv_Ax_s_succ_add_terms
#check @PA.Formula.BProv_Ax_s_succ_add_cancel_terms
#check @PA.Formula.BProv_Ax_s_add_cancel_left_all
#check @PA.Formula.BProv_Ax_s_add_cancel_left_terms
#check @PA.Formula.BProv_Ax_s_add_cancel_right_all
#check @PA.Formula.BProv_Ax_s_add_cancel_right_terms
#check @PA.Formula.BProv_Ax_s_add_assoc_all
#check @PA.Formula.BProv_Ax_s_add_assoc_terms
#check @PA.Formula.BProv_Ax_s_add_comm_all
#check @PA.Formula.BProv_Ax_s_add_comm_terms
#check @PA.Formula.BProv_Ax_s_add_succ_ne_self_all
#check @PA.Formula.BProv_Ax_s_add_succ_ne_self_terms
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPredAt_all
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPred_term
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPredAt
#check @PA.Formula.BProv_nonzeroAt_elim
#check @PA.Formula.BProv_nonzeroAt_of_succPredAt
#check @PA.Formula.term_substZero_rename_succ
#check @PA.Formula.term_substSuccVar_rename_succ
#check @PA.Formula.BProv_Ax_s_add_eq_zero_left_all
#check @PA.Formula.BProv_Ax_s_add_eq_zero_left_terms
#check @PA.Formula.BProv_Ax_s_add_eq_zero_right_terms
#check @PA.Formula.BProv_Ax_s_leConstAt_of_leAt_eqConst
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leConstAt_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_leConstAt_succ_cases
#check @PA.Formula.BProv_Ax_s_mulZero_rename
#check @PA.Formula.BProv_Ax_s_mulZero
#check @PA.Formula.BProv_Ax_s_mulZero_term
#check @PA.Formula.BProv_Ax_s_mulSucc_rename
#check @PA.Formula.BProv_Ax_s_mulSucc
#check @PA.Formula.BProv_Ax_s_mulSucc_terms
#check @PA.Formula.BProv_Ax_s_zero_mul_all
#check @PA.Formula.BProv_Ax_s_zero_mul_term
#check @PA.Formula.BProv_Ax_s_succ_mul_all
#check @PA.Formula.BProv_Ax_s_succ_mul_terms
#check @PA.Formula.BProv_Ax_s_mul_comm_all
#check @PA.Formula.BProv_Ax_s_mul_comm_terms
#check @PA.Formula.BProv_Ax_s_mul_add_all
#check @PA.Formula.BProv_Ax_s_mul_add_terms
#check @PA.Formula.BProv_Ax_s_add_mul_all
#check @PA.Formula.BProv_Ax_s_add_mul_terms
#check @PA.Formula.BProv_Ax_s_mul_assoc_all
#check @PA.Formula.BProv_Ax_s_mul_assoc_terms
#check @PA.Formula.BProv_Ax_s_mul_one_all
#check @PA.Formula.BProv_Ax_s_mul_one_term
#check @PA.Formula.BProv_Ax_s_one_mul_all
#check @PA.Formula.BProv_Ax_s_one_mul_term
#check @PA.Formula.BProv_Ax_s_addRightNumeral
#check @PA.Formula.BProv_Ax_s_mulRightNumeral
#check @PA.Formula.BProv_Ax_s_mul_two_right_terms
#check @PA.Formula.BProv_Ax_s_addNumerals
#check @PA.Formula.BProv_Ax_s_mulRightNumeral_numeral
#check @PA.Formula.BProv_Ax_s_mulNumerals
#check @PA.Formula.BProv_Ax_s_leAt_of_eq
#check @PA.Formula.BProv_Ax_s_leAt_of_eqConst_zero_left
#check @PA.Formula.BProv_Ax_s_leAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_leTermAt_numeral_of_eqConst
#check @PA.Formula.BProv_Ax_s_ltAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_leAt_of_ltAt
#check @PA.Formula.BProv_Ax_s_leAt_refl
#check @PA.Formula.BProv_Ax_s_leAt_trans
#check @PA.Formula.BProv_Ax_s_eq_of_leAt_leAt
#check @PA.Formula.BProv_Ax_s_ltAt_trans
#check @PA.Formula.BProv_Ax_s_ltAt_leAt_trans
#check @PA.Formula.BProv_Ax_s_leAt_ltAt_trans
#check @PA.Formula.BProv_Ax_s_ltAt_irrefl_bot
#check @PA.Formula.BProv_Ax_s_ltAt_leAt_bot
#check @PA.Formula.BProv_Ax_s_ltTermAt_leTermAt_bot
#check @PA.Formula.BProv_Ax_s_ltAt_asymm_bot
#check @PA.Formula.BProv_Ax_s_ltAt_eq_bot
#check @PA.Formula.BProv_Ax_s_ltAt_of_eqConst_zero_succPredAt
#check @PA.Formula.BProv_Ax_s_succPredAt_of_ltAt
#check @PA.Formula.BProv_leTermAt_of_eq_left
#check @PA.Formula.BProv_leTermAt_of_eq_right
#check @PA.Formula.BProv_ltTermAt_of_eq_left
#check @PA.Formula.BProv_ltTermAt_of_eq_right
#check @PA.Formula.BProv_Ax_s_leTermAt_refl
#check @PA.Formula.BProv_Ax_s_leTermAt_zero_left
#check @PA.Formula.BProv_Ax_s_ltTermAt_zero_succ
#check @PA.Formula.BProv_Ax_s_ltTermAt_self_succ
#check @PA.Formula.BProv_Ax_s_remTermTermAt_of_eq_add_mul_terms
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_rem
#check @PA.Formula.BProv_Ax_s_betaTermTermAtConstIdx_of_beta
#check @PA.Formula.BProv_Ax_s_leTermAt_succ_succ
#check @PA.Formula.BProv_Ax_s_eq_of_leTermAt_leTermAt
#check @PA.Formula.BProv_Ax_s_ltTermAt_succ_succ
#check @PA.Formula.BProv_Ax_s_ltTermAt_succ_right_of_leTermAt
#check @PA.Formula.BProv_Ax_s_leTermAt_of_ltTermAt_succ_right
#check @PA.Formula.BProv_Ax_s_leTermAt_or_gtTermAt_all
#check @PA.Formula.BProv_Ax_s_leTermAt_or_gtTermAt
#check @PA.Formula.BProv_Ax_s_ltTermAt_succ_right_cases
#check @PA.Formula.BProv_Ax_s_leAt_or_gtAt
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_ltAt_eqConst_one
#check @PA.Formula.BProv_Ax_s_ltConst_of_eqConst
#check @PA.Formula.BProv_Ax_s_ltConst_closed
#check @PA.Formula.BProv_Ax_s_dvdAt_of_eqConst_mul
#check @PA.Formula.BProv_Ax_s_dvdAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_dvdAt_of_eq_mul_term
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_dvdAt_ltAt
#check @PA.Formula.BProv_Ax_s_dvdAt_of_doubleEqAt_two
#check @PA.Formula.BProv_Ax_s_boolAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_div2StepAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_div2StepAt_zero_one_bot
#check @PA.Formula.BProv_Ax_s_div2StepAt_zero_half_zero
#check @PA.Formula.BProv_Ax_s_div2StepAt_double_one_bot
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_div2StepAt_double
#check @PA.Formula.BProv_Ax_s_doubleEqAt_of_eqConst_double
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_div2StepAt_eqConst_even
#check @PA.Formula.BProv_Ax_s_doubleEqAt_of_div2StepAt_bit_zero
#check @PA.Formula.BProv_Ax_s_oddDoubleEqAt_of_div2StepAt_bit_one
#check @PA.Formula.BProv_Ax_s_succ_oddDoubleEqAt_eq_double_succ
#check @PA.Formula.BProv_Ax_s_double_or_oddDoubleEqAt_of_div2StepAt
#check @PA.Formula.BProv_Ax_s_of_div2StepAt_double_odd_cases
#check @PA.Formula.BProv_Ax_s_of_two_div2StepAt_double_odd_cases
#check @PA.Formula.BProv_Ax_s_remAt_of_div2StepAt_two
#check @PA.Formula.BProv_Ax_s_div2StepAt_closedSubst
#check @PA.Formula.BProv_Ax_s_div2StepAt_constValueHalfSubst_of_eqConst
#check @PA.Formula.BProv_Ax_s_remAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_remAt_constMod_of_eqConst
#check @PA.Formula.BProv_Ax_s_remAt_constRemMod_of_eqConst
#check @PA.Formula.BProv_Ax_s_ltAt_of_remAt
#check @PA.Formula.BProv_Ax_s_remEqAt_of_remAt
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_dvdAt_remAt
#check @PA.Formula.ltTermAt
#check @PA.Formula.remTermAt
#check @PA.Formula.remTermTermAt
#check @PA.Formula.ltTermAt_var
#check @PA.Formula.leTermAt_var
#check @PA.Formula.remTermAt_var
#check @PA.Formula.remTermEqAt
#check @PA.Formula.betaTermAt
#check @PA.Formula.betaModTermTerm
#check @PA.Formula.betaTermTermAt
#check @PA.Formula.betaTermAt_var
#check @PA.Formula.betaTermAtTermIdx
#check @PA.Formula.betaTermAtConstIdx
#check @PA.Formula.betaTermTermAtConstIdx
#check @PA.Formula.boolTermAt
#check @PA.Formula.div2StepTermAt
#check @PA.Formula.boolTermAt_var
#check @PA.Formula.div2StepTermAt_var
#check @PA.Formula.betaDiv2StepWitnessTermAt
#check @PA.Formula.betaDiv2StepsThroughTermTermAt
#check @PA.Formula.betaTermAtConstIdx_var
#check @PA.Formula.BProv_Ax_s_betaModTermTerm_zero
#check @PA.Formula.BProv_Ax_s_betaModTermTerm_one_mul_two
#check @PA.Formula.BProv_Ax_s_betaModTermTerm_one_add_self
#check @PA.Formula.hfMemZeroSetAt
#check @PA.Formula.hfMemTermAt
#check @PA.Formula.hfMemTermAt_var
#check @PA.Formula.hfMemTermAt_zero
#check @PA.Formula.rename_hfMemTermAt_succ
#check @PA.Formula.subst_instTerm_hfMemAt_succ_zero
#check @PA.Formula.subst_up_zero_hfMemAt_zero_set
#check @PA.Formula.BProv_Ax_s_ltTermAt_of_remTermAt
#check @PA.Formula.BProv_Ax_s_remTermEqAt_of_remTermAt
#check @PA.Formula.BProv_Ax_s_eq_zero_of_remTermAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_eq_of_same_quotient_remainder_terms
#check @PA.Formula.BProv_Ax_s_leTermAt_of_eq_add_right_terms
#check @PA.Formula.BProv_Ax_s_leAt_half_of_doubleEqAt
#check @PA.Formula.BProv_Ax_s_leAt_half_of_oddDoubleEqAt
#check @PA.Formula.BProv_Ax_s_ltAt_half_of_doubleEqAt_ltAt
#check @PA.Formula.BProv_Ax_s_ltAt_half_of_oddDoubleEqAt_ltAt
#check @PA.Formula.BProv_Ax_s_leAt_half_of_div2StepAt
#check @PA.Formula.BProv_Ax_s_ltAt_half_of_div2StepAt_ltAt
#check @PA.Formula.BProv_Ax_s_leTermAt_modulus_of_eq_mul_succ_add
#check @PA.Formula.BProv_Ax_s_remainder_difference_of_le_quotient_terms
#check @PA.Formula.BProv_Ax_s_eq_zero_of_bounded_remainder_difference_terms
#check @PA.Formula.BProv_Ax_s_eq_highRem_of_bounded_remainder_difference_terms
#check @PA.Formula.BProv_Ax_s_eq_of_bounded_remainder_decompositions_terms
#check @PA.Formula.BProv_Ax_s_eq_of_bounded_remainder_decomposition_quotients_terms
#check @PA.Formula.BProv_doubleEqAt_of_eq_value
#check @PA.Formula.BProv_oddDoubleEqAt_of_eq_value
#check @PA.Formula.BProv_Ax_s_ltTermAt_two_of_boolAt
#check @PA.Formula.BProv_Ax_s_eq_of_doubleEqAt_div2StepAt
#check @PA.Formula.BProv_Ax_s_eq_of_oddDoubleEqAt_div2StepAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_of_doubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_of_oddDoubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_of_current_doubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_of_current_oddDoubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_next_termIdx_of_current_doubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_next_termIdx_of_current_oddDoubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_next_termIdx_of_current_div2StepAt
#check @PA.Formula.BProv_Ax_s_eqConstAt_mod_two_of_div2StepAt_eqConst
#check @PA.Formula.BProv_Ax_s_eqConstAt_div_two_of_div2StepAt_eqConst
#check @PA.Formula.BProv_Ax_s_eqConstAt_of_remAt_eqConst
#check @PA.Formula.BProv_Ax_s_eq_of_remAt_remTermAt_eq_modulus
#check @PA.Formula.BProv_Ax_s_eq_of_remAt_remTermAt_same_modulus
#check @PA.Formula.BProv_Ax_s_eq_of_remTermAt_remTermAt_eq_modulus
#check @PA.Formula.BProv_Ax_s_eq_of_remTermAt_remTermAt_same_modulus
#check @PA.Formula.BProv_Ax_s_mul_succ_right_eq_succ_terms
#check @PA.Formula.BProv_Ax_s_add_successor_summand_ne_self_terms
#check @PA.Formula.BProv_Ax_s_remainder_eq_mul_of_le_quotient_terms
#check @PA.Formula.BProv_Ax_s_remainder_gt_quotient_bot_terms
#check @PA.Formula.BProv_Ax_s_remainder_zero_of_le_quotient_terms
#check @PA.Formula.BProv_Ax_s_remainder_zero_of_gt_quotient_terms
#check @PA.Formula.BProv_Ax_s_remainder_zero_of_le_quotient_at
#check @PA.Formula.BProv_Ax_s_remainder_zero_of_gt_quotient_at
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_dvdAt_value_remAt
#check @PA.Formula.BProv_Ax_s_dvdAt_of_eq_left
#check @PA.Formula.BProv_Ax_s_dvdAt_of_eq_right
#check @PA.Formula.BProv_Ax_s_dvdAt_of_remTermAt_zero
#check @PA.Formula.BProv_Ax_s_remTermAt_of_remAt_eq_term
#check @PA.Formula.BProv_Ax_s_remAt_of_remTermAt_eq_term
#check @PA.Formula.BProv_Ax_s_remTermAt_zero_of_remAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_dvdAt_of_remAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_output_zero_of_output_dvd
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_output_zero_of_code_dvd
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_code_dvd_of_output_zero
#check @PA.Formula.BProv_Ax_s_betaAt_output_zero_of_betaAt_output_zero_same_index
#check @PA.Formula.BProv_Ax_s_betaAt_output_zero_of_betaTermAt_zero_same_index
#check @PA.Formula.BProv_Ax_s_betaAt_output_zero_of_betaTermAt_zero_eq_index
#check @PA.Formula.BProv_Ax_s_betaTermAt_zero_of_betaAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_betaAt_output_zero_of_betaTermAtConstIdx_zero_eqConst_index
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_remAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_remAt_eqConst_modulus_one
#check @PA.Formula.BProv_Ax_s_remAt_eqConst_modulus_zero_bot
#check @PA.Formula.BProv_Ax_s_betaModTerm_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaModTerm_congr
#check @PA.Formula.BProv_Ax_s_betaModTerm_eq_one_of_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_betaModTerm_idx_zero_of_step_succ
#check @PA.Formula.BProv_Ax_s_eq_succ_eq_zero_bot
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_one_bot
#check @PA.Formula.BProv_Ax_s_div2StepAt_dvd_two_one_bot
#check @PA.Formula.BProv_Ax_s_div2StepAt_even_one_bot
#check @PA.Formula.BProv_Ax_s_betaModTerm_idx_zero_step_succ_ne_zero_bot
#check @PA.Formula.BProv_Ax_s_betaModTerm_modEq_zero_bot
#check @PA.Formula.BProv_Ax_s_succPredAt_of_eq_succ_term
#check @PA.Formula.BProv_Ax_s_betaModTerm_modEq_succPredAt
#check @PA.Formula.BProv_Ax_s_ltAt_zero_of_betaModTerm_modEq
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_modulus_zero_bot
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_modulus_succPredAt
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_zero_lt_modulus
#check @PA.Formula.BProv_Ax_s_betaTermAt_opened_body_modulus_zero_bot
#check @PA.Formula.BProv_Ax_s_betaTermAt_opened_body_modulus_succPredAt
#check @PA.Formula.BProv_Ax_s_betaTermAt_opened_body_zero_lt_modulus
#check @PA.Formula.BProv_Ax_s_betaAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_modEq
#check @PA.Formula.BProv_Ax_s_betaAt_opened_body_rem
#check @PA.Formula.BProv_Ax_s_eqConstAt_of_betaAt_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaTermAt_opened_body_modEq
#check @PA.Formula.BProv_Ax_s_betaTermAt_opened_body_rem
#check @PA.Formula.BProv_Ax_s_eq_of_betaAt_betaTermAt_same_index
#check @PA.Formula.BProv_Ax_s_eq_of_betaTermAt_betaTermAt_same_index
#check @PA.Formula.BProv_Ax_s_betaTermAt_of_betaAt_eq_term
#check @PA.Formula.BProv_Ax_s_betaAt_of_betaTermAt_eq_term
#check PA.Formula.betaTermAt_eq_betaTermTermAt_var
#check @PA.Formula.BProv_Ax_s_betaTermAt_zero_opened_body_dvd
#check @PA.Formula.BProv_Ax_s_betaAtConstIdx_opened_body_idx
#check @PA.Formula.BProv_Ax_s_betaAtConstIdx_opened_body_beta
#check @PA.Formula.BProv_Ax_s_betaTermAtConstIdx_opened_body_idx
#check @PA.Formula.BProv_Ax_s_betaTermAtConstIdx_opened_body_beta
#check @PA.Formula.BProv_Ax_s_betaTermAtConstIdx_of_betaAtConstIdx_eq_term
#check @PA.Formula.BProv_Ax_s_betaTermAt_of_eq_index
#check @PA.Formula.betaTermTermAtSuccIdx
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_eq_index
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_betaTermTermAtConstIdx_eq_term
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_betaTermTermAtConstIdx_eq_index
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_succ_of_betaTermTermAtConstIdx_eq_index
#check @PA.Formula.BProv_Ax_s_betaTermTermAtSuccIdx_of_succ
#check @PA.Formula.BProv_Ax_s_betaTermTermAtSuccIdx_of_betaTermTermAtConstIdx_eq_index
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessTermAt_of_components
#check @PA.Formula.BProv_Ax_s_betaTermAtTermIdx_opened_body_idx
#check @PA.Formula.BProv_Ax_s_betaTermAtTermIdx_opened_body_beta
#check @PA.Formula.BProv_Ax_s_betaTermAtTermIdx_of_eq_beta
#check @PA.Formula.BProv_Ax_s_betaTermAt_of_betaTermAtTermIdx_eq_index
#check @PA.Formula.BProv_Ax_s_betaAt_of_betaTermAtTermIdx_eq_output_index
#check @PA.Formula.BProv_Ax_s_betaTermAtTermIdx_of_betaTermAtConstIdx
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_betaTermAtTermIdx
#check @PA.Formula.BProv_Ax_s_betaAt_of_betaTermAtConstIdx_eq_output_index
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_of_betaTermAtConstIdx_eq_output_index
#check @PA.Formula.BProv_Ax_s_betaAt_output_zero_of_betaTermAtTermIdx_eq_index
#check @PA.Formula.BProv_Ax_s_eq_of_betaAt_betaTermAtTermIdx_eq_index
#check @PA.Formula.BProv_Ax_s_eqConstAt_of_betaAt_betaTermAtTermIdx_eq_index
#check @PA.Formula.BProv_Ax_s_eq_of_betaTermAtTermIdx_betaTermAtTermIdx_eq_index
#check @PA.Formula.BProv_Ax_s_eq_of_betaTermAtTermIdx_betaTermAtTermIdx_same_index
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_opened_body_idx
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_opened_body_beta
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAt_eqConst_code_zero
#check @PA.Formula.BProv_Ax_s_eq_zero_of_betaTermAt_eqConst_code_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAt_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_eq_zero_of_betaTermAt_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAtConstIdx_eqConst_code_zero
#check @PA.Formula.BProv_Ax_s_eq_zero_of_betaTermAtConstIdx_eqConst_code_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAtSuccIdx_eqConst_code_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAtConstIdx_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_eq_zero_of_betaTermAtConstIdx_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_betaAtSuccIdx_eqConst_step_zero
#check @PA.Formula.BProv_Ax_s_betaAt_constOutSubst_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaModTerm_constIdx_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAt_constOutIdxSubst_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAt_constIdxSubst_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAtConstIdx_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_constOutSubst_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_betaAt_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaAt_constOutSubst_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaAt_constOutIdxSubst_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaAtConstIdx_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaAtSuccIdx_constOutSubst_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_of_eqConst_step
#check @PA.Formula.betaDiv2StepWitnessAtTermIdx
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_zero_next_zero
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_current_zero_of_betaTermAt_zero_eq_index
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_zero_of_betaTermAt_zero_eq_index
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_zero
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_of_next_eq
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_next_termIdx_eqConst_div_two
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_next_termIdx_zero
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_next_termIdx_eqConst_div_two
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_opened_body_idx
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_opened_body_witness
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_next_termIdx_eqConst_div_two
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_next_termIdx_of_current_doubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_next_termIdx_of_current_oddDoubleEqAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_next_termIdx_of_current_div2StepAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_step_termIdx_of_leTerm
#check @PA.Formula.betaDiv2StepsThroughTermAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermAt_step_termIdx_of_leTerm
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermAt_step_succ_termIdx_of_leTerm
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_next_termIdx_eqConst_div_two_of_leTerm
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_termIdx_eqConst_div2Iter_of_le
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_step_of_le
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_step_of_eqConst_zero
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_termIdx_zero_of_le
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_of_eqConst_step
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_zero_one_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_double_one_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_current_zero_of_betaTermAt_zero_eq_index
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_bot_of_opened_final_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_current_zero_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_current_double_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_current_bit_zero_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_bit_zero_of_current_eqConst_even
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_bit_zero_of_current_termIdx_even
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_current_eqConst_even_bot
#check @PA.Formula.BProv_Ax_s_betaDiv2BitAt_step_zero_bot
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_final_current_eqConst_div2Iter
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_final_current_eq_set_of_elem_zero
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_eqConst_zero_elem_dvd_set
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_eqConst_not_mem
#check @PA.Formula.BProv_exists_eqConstAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_zero_of_eqConst_step
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_zero_of_eqConst_step
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_succ_of_eqConst_step
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_of_const_eqConst
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_of_eqConst_trace
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_of_eqConst_trace
#check @PA.Formula.BProv_Ax_s_hfMemAt_bitOneEx_of_bit
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_bitOneEx_of_bit
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_closed_components
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_closed_bit_components
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_of_components
#check @PA.Formula.BProv_Ax_s_subst_hfMemTermAt_of_components
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_of_bit_components
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_of_closed_components
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_of_closed_bit_components
#check @PA.Formula.BProv_Ax_s_hfMemAt_entryComponent_of_eqConst_entry
#check @PA.Formula.BProv_Ax_s_hfMemAt_bitComponent_of_eqConst_bit
#check @PA.Formula.BProv_Ax_s_hfMemAt_stepsComponent_of_eqConst_trace
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_trace_with_steps
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_trace
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_zero_odd_double
#check @PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_mem
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemAt_succ_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemAt_succ_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemAt_succ_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_succ_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_succ_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_succ_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_bot
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_current_zero
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_current_double
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_bit_zero
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_current_eqConst_even
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_step_zero
#check @PA.Formula.BProv_Ax_s_hfMemAt_opened_body_step_zero_bot
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_step_successor
#check @PA.Formula.BProv_Ax_s_hfMemAt_succ_opened_pred_bot
#check @PA.Formula.BProv_Ax_s_hfMemAt_pred_opened_step_succ
#check @PA.Formula.BProv_Ax_s_hfMemAt_pred_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemAt_pred_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemAt_pred_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemAt_pred_opened_as_hfMemTermAt
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_pred_opened_step_succ
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_pred_opened_body_entry
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_pred_opened_body_steps
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_pred_opened_body_bitEx
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_bot_of_opened_final_current_zero
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_opened_body_step_zero_bot
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_bot_of_opened_step_successor
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_succ_opened_pred_bot
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_bot_of_opened_step_pred
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_opened_final_current_zero
#check @PA.Formula.BProv_Ax_s_hfMemZeroSetAt_bot
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_step_pred
#check @PA.Formula.BProv_Ax_s_hfMemAt_elim_opened_step_pred
#check @PA.Formula.subst_instTerm_var_hfMemAt_succ_zero
#check @PA.Formula.subst_instTerm_zero_hfMemAt_succ_zero
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_eqConst_zero
#check @PA.Formula.BProv_Ax_s_HF_empty_zero_body_of_member_bot
#check @PA.Formula.BProv_Ax_s_translated_HF_empty_of_zero_body
#check @PA.Formula.BProv_Ax_s_translated_HF_empty_of_zero_member_bot
#check @PA.Formula.subst_instTerm_var_hfMemAt_zero_succ
#check @PA.Formula.subst_instTerm_var_hfMemAt_iff
#check @PA.Formula.BProv_hfMemAt_iff_of_all
#check @PA.Formula.BProv_hfMemAt_forward_of_all
#check @PA.Formula.BProv_hfMemAt_reverse_of_all
#check @PA.Formula.BProv_Ax_s_HF_extensionality_fresh_member_forward
#check @PA.Formula.BProv_Ax_s_HF_extensionality_fresh_member_reverse
#check PA.Formula.hfDistinguishesAt
#check PA.Formula.hfDistinguishesTermAt
#check PA.Formula.hfSomeDistinguishesAt
#check PA.Formula.hfSomeDistinguishesTermAt
#check PA.Formula.hfLtDistinguishesAt
#check PA.Formula.hfLtDistinguishesTermAt
#check @PA.Formula.hfDistinguishesTermAt_var
#check @PA.Formula.hfSomeDistinguishesTermAt_var
#check @PA.Formula.hfLtDistinguishesTermAt_var
#check @PA.Formula.rename_hfDistinguishesAt
#check @PA.Formula.rename_hfSomeDistinguishesAt_succ
#check @PA.Formula.rename_hfSomeDistinguishesTermAt_succ
#check @PA.Formula.rename_hfLtDistinguishesTermAt_succ
#check @PA.Formula.rename_hfLtDistinguishesAt_succ
#check @PA.Formula.subst_instTerm_var_hfLtDistinguishesAt_body
#check @PA.Formula.subst_instTerm_var_hfLtDistinguishesTermAt_body
#check @PA.Formula.subst_instTerm_var_hfLtDistinguishesAt_zero
#check @PA.Formula.subst_instTerm_hfLtDistinguishesAt_zero_term
#check PA.Formula.substSuccVar_hfLtDistinguishesAt_zero
#check @PA.Formula.subst_instTerm_var_hfMemTermAt_zero_rename_succ
#check @PA.Formula.BProv_hfMemTermAt_of_hfMemAt_eq_term
#check @PA.Formula.BProv_hfMemTermAt_of_hfMemTermAt_eq_term
#check @PA.Formula.BProv_hfSomeDistinguishesAt_of_hfLtDistinguishesAt
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_hfLtDistinguishesTermAt
#check @PA.Formula.BProv_hfSomeDistinguishesAt_of_all_hfLtDistinguishesAt
#check @PA.Formula.hfDistinguishesAt_nat
#check @PA.Formula.hfSomeDistinguishesAt_nat
#check @PA.Formula.hfSomeDistinguishesAt_nat_of_lt
#check @PA.Formula.hfSomeDistinguishesAt_nat_or_of_ne
#check @PA.Formula.subst_instTerm_var_hfDistinguishesAt_zero_succ
#check @PA.Formula.subst_instTerm_var_hfDistinguishesTermAt_zero_succ
#check @PA.Formula.BProv_hfSomeDistinguishesAt_intro_var
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_intro_var
#check @PA.Formula.BProv_hfSomeDistinguishesAt_elim
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_elim
#check @PA.Formula.BProv_hfDistinguishesAt_of_mem_and_not_mem
#check @PA.Formula.BProv_hfSomeDistinguishesAt_of_mem_and_not_mem
#check @PA.Formula.BProv_hfDistinguishesAt_of_mem_and_low_mem_bot
#check @PA.Formula.BProv_hfSomeDistinguishesAt_of_mem_and_low_mem_bot
#check @PA.Formula.BProv_hfDistinguishesTermAt_of_mem_and_not_mem
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_mem_and_not_mem
#check @PA.Formula.BProv_hfDistinguishesTermAt_of_high_eq_term
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_high_eq_term
#check @PA.Formula.BProv_hfLtDistinguishesTermAt_of_high_eq_term
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_of_high_odd_double_succ
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_of_high_odd_double_succ
#check @PA.Formula.BProv_hfDistinguishesTermAt_of_hfDistinguishesAt_eq_term
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_hfDistinguishesAt_eq_term
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_hfSomeDistinguishesAt_eq_term
#check @PA.Formula.BProv_hfMemAt_bot_imp_of_low_eq
#check @PA.Formula.BProv_hfDistinguishesTermAt_of_low_eq
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_low_eq
#check @PA.Formula.BProv_hfDistinguishesTermAt_of_mem_and_low_mem_bot
#check @PA.Formula.BProv_hfSomeDistinguishesTermAt_of_mem_and_low_mem_bot
#check @PA.Formula.BProv_Ax_s_hfDistinguishesTermAt_of_zero_mem_and_low_dvd
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_of_zero_mem_and_low_dvd
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_of_zero_mem_and_low_double
#check @PA.Formula.BProv_Ax_s_hfDistinguishesAt_of_mem_and_eqConst_zero_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_mem_and_eqConst_zero_low
#check @PA.Formula.BProv_Ax_s_hfDistinguishesAt_of_eqConst_zero_odd_high_dvd_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_zero_odd_high_dvd_low
#check @PA.Formula.BProv_Ax_s_hfDistinguishesAt_of_eqConst_zero_odd_high_double_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_zero_odd_high_double_low
#check @PA.Formula.BProv_Ax_s_hfDistinguishesAt_of_eqConst_mem_not_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_mem_not_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_mem_not_mem_closed_witness
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_lt
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_ltAt
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_high_leConst_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_high_ltAt
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesAt_of_eqConst_high
#check PA.Formula.BProv_Ax_s_hfLtDistinguishesAt_zero_base
#check @PA.Formula.BProv_Ax_s_hfDistinguishesAt_of_eqConst_mem_zero_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_eqConst_mem_zero_low
#check @PA.Formula.BProv_Ax_s_HF_extensionality_lt10_bot_of_distinguishing
#check @PA.Formula.BProv_Ax_s_HF_extensionality_lt01_bot_of_distinguishing
#check @PA.Formula.BProv_Ax_s_HF_extensionality_member_ext_of_lt_bots
#check @PA.Formula.BProv_Ax_s_HF_extensionality_body_of_member_ext
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_body
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_member_ext
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_lt_bots
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_distinguishing
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_lt_distinguishes
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_all_hfLtDistinguishesAt
#check @PA.Formula.BProv_Ax_s_all_hfLtDistinguishesAt_of_successor_step
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_strict_ih
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_hfLtDistinguishesTermAt_div2_half
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_strict_ih_low_div2_half
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_eq_case_of_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_strict_and_self
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_successor_step
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_successor_cases
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_strict_and_self
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_div2_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_and_self
#check @PA.Formula.BProv_Ax_s_translated_HF_extensionality_of_div2_step_pred_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_and_self
#check @PA.Formula.BProv_Ax_s_HF_empty_zero_member_bot
#check @PA.Formula.BProv_Ax_s_translated_HF_empty
#check @PA.Formula.BProv_Ax_s_betaTermAtConstIdx_zero_opened_raw_body_dvd
#check @PA.Formula.BProv_Ax_s_leTermAt_trans
#check @PA.Formula.BProv_Ax_s_leTermAt_self_succ
#check @PA.Formula.BProv_Ax_s_leTermAt_pred_of_succ_le
#check @PA.Formula.BProv_Ax_s_leAt_pred_of_succ_eq_le
#check @PA.Formula.BProv_Ax_s_inductionForm_rename
#check @PA.Formula.BProv_Ax_s_inductionForm
#check @PA.Formula.BProv_Ax_s_induction_rule
#check @PA.Formula.leAt
#check @PA.Formula.leTermAt
#check @PA.Formula.leConstAt
#check @PA.Formula.ltAt
#check @PA.Formula.dvdAt
#check @PA.Formula.eqConstAt
#check @PA.Formula.zeroAt
#check @PA.Formula.oneAt
#check @PA.Formula.twoAt
#check @PA.Formula.nonzeroAt
#check @PA.Formula.succPredAt
#check @PA.Formula.zeroOrSuccPredAt
#check @PA.Formula.boolAt
#check @PA.Formula.doubleEqAt
#check @PA.Formula.oddDoubleEqAt
#check @PA.Formula.div2StepAt
#check @PA.Formula.remAt
#check @PA.Formula.betaModTerm
#check @PA.Formula.betaAt
#check @PA.Formula.betaAtConstIdx
#check @PA.Formula.betaAtSuccIdx
#check @PA.Formula.BetaModulus
#check @PA.Formula.BetaEntry
#check @PA.Formula.twoEntryBetaStep
#check @PA.Formula.twoEntryBetaCode
#check @PA.Formula.BetaEntry_twoEntry_zero
#check @PA.Formula.BetaEntry_twoEntry_one
#check @PA.Formula.BetaDiv2Step_twoEntry
#check @PA.Formula.BetaDiv2StepsThrough_zero_twoEntry
#check @PA.Formula.HFMemTrace_zero_exists_of_one_step
#check @PA.Formula.HFMemTrace_succ_of_double_mem_succ
#check @PA.Formula.evenSuccBetaStepTerm
#check @PA.Formula.evenSuccBetaCodeTerm
#check @PA.Formula.oddCurrentBetaStepTerm
#check @PA.Formula.oddCurrentBetaCodeTerm
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_entryComponent_zero
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_entryComponent_zero
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_index_one_bound
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_index_one_bound
#check @PA.Formula.BProv_Ax_s_oddCurrent_beta_code_decomp
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_index_one_value
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_index_one_value
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_entryComponent_one
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_entryComponent_one
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_div2Step_one
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_div2Step_one
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_bitComponent_zero
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_bitComponent_zero
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_stepWitness_zero
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_stepWitness_zero
#check @PA.Formula.BProv_Ax_s_evenSuccBeta_stepsComponent_zero
#check @PA.Formula.BProv_Ax_s_oddCurrentBeta_stepsComponent_zero
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_oddCurrentBeta_of_zero_and_odd
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_evenSucc_of_zero_and_low_double
#check @PA.Formula.BProv_Ax_s_hfMemAt_bot_of_eqConst_zero_elem_low_double
#check @PA.Formula.BProv_Ax_s_nonzeroAt_of_hfMemAt_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_elim_high_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_elim_high_double_pred
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_succ_of_high_double_opened_high_mem
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_succ_of_high_double_opened_step_pred
#check @PA.Formula.BProv_Ax_s_hfMemTermAt_succ_opened_step_pred_of_components
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_high_double_opened_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_high_double_opened_mem_with_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_double_low_odd_of_opened_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_double_low_odd_of_opened_high_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_double_low_odd_of_opened_step_pred
#check PA.Formula.strictHighDoubleLowOddSuccComponentContext
#check PA.Formula.strictHighDoubleLowOddSuccTargetCode
#check PA.Formula.strictHighDoubleLowOddSuccEntryFormula
#check PA.Formula.strictHighDoubleLowOddSuccStepsFormula
#check PA.Formula.strictHighDoubleLowOddSuccBitExFormula
#check PA.Formula.strictHighOddLowDoubleSuccCarryContext
#check PA.Formula.strictHighOddLowOddSuccCarryContext
#check PA.Formula.strictHighOddSuccHalfCode
#check PA.Formula.strictHighOddSuccCarryTargetFormula
#check PA.Formula.strictHighOddLowDoubleOpenedIHContext
#check PA.Formula.strictHighOddLowOddOpenedIHContext
#check PA.Formula.strictHighOddOpenedIHTargetFormula
#check PA.Formula.strictHighOddSuccWitnessTerm
#check PA.Formula.strictHighOddOpenedWitnessSuccHighCode
#check PA.Formula.strictHighOddOpenedWitnessSuccMemFormula
#check PA.Formula.strictHighOddOpenedWitnessSuccMemEntryFormula
#check PA.Formula.strictHighOddOpenedWitnessSuccMemStepsFormula
#check PA.Formula.strictHighOddOpenedWitnessSuccMemBitExFormula
#check PA.Formula.strictHighOddOpenedWitnessSuccLowMemFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemEntryFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemStepsFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemBitExFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemOpenedFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemOpenedEntryFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemOpenedStepsFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemOpenedBitExFormula
#check PA.Formula.strictHighOddOpenedWitnessSuccLowMemStepEx
#check PA.Formula.strictHighOddOpenedWitnessSuccLowMemStepBody
#check PA.Formula.strictHighOddOpenedWitnessSuccLowMemOpenedCodeStepContext
#check PA.Formula.strictHighOddOpenedWitnessSuccBodyFormula
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_double_low_odd_of_components
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_double_low_odd_of_named_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_opened_ih
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_opened_ih
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccBody_of_mem_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccMem_of_components
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_elim_opened_code_step
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_assumption_elim_opened_code_step
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_low_half_mem_of_opened_code_step
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_bot_of_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_bot_of_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_of_components
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_of_components
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_entry_of_betaTermTermAt_zero
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_entry_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_entry_of_shift_tail_of_zero_le
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_entry_of_shift_tail_succ_bound
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_low_half_entry_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_low_half_entry_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_low_half_entry_of_shift_tail_succ_bound
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_low_half_entry_of_shift_tail_succ_bound
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_bot_of_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_bot_of_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_bot_of_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_bot_of_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_bot_of_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_bot_of_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_bot_of_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_bot_of_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_bot_of_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_bot_of_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedIHTarget_of_succ_witness_body
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedIHTarget_of_succ_witness_mem_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_body
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_entry
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_entry_termIdx
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_trace_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_steps
#check @PA.Formula.strictHighOddOpenedWitnessSuccLowMemOpenedStepsTermFormula
#check PA.Formula.betaShiftTailThroughTermAt
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_betaAt_eq_index
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_of_subst_betaAt
#check @PA.Formula.BProv_Ax_s_subst_betaAt_of_betaTermTermAt
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_succ_of_subst_betaAtSuccIdx
#check @PA.Formula.BProv_Ax_s_subst_betaAtSuccIdx_of_betaTermTermAt_succ
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_succ_of_betaTermTermAtSuccIdx_eq_term
#check @PA.Formula.BProv_Ax_s_betaTermTermAt_succ_of_betaAtSuccIdx_eq_index
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_to_termAt_of_idxEq
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAtTermIdx_to_termAt
#check PA.Formula.betaDiv2BitTermAt
#check PA.Formula.betaDiv2BitOneTermExAt
#check PA.Formula.strictHighOddOpenedWitnessSuccLowMemOpenedBitTermExFormula
#check PA.Formula.strictHighOddOpenedWitnessLowHalfMemOpenedBitTermExFormula
#check @PA.Formula.BProv_Ax_s_betaDiv2BitTermAt_of_components
#check @PA.Formula.BProv_Ax_s_betaDiv2BitTermAt_of_subst_betaDiv2BitAt
#check @PA.Formula.BProv_Ax_s_subst_betaDiv2BitAt_of_betaDiv2BitTermAt
#check @PA.Formula.BProv_Ax_s_betaDiv2BitOneTermExAt_of_subst_bitOneEx
#check @PA.Formula.BProv_Ax_s_subst_bitOneEx_of_betaDiv2BitOneTermExAt
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_entry_of_leTerm
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_steps_term
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_step_termIdx_of_leTerm
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_step_succ_termIdx_of_leTerm
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermTermAt_step_of_leTerm
#check @PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermTermAt_step_succ_of_leTerm
#check @PA.Formula.betaDiv2StepWitnessTermSuccIdxAt
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessTermSuccIdxAt_of_components
#check @PA.Formula.BProv_Ax_s_betaDiv2StepWitnessTermSuccIdxAt_of_termAt
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_stepWitness_of_components
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_stepWitness_of_oldWitness
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_bitTerm_of_oldBit
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_bitOneEx_of_oldBitOneEx
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_stepWitness_of_oldSteps
#check @PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_stepsThrough_of_oldSteps
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_steps_of_term_trace
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_steps_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_bitTermEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_bitEx_of_bitTermEx
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessLowHalfMem_opened_bitEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_low_half_steps_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_low_half_steps_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_low_half_bitTermEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_low_half_bitTermEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_low_half_bitEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_low_half_bitEx_of_shift_tail
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_bitEx
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_bitTermEx
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_step_zero
#check @PA.Formula.BProv_Ax_s_strictHighOddOpenedWitnessSuccLowMem_opened_code_step_step_zero_termIdx
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleOpenedWitnessSuccLowMem_opened_code_step_low_half_entry_termIdx
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddOpenedWitnessSuccLowMem_opened_code_step_low_half_entry_termIdx
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_mem_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_mem_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_low_bot
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half_bitEx
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half_bitEx
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_shift_tail_opened_low_half
#check @PA.Formula.BProv_Ax_s_strictHighOddLowDoubleSuccCarry_of_succ_witness_components_and_low_half_components
#check @PA.Formula.BProv_Ax_s_strictHighOddLowOddSuccCarry_of_succ_witness_components_and_low_half_components
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_opened_ih_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_low_half_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_opened_low_half_mem
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_opened_low_half_components
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_bitEx
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_shift_tail_opened_low_half
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_step_pred_succ_witness_components_carry_cases_shift_tail_opened_low_half
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_succ_witness_components_carry_cases_low_half_components
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_remaining_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_high_odd_of_double_succ
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_double_succ_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_high_mem_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_high_mem_double_succ_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_step_pred_double_succ_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_components_double_succ_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_components_double_succ_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_strict_of_div2_steps_and_named_carry_cases
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_components_double_succ_carry_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_components_double_succ_carry_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_carry_cases_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_opened_ih_carry_cases_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_carry_cases_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_opened_low_half_mem_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_opened_low_half_components_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_bitEx_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_step_pred_named_succ_witness_components_carry_cases_shift_tail_opened_low_half_and_self
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_div2_named_succ_witness_components_carry_cases_low_half_components_and_self
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_strict_ih_low_div2_half_in_high_odd_low_double_context
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesAt_of_strict_ih_low_div2_half_in_high_odd_low_odd_context
#check @PA.Formula.BProv_Ax_s_hfDistinguishesTermAt_of_zero_mem_and_low_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_low_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_self_of_div2_bit_zero
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_self_of_div2_step_and_odd_case
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_high_low_double
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_div2_bits_zero_zero
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_div2_steps_and_carry_cases
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_eqConst_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_leConst_low
#check @PA.Formula.BProv_Ax_s_hfSomeDistinguishesTermAt_succ_of_eqConst_high_ltAt
#check @PA.Formula.BProv_Ax_s_hfLtDistinguishesTermAt_succ_of_eqConst_high
#check @PA.Formula.betaFact
#check @PA.Formula.BetaModuliProduct
#check @PA.Formula.BetaDiv2Step
#check @PA.Formula.BetaDiv2StepsThrough
#check @PA.Formula.BetaDiv2Bit
#check @PA.Formula.HFMemTrace
#check @PA.Formula.betaDiv2StepWitnessAt
#check @PA.Formula.betaDiv2StepAt
#check @PA.Formula.betaDiv2StepsThroughAt
#check @PA.Formula.betaDiv2StepsThroughConstAt
#check @PA.Formula.betaDiv2BitAt
#check @PA.Formula.hfMemAt
#check @PA.Formula.leAt_nat
#check @PA.Formula.ltAt_nat
#check @PA.Formula.dvdAt_nat
#check @PA.Formula.eqConstAt_nat
#check @PA.Formula.zeroAt_nat
#check @PA.Formula.oneAt_nat
#check @PA.Formula.twoAt_nat
#check @PA.Formula.nonzeroAt_nat
#check @PA.Formula.boolAt_nat
#check @PA.Formula.doubleEqAt_nat
#check @PA.Formula.oddDoubleEqAt_nat
#check @PA.Formula.div2StepAt_nat
#check @PA.Formula.betaModTerm_nat
#check @PA.Formula.remAt_nat
#check @PA.Formula.betaAt_nat
#check @PA.Formula.betaAtConstIdx_nat
#check @PA.Formula.betaAtSuccIdx_nat
#check @PA.Formula.betaAt_nat_entry
#check @PA.Formula.betaAtConstIdx_nat_entry
#check @PA.Formula.betaAtSuccIdx_nat_entry
#check @PA.Formula.betaDiv2StepWitnessAt_nat
#check @PA.Formula.betaDiv2StepAt_nat
#check @PA.Formula.betaDiv2StepsThroughAt_nat
#check @PA.Formula.betaDiv2StepsThroughConstAt_nat
#check @PA.Formula.betaDiv2BitAt_nat
#check @PA.Formula.hfMemAt_nat_trace
#check @PA.Formula.betaFact_pos
#check @PA.Formula.BetaModuliProduct_pos
#check @PA.Formula.dvd_betaFact_of_pos_le
#check @PA.Formula.BetaModulus_pos
#check @PA.Formula.BetaModulus_coprime_step
#check @PA.Formula.BetaModulus_sub
#check @PA.Formula.BetaModulus_pair_coprime_of_dvd_step
#check @PA.Formula.BetaModulus_pair_coprime_of_lt_le
#check @PA.Formula.BetaModuliProduct_coprime_modulus_of_le
#check @PA.Formula.BetaModuliProduct_coprime_next_of_le
#check @PA.Formula.int_bezout_gcd
#check @PA.Formula.coprime_int_bezout
#check @PA.Formula.int_nonneg_shift
#check @PA.Formula.int_crt_shape_left
#check @PA.Formula.int_crt_shape_right
#check @PA.Formula.crt_two_mod
#check @PA.Formula.BetaEntry_value_lt
#check @PA.Formula.BetaEntry_mod_eq
#check @PA.Formula.BetaEntry_of_mod_eq
#check @PA.Formula.BetaModuliProduct_dvd_of_lt
#check @PA.Formula.mod_eq_of_mod_BetaModuliProduct_eq
#check @PA.Formula.BetaEntry_of_mod_BetaModuliProduct_eq
#check @PA.Formula.BetaModulus_pair_coprime_of_lt_le_mul_betaFact
#check @PA.Formula.BetaModuliProduct_coprime_modulus_of_le_mul_betaFact
#check @PA.Formula.BetaModuliProduct_coprime_next_of_le_mul_betaFact
#check @PA.Formula.beta_entries_exist_lt_mul_betaFact
#check @PA.Formula.beta_entries_exist_through_mul_betaFact
#check @PA.Formula.div2Iter
#check @PA.Formula.div2Iter_eq_shiftRight
#check @PA.Formula.div2Iter_mod_two_eq_zero_of_not_mem
#check @PA.Formula.shiftRight_lt_trace_modulus
#check @PA.Formula.div2_step_shiftRight
#check @PA.Formula.div2_step_shiftRight_one
#check @PA.Formula.HFMemTrace_exists_of_mem
#check @PA.Formula.BetaEntry_functional
#check @PA.Formula.BetaDiv2Step_div_two
#check @PA.Formula.BetaDiv2Step_bit_one_testBit_zero
#check @PA.Formula.BetaDiv2StepsThrough_entry_shiftRight
#check @PA.Formula.HFMemTrace_entry_shiftRight
#check @PA.Formula.BetaDiv2Step_bit_zero_of_not_mem
#check @PA.Formula.BetaDiv2Step_current_double_of_not_mem
#check @PA.Formula.HFMemTrace_mem
#check @PA.Formula.hfMemAt_sound
#check @PA.Formula.hfMemAt_complete
#check @PA.Formula.hfMemAt_exact
#check @PA.Formula.hfMemAt_free
#check @PA.Formula.rename_hfMemAt
#check @PA.Formula.hfUpVarMap
#check @PA.Formula.hfFormulaAt
#check @PA.Formula.hfFormulaAt_free
#check @PA.Formula.translateHFFormula
#check @PA.Formula.hfContextAt
#check @PA.Formula.translateHFContext
#check @PA.Formula.hfFormulaAt_ext
#check @PA.Formula.hfFormulaAt_ext_free
#check @PA.Formula.hfFormulaAt_source_rename
#check @PA.Formula.rename_hfFormulaAt
#check @PA.Formula.hfFormulaAt_rename_succ
#check @PA.Formula.hfContextAt_rename_succ
#check @PA.Formula.hfContextAt_cons_rename_succ
#check @PA.Formula.subst_instTerm_var_hfFormulaAt
#check @PA.Formula.hfFormulaAt_eq_translateHFFormula_of_HF_sentence
#check @PA.Formula.hfFormulaAt_exact
#check @PA.Formula.translateHFFormula_exact
#check @PA.Formula.translated_HF_axiom_sat_nat
#check @PA.Formula.translated_HFFin_axiom_sat_nat
#check @PA.Formula.hfFormulaAt_sentence_of_HF_sentence
#check @PA.Formula.translateHFFormula_sentence_of_HF_sentence
#check @PA.Formula.translated_HF_axiom_sentence
#check @PA.Formula.translatedHFAx
#check @PA.Formula.translatedHFFinAx
#check @PA.Formula.translatedHFAx_intro
#check @PA.Formula.translatedHFFinAx_intro
#check @PA.Formula.translatedHFFinAx_of_translatedHFAx
#check @PA.Formula.Sentences_translatedHFAx
#check @PA.Formula.Sentences_translatedHFFinAx
#check @PA.Formula.BProv_translatedHFAx_of_HFAx
#check @PA.Formula.BProv_translatedHFFinAx_of_HFFinAx
#check @PA.Formula.BProv_lift_translatedHFAx_to_PA
#check @PA.Formula.BProv_lift_translatedHFFinAx_to_PA
#check @PA.Formula.standard_sat_translatedHFAx
#check @PA.Formula.standard_sat_translatedHFFinAx
#check @PA.Formula.TranslatedHFAxiomProofs
#check @PA.Formula.TranslatedHFFinAxiomProofs
#check @PA.Formula.translatedHFAxiomProofs_of_remaining
#check @PA.Formula.translatedHFFinAxiomProofs_of_remaining
#check @PA.Formula.BProv_Ax_s_of_translatedHFAx_of_proofs
#check @PA.Formula.BProv_Ax_s_of_translatedHFFinAx_of_proofs
#check @PA.Formula.Prov_hfFormulaAt_of_Prov
#check @PA.Formula.BProv_hfFormulaAt_of_BProv_HFFin
#check @PA.Formula.BProv_translateHFFormula_of_BProv_HFFin
#check @AckermannHF.HFAx_s
#check @AckermannHF.Sentences_HF
#check @AckermannHF.HFFinAx_s
#check @AckermannHF.Sentences_HFFin
#check @AckermannHF.HF_finite_induction_form
#check @AckermannHF.HF_finite_induction_form_spec
#check @AckermannHF.prefixBelow
#check @AckermannHF.mem_prefixBelow_iff
#check @AckermannHF.mem_zero_of_odd_double
#check @AckermannHF.prefixBelow_self_eq
#check @AckermannHF.sat_HF_finite_induction_standard
#check @AckermannHF.standard_sat_HFFin
#check @AckermannHF.HFFinAx_s_finite_induction
#check @AckermannHF.semantic_finite_induction_schema_of_HFFinAx_s
#check @AckermannHF.FirstOrderFiniteAdjunctionModel
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.sepBy_exists
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.binUnion_exists
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.union_exists
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.chainSubsetsMax_exists
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.ordinalLike_empty_or_succ
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.succRecTotal_of_ordinalLike
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.succRecApprox_value_ordinalLike
#check @AckermannHF.FirstOrderFiniteAdjunctionModel.succRecApprox_value_unique
#check @AckermannHF.firstOrderFiniteAdjunctionModel_of_HFFinAx_s
#check @AckermannHF.eq_empty_iff_no_mem
#check @AckermannHF.exists_mem_of_ne_empty
#check @AckermannHF.exists_mem_not_mem_of_lt
#check @AckermannHF.maxHighNotLowBelow
#check @AckermannHF.le_maxHighNotLowBelow_of_lt
#check @AckermannHF.maxHighNotLowBelow_spec_of_exists
#check @AckermannHF.highNotLowWitness
#check @AckermannHF.highNotLowWitness_spec_of_lt
#check @AckermannHF.exists_mem_diff_of_ne
#check @AckermannHF.exists_max_mem_of_ne_empty
#check @AckermannHF.HF_emptyAt_empty
#check @AckermannHF.HF_adjoinAt_adjoin
#check @AckermannHF.HF_succAt_spec
#check @AckermannHF.single_spec
#check @AckermannHF.upair_spec
#check @AckermannHF.kpair_mem
#check @AckermannHF.kpair_injective
#check @AckermannHF.HF_singleAt_spec
#check @AckermannHF.HF_upairAt_spec
#check @AckermannHF.HF_kpairAt_spec
#check @AckermannHF.HF_pairMemAt_spec
#check @AckermannHF.PairFunctional
#check @AckermannHF.PairKeysBelowSucc
#check @AckermannHF.PairTotalBelowSucc
#check @AckermannHF.PairSuccStep
#check @AckermannHF.SuccRecApprox
#check @AckermannHF.HF_pairFunctionalAt_spec
#check @AckermannHF.HF_pairKeysBelowSuccAt_spec
#check @AckermannHF.HF_pairTotalBelowSuccAt_spec
#check @AckermannHF.HF_pairSuccStepAt_spec
#check @AckermannHF.HF_pairBaseAt_spec
#check @AckermannHF.HF_pairZeroBaseAt_spec
#check @AckermannHF.HF_succRecApproxAt_spec
#check @AckermannHF.HF_succRecTotalAt
#check @AckermannHF.HF_succRecTotalOnOrdinalAt
#check @AckermannHF.HF_memMaxAt
#check @AckermannHF.HF_chainSubsetsMaxAt
#check @AckermannHF.HF_subsetAt_spec
#check @AckermannHF.HF_sepByAt
#check @AckermannHF.HF_sepByAt_spec
#check @AckermannHF.HF_binUnionAt
#check @AckermannHF.HF_binUnionAt_spec
#check @AckermannHF.HF_unionAt
#check @AckermannHF.HF_unionAt_spec
#check @AckermannHF.ChainLike
#check @AckermannHF.HF_chainLikeAt
#check @AckermannHF.HF_chainLikeAt_spec
#check @AckermannHF.HF_transitiveAt_spec
#check @AckermannHF.HF_memTotalOnAt_spec
#check @AckermannHF.HF_ordinalLikeAt_spec
#check @AckermannHF.HF_memMaxAt_spec
#check @AckermannHF.HF_chainSubsetsMaxAt_spec
#check @AckermannHF.HF_emptyAt_free
#check @AckermannHF.HF_adjoinAt_free
#check @AckermannHF.HF_pairMemAt_free
#check @AckermannHF.HF_succRecApproxAt_free
#check @AckermannHF.HF_ordinalLikeAt_free
#check @AckermannHF.OrdinalLike.of_mem
#check @AckermannHF.OrdinalLike.empty
#check @AckermannHF.OrdinalLike.adjoin_self
#check @AckermannHF.ordinalCode_ordinalLike
#check @AckermannHF.HF_ordinalLikeAt_of_ordinalCode
#check @AckermannHF.ordinalLike_is_ordinalCode
#check @AckermannHF.HF_ordinalLikeAt_exact
#check @AckermannHF.succIterObj_ordinalCode
#check @AckermannHF.succRecTrace_mem_iff
#check @AckermannHF.succRecTrace_pair_mem
#check @AckermannHF.succRecTrace_functional
#check @AckermannHF.succRecTrace_keysBelowSucc
#check @AckermannHF.succRecTrace_totalBelowSucc
#check @AckermannHF.succRecTrace_succStep
#check @AckermannHF.succRecTrace_succRecApprox
#check @AckermannHF.succRecApprox_value_of_le
#check @AckermannHF.mulRecTrace_mem_iff
#check @AckermannHF.mulRecTrace_pair_mem
#check @AckermannHF.mulRecTrace_functional
#check @AckermannHF.mulRecTrace_keysBelowSucc
#check @AckermannHF.mulRecTrace_totalBelowSucc
#check @AckermannHF.PAInHF.domainForm
#check @AckermannHF.PAInHF.zeroGraph
#check @AckermannHF.PAInHF.succGraph
#check @AckermannHF.PAInHF.addGraphAt
#check @AckermannHF.PAInHF.addGraph
#check @AckermannHF.PAInHF.mulStepAt
#check @AckermannHF.PAInHF.mulRecApproxAt
#check @AckermannHF.PAInHF.mulGraphAt
#check @AckermannHF.PAInHF.mulGraph
#check @AckermannHF.PAInHF.domain_ordinalCode
#check @AckermannHF.PAInHF.domain_exact
#check @AckermannHF.PAInHF.zeroGraph_ordinalCode
#check @AckermannHF.PAInHF.zeroGraph_exact_on_ordinalCode
#check @AckermannHF.PAInHF.succGraph_ordinalCode
#check @AckermannHF.PAInHF.succGraph_exact_on_ordinalCodes
#check @AckermannHF.PAInHF.addGraph_ordinalCode
#check @AckermannHF.PAInHF.addGraphAt_ordinalCode
#check @AckermannHF.PAInHF.addGraphAt_value_of_ordinalInputs
#check @AckermannHF.PAInHF.addGraphAt_exact_on_ordinalCodes
#check @AckermannHF.PAInHF.addGraph_exact_on_ordinalCodes
#check @AckermannHF.PAInHF.mulGraph_ordinalCode
#check @AckermannHF.PAInHF.mulRecApproxAt_value_of_le
#check @AckermannHF.PAInHF.mulGraph_exact_on_ordinalCodes
#check @AckermannHF.PAInHF.mulGraph_value_of_ordinalInputs
#check @AckermannHF.PAInHF.domainForm_free
#check @AckermannHF.PAInHF.addGraphAt_free
#check @AckermannHF.PAInHF.mulGraphAt_free
#check @AckermannHF.PAInHF.domain_empty_model
#check @AckermannHF.PAInHF.zeroGraph_empty_model
#check @AckermannHF.PAInHF.succGraph_adjoin_self_model
#check @AckermannHF.PAInHF.domain_adjoin_self_model
#check @AckermannHF.PAInHF.Domain
#check @AckermannHF.PAInHF.domainZero
#check @AckermannHF.PAInHF.domainSucc
#check @AckermannHF.PAInHF.domainZero_val
#check @AckermannHF.PAInHF.domainSucc_val
#check @AckermannHF.PAInHF.adjoin_self_ne_empty_model
#check @AckermannHF.PAInHF.adjoin_self_injective_on_ordinalLike_model
#check @AckermannHF.PAInHF.domainSucc_injective_model
#check @AckermannHF.PAInHF.domainSucc_ne_zero_model
#check @AckermannHF.PAInHF.domainElement_domainForm_model
#check @AckermannHF.PAInHF.domainZero_domainForm_model
#check @AckermannHF.PAInHF.domainZero_zeroGraph_model
#check @AckermannHF.PAInHF.domainSucc_domainForm_model
#check @AckermannHF.PAInHF.domainSucc_succGraph_model
#check @AckermannHF.PAInHF.zeroGraph_domain_model
#check @AckermannHF.PAInHF.zeroGraph_domain
#check @AckermannHF.PAInHF.succGraph_preserves_domain_model
#check @AckermannHF.PAInHF.succGraph_preserves_domain
#check @AckermannHF.PAInHF.termGraphAt
#check @AckermannHF.PAInHF.termGraphAt_free
#check @AckermannHF.PAInHF.termGraphAt_map_ext
#check @AckermannHF.PAInHF.termGraphAt_var_spec
#check @AckermannHF.PAInHF.termGraphAt_zero_spec
#check @AckermannHF.PAInHF.termGraphAt_succ_var_spec
#check @AckermannHF.PAInHF.termGraphAt_map_ext_free
#check @AckermannHF.PAInHF.termGraphAt_var_model
#check @AckermannHF.PAInHF.termGraphAt_zero_model
#check @AckermannHF.PAInHF.termGraphAt_succ_var_model
#check @AckermannHF.PAInHF.termGraphAt_exact
#check @AckermannHF.PAInHF.upVarMap
#check @AckermannHF.PAInHF.insertAt
#check @AckermannHF.PAInHF.insertAt_zero
#check @AckermannHF.PAInHF.insertAt_lt
#check @AckermannHF.PAInHF.insertAt_eq
#check @AckermannHF.PAInHF.insertAt_gt
#check @AckermannHF.PAInHF.scons_insertAt
#check @AckermannHF.PAInHF.scons2_insertAt
#check @AckermannHF.PAInHF.scons3_insertAt
#check @AckermannHF.PAInHF.scons_insertAt_prefix
#check @AckermannHF.PAInHF.scons2_insertAt_prefix
#check @AckermannHF.PAInHF.scons3_insertAt_prefix
#check @PA.Formula.substZeroAt
#check @PA.Formula.upSubst_substZeroAt
#check @PA.Formula.substSuccAt
#check @PA.Formula.upSubst_substSuccAt
#check @AckermannHF.PAInHF.substZeroAfterMap
#check @AckermannHF.PAInHF.substZeroBeforeMap
#check @AckermannHF.PAInHF.substZeroAfterMap_zero_zero
#check @AckermannHF.PAInHF.substZeroBeforeMap_zero_zero
#check @AckermannHF.PAInHF.substZeroBeforeMap_ne_replaced_slot
#check @AckermannHF.PAInHF.replaceAt
#check @AckermannHF.PAInHF.replaceAt_eq
#check @AckermannHF.PAInHF.replaceAt_ne
#check @AckermannHF.PAInHF.replaceAt_zero_scons
#check @AckermannHF.PAInHF.succReplaceAt
#check @AckermannHF.PAInHF.succReplaceAt_eq
#check @AckermannHF.PAInHF.succReplaceAt_ne
#check @AckermannHF.PAInHF.scons_replaceAt
#check @AckermannHF.PAInHF.scons_replaceAt_prefix
#check @AckermannHF.PAInHF.scons2_replaceAt_prefix
#check @AckermannHF.PAInHF.scons3_replaceAt_prefix
#check @AckermannHF.PAInHF.scons_succReplaceAt_prefix
#check @AckermannHF.PAInHF.scons2_succReplaceAt_prefix
#check @AckermannHF.PAInHF.scons3_succReplaceAt_prefix
#check @AckermannHF.PAInHF.termGraphAt_substZero_insert_model
#check @AckermannHF.PAInHF.termGraphAt_substZeroAt_insert_model
#check @AckermannHF.PAInHF.termGraphAt_substSuccAt_replace_model
#check @AckermannHF.PAInHF.formulaAt
#check @AckermannHF.PAInHF.formulaAt_map_ext
#check @AckermannHF.PAInHF.domainForm_scons_insertAt
#check @AckermannHF.PAInHF.domainForm_scons_succReplaceAt
#check @AckermannHF.PAInHF.formulaAt_substZeroAt_insert_model
#check @AckermannHF.PAInHF.formulaAt_substZero_insert_model
#check @AckermannHF.PAInHF.formulaAt_substZero_scons_model
#check @AckermannHF.PAInHF.Sat_termGraphAt_insertAt_shift_formula_prefix
#check @AckermannHF.PAInHF.formulaAt_substTermAt_insert_model
#check @AckermannHF.PAInHF.formulaAt_subst_instTerm_of_termGraph_model
#check @AckermannHF.PAInHF.formulaAt_substSuccAt_replace_model
#check @AckermannHF.PAInHF.formulaAt_substSuccVar_scons_model
#check @AckermannHF.PAInHF.formulaAt_induction_valid_finite_model
#check @AckermannHF.PAInHF.formulaAt_free
#check @AckermannHF.PAInHF.formulaAt_eq_var_spec
#check @AckermannHF.PAInHF.formulaAt_zeroNotSucc_valid
#check @AckermannHF.PAInHF.formulaAt_succInj_of_irrefl
#check @AckermannHF.PAInHF.formulaAt_closeN_valid
#check @AckermannHF.PAInHF.formulaAt_sealPA_valid
#check @AckermannHF.PAInHF.formulaAt_eq_var_model
#check @AckermannHF.PAInHF.formulaAt_zeroNotSucc_model
#check @AckermannHF.PAInHF.formulaAt_succInj_model
#check @AckermannHF.PAInHF.formulaAt_closeN_valid_model
#check @AckermannHF.PAInHF.formulaAt_sealPA_valid_model
#check @AckermannHF.PAInHF.translated_zeroNotSucc_sat_model
#check @AckermannHF.PAInHF.translated_succInj_sat_model
#check @AckermannHF.PAInHF.formulaAt_exact
#check @AckermannHF.PAInHF.translateFormula
#check @AckermannHF.PAInHF.translated_zeroNotSucc_sat
#check @AckermannHF.PAInHF.translated_succInj_sat_of_irrefl
#check @AckermannHF.PAInHF.translated_succInj_sat_of_HFAx_s
#check @AckermannHF.PAInHF.addGraphAt_zero_right_model
#check @AckermannHF.PAInHF.addGraphAt_of_succRecApprox_model
#check @AckermannHF.PAInHF.addGraphAt_value_unique_finite_model
#check @AckermannHF.PAInHF.addGraphAt_outputs_eq_finite_model
#check @AckermannHF.PAInHF.addGraphAt_succ_right_of_addGraphAt_model
#check @AckermannHF.PAInHF.addGraphAt_succ_right_of_succRecApprox_model
#check @AckermannHF.PAInHF.MulStep
#check @AckermannHF.PAInHF.MulRecApprox
#check @AckermannHF.PAInHF.MulRecTotal
#check @AckermannHF.PAInHF.mulStepAt_spec
#check @AckermannHF.PAInHF.mulRecApproxAt_spec
#check @AckermannHF.PAInHF.mulRecTotalAt_spec
#check @AckermannHF.PAInHF.mulRecTotalOnOrdinalAt_spec
#check @AckermannHF.PAInHF.zeroMulRecGraph_mulRecApprox
#check @AckermannHF.PAInHF.mulRecGraphSucc_mulRecApprox
#check @AckermannHF.PAInHF.mulRecTotal_of_ordinalLike_of_predecessor
#check @AckermannHF.PAInHF.mulRecTotal_of_ordinalLike_finite_model
#check @AckermannHF.PAInHF.mulRecApprox_value_ordinalLike
#check @AckermannHF.PAInHF.mulRecApprox_value_unique
#check @AckermannHF.PAInHF.mulGraphAt_of_mulRecApprox_model
#check @AckermannHF.PAInHF.mulGraphAt_value_unique_finite_model
#check @AckermannHF.PAInHF.mulGraphAt_outputs_eq_finite_model
#check @AckermannHF.PAInHF.mulGraphAt_succ_right_of_mulRecApprox_model
#check @AckermannHF.PAInHF.mulStepAt_empty_model
#check @AckermannHF.PAInHF.mulGraphAt_zero_right_model
#check @AckermannHF.PAInHF.termGraphAt_succ_var_firstOrder_model
#check @AckermannHF.PAInHF.termGraphAt_add_var_zero_model
#check @AckermannHF.PAInHF.termGraphAt_mul_var_zero_model
#check @AckermannHF.PAInHF.termGraphAt_mul_var_var_of_mulRecApprox_model
#check @AckermannHF.PAInHF.termGraphAt_mul_var_succ_var_of_mulRecApprox_model
#check @AckermannHF.PAInHF.termGraphAt_add_mul_var_var_var_of_traces_model
#check @AckermannHF.PAInHF.termGraphAt_add_var_var_of_succRecApprox_model
#check @AckermannHF.PAInHF.termGraphAt_add_var_succ_var_of_succRecApprox_model
#check @AckermannHF.PAInHF.termGraphAt_succ_add_var_var_of_succRecApprox_model
#check @AckermannHF.PAInHF.termGraphAt_PA_rename
#check @AckermannHF.PAInHF.termGraphAt_rename
#check @AckermannHF.PAInHF.termGraphAt_inst_out
#check @AckermannHF.PAInHF.termGraphAt_value_ordinalLike_finite_model
#check @AckermannHF.PAInHF.termGraphAt_outputs_eq_finite_model
#check @AckermannHF.PAInHF.termGraphAt_transport_model
#check @AckermannHF.PAInHF.Sat_termGraphAt_insertAt_shift_prefix
#check @AckermannHF.PAInHF.termGraphAt_substTermAt_replaced_var_model
#check @AckermannHF.PAInHF.termGraphAt_substTermAt_insert_model
#check @AckermannHF.PAInHF.formulaAt_addZero_valid_model
#check @AckermannHF.PAInHF.formulaAt_mulZero_valid_model
#check @AckermannHF.PAInHF.formulaAt_addSucc_valid_model_of_succRecTotal
#check @AckermannHF.PAInHF.formulaAt_addSucc_valid_model_of_mem_max_exists
#check @AckermannHF.PAInHF.formulaAt_addSucc_valid_finite_model
#check @AckermannHF.PAInHF.formulaAt_mulSucc_valid_finite_model
#check @AckermannHF.PAInHF.translated_addZero_sat_of_HFAx_s
#check @AckermannHF.PAInHF.translated_mulZero_sat_of_HFAx_s
#check @AckermannHF.PAInHF.translated_addSucc_sat_of_HFFinAx_s
#check @AckermannHF.PAInHF.translated_mulSucc_sat_of_HFFinAx_s
#check @AckermannHF.PAInHF.translated_induction_sat_of_HFFinAx_s
#check @AckermannHF.PAInHF.translateFormula_exact
#check @AckermannHF.PAInHF.translated_PA_axiom_sat_codes
#check @AckermannHF.PAInHF.formulaAt_PA_rename
#check @AckermannHF.PAInHF.rename_domainForm_up
#check @AckermannHF.PAInHF.formulaAt_rename
#check @AckermannHF.PAInHF.formulaAt_rename_succ_upVarMap
#check @AckermannHF.PAInHF.formulaAt_subst_instTerm_var
#check @AckermannHF.PAInHF.formulaAt_map_ext_free
#check @AckermannHF.PAInHF.formulaAt_sentence_of_PA_sentence
#check @AckermannHF.PAInHF.translateFormula_sentence_of_PA_sentence
#check @AckermannHF.PAInHF.formulaAt_eq_translateFormula_of_PA_sentence
#check @AckermannHF.PAInHF.translated_PA_axiom_sentence
#check @AckermannHF.PAInHF.BProv_HF_translated_zeroNotSucc
#check @AckermannHF.PAInHF.BProv_HF_translated_succInj
#check @AckermannHF.PAInHF.BProv_HF_translated_addZero
#check @AckermannHF.PAInHF.BProv_HF_translated_mulZero
#check @AckermannHF.PAInHF.BProv_HFFin_translated_zeroNotSucc
#check @AckermannHF.PAInHF.BProv_HFFin_translated_succInj
#check @AckermannHF.PAInHF.BProv_HFFin_translated_addZero
#check @AckermannHF.PAInHF.BProv_HFFin_translated_mulZero
#check @AckermannHF.PAInHF.BProv_HFFin_translated_addSucc
#check @AckermannHF.PAInHF.BProv_HFFin_translated_mulSucc
#check @AckermannHF.PAInHF.BProv_HFFin_translated_induction
#check @AckermannHF.PAInHF.BProv_HFFin_translated_PA_axiom
#check @AckermannHF.PAInHF.translatedPAAx
#check @AckermannHF.PAInHF.translatedPAAx_intro
#check @AckermannHF.PAInHF.Sentences_translatedPAAx
#check @AckermannHF.PAInHF.BProv_translatedPAAx_of_PAAx
#check @AckermannHF.PAInHF.translateContext
#check @AckermannHF.PAInHF.translateContextAt
#check @AckermannHF.PAInHF.domainContextAt
#check @AckermannHF.PAInHF.translateContextAt_id
#check @AckermannHF.PAInHF.rename_domainForm_inst
#check @AckermannHF.PAInHF.rename_domainForm_inst_zero
#check @AckermannHF.PAInHF.domainContextAt_rename
#check @AckermannHF.PAInHF.mem_domainContextAt
#check @AckermannHF.PAInHF.mem_domainContextAt_mono
#check @AckermannHF.PAInHF.BProv_mono_domainContextAt
#check @AckermannHF.PAInHF.domainContextAt_upVarMap_succ
#check @AckermannHF.PAInHF.translateContextAt_rename_succ_upVarMap
#check @AckermannHF.PAInHF.mem_translateContext_of_mem
#check @AckermannHF.PAInHF.mem_translateContextAt_of_mem
#check @AckermannHF.PAInHF.BProv_translate_ass
#check @AckermannHF.PAInHF.BProv_formulaAt_ass
#check @AckermannHF.PAInHF.BProv_domainContextAt_var
#check @AckermannHF.PAInHF.Sat_rename_inst_domainForm_ordinalLike
#check @AckermannHF.PAInHF.Sat_domainContextAt_ordinalLike
#check @AckermannHF.PAInHF.BProv_translate_ax
#check @AckermannHF.PAInHF.BProv_formulaAt_ax
#check @AckermannHF.PAInHF.BProv_context_cons
#check @AckermannHF.PAInHF.BProv_impI
#check @AckermannHF.PAInHF.BProv_impI_after_prefix
#check @AckermannHF.PAInHF.BProv_andI
#check @AckermannHF.PAInHF.BProv_botE
#check @AckermannHF.PAInHF.BProv_andE1
#check @AckermannHF.PAInHF.BProv_andE2
#check @AckermannHF.PAInHF.BProv_orI1
#check @AckermannHF.PAInHF.BProv_orI2
#check @AckermannHF.PAInHF.BProv_orE
#check @AckermannHF.PAInHF.BProv_orE_after_prefix
#check @AckermannHF.PAInHF.BProv_allE
#check @AckermannHF.PAInHF.BProv_exI
#check @AckermannHF.PAInHF.BProv_allI_of_sentences
#check @AckermannHF.PAInHF.BProv_exE_of_sentences
#check @AckermannHF.PAInHF.BProv_translate_impI
#check @AckermannHF.PAInHF.BProv_formulaAt_impI
#check @AckermannHF.PAInHF.BProv_translate_impE
#check @AckermannHF.PAInHF.BProv_formulaAt_impE
#check @AckermannHF.PAInHF.BProv_translate_botE
#check @AckermannHF.PAInHF.BProv_formulaAt_botE
#check @AckermannHF.PAInHF.BProv_translate_lem
#check @AckermannHF.PAInHF.BProv_formulaAt_lem
#check @AckermannHF.PAInHF.BProv_formulaAt_eqRefl_var
#check @AckermannHF.PAInHF.formulaAt_eqRefl_zero_valid_of_HFFinAx_s
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_eqRefl_zero
#check @AckermannHF.PAInHF.formulaAt_eqRefl_valid_of_HFFinAx_s_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_eqRefl_domainContext
#check @AckermannHF.PAInHF.formulaAt_eqRefl_valid_of_HFFinAx_s_domainContext_le
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_eqRefl_domainContext_le
#check @AckermannHF.PAInHF.termGraphAt_exists_valid_of_HFFinAx_s_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_termGraphAt_exists_domainContext
#check @AckermannHF.PAInHF.termGraphAt_exists_valid_of_HFFinAx_s_domainContext_le
#check @AckermannHF.PAInHF.BProv_HFFin_termGraphAt_exists_domainContext_le
#check @AckermannHF.PAInHF.formulaAt_allE_valid_of_HFFinAx_s_domainContext
#check @AckermannHF.PAInHF.formulaAt_exI_valid_of_HFFinAx_s_domainContext
#check @AckermannHF.PAInHF.formulaAt_allE_valid_of_HFFinAx_s_domainContext_le
#check @AckermannHF.PAInHF.formulaAt_exI_valid_of_HFFinAx_s_domainContext_le
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_allE_term_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_exI_term_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_allE_term_domainContext_le
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_exI_term_domainContext_le
#check @AckermannHF.PAInHF.formulaAt_eqElim_valid_of_HFFinAx_s_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_eqElim_term_domainContext
#check @AckermannHF.PAInHF.formulaAt_eqElim_valid_of_HFFinAx_s_domainContext_le
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_eqElim_term_domainContext_le
#check @AckermannHF.PAInHF.BProv_formulaAt_eq_var_of_eq
#check @AckermannHF.PAInHF.BProv_formulaAt_eq_of_termGraphsAt
#check @AckermannHF.PAInHF.Sat_termGraphAt_shift_front
#check @AckermannHF.PAInHF.Sat_termGraphAt_shift_front_inv
#check @AckermannHF.PAInHF.Sat_termGraphAt_insert_after_output
#check @AckermannHF.PAInHF.Sat_termGraphAt_insert_after_output_inv
#check @AckermannHF.PAInHF.termGraphAt_total_of_ordinalLike
#check @AckermannHF.PAInHF.BProv_termGraphAt_eqElim_out
#check @AckermannHF.PAInHF.BProv_formulaAt_eqRefl_of_termGraphAt
#check @AckermannHF.PAInHF.BProv_eq_of_formulaAt_eq_var
#check @AckermannHF.PAInHF.BProv_formulaAt_eqElim_var
#check @AckermannHF.PAInHF.BProv_translate_andI
#check @AckermannHF.PAInHF.BProv_formulaAt_andI
#check @AckermannHF.PAInHF.BProv_translate_andE1
#check @AckermannHF.PAInHF.BProv_formulaAt_andE1
#check @AckermannHF.PAInHF.BProv_translate_andE2
#check @AckermannHF.PAInHF.BProv_formulaAt_andE2
#check @AckermannHF.PAInHF.BProv_translate_orI1
#check @AckermannHF.PAInHF.BProv_formulaAt_orI1
#check @AckermannHF.PAInHF.BProv_translate_orI2
#check @AckermannHF.PAInHF.BProv_formulaAt_orI2
#check @AckermannHF.PAInHF.BProv_translate_orE
#check @AckermannHF.PAInHF.BProv_formulaAt_orE
#check @AckermannHF.PAInHF.rename_eq_of_sentence
#check @AckermannHF.PAInHF.BProv_translate_allI_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_allI_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_allI
#check @AckermannHF.PAInHF.BProv_formulaAt_allI_domainContext
#check @AckermannHF.PAInHF.BProv_formulaAt_allI_domainContext_of_sentences
#check @AckermannHF.PAInHF.BProv_translate_allE_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_slot_context
#check @AckermannHF.PAInHF.BProv_formulaAt_slot_eqElim_context
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_equal_slot_context
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_var
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_var_context
#check @AckermannHF.PAInHF.BProv_formulaAt_allE_var_domainContext
#check @AckermannHF.PAInHF.BProv_translate_exI_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_slot_context
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_equal_slot_context
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_var
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_var_context
#check @AckermannHF.PAInHF.BProv_formulaAt_exI_var_domainContext
#check @AckermannHF.PAInHF.BProv_translate_exE_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_exE_raw
#check @AckermannHF.PAInHF.BProv_formulaAt_exE
#check @AckermannHF.PAInHF.BProv_formulaAt_exE_domainContext_of_sentences
#check @AckermannHF.PAInHF.Sat_domainContextAt_of_ordinalLike
#check @AckermannHF.PAInHF.BProv_formulaAt_of_Prov_with_term_rules
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_of_Prov_domainContext
#check @AckermannHF.PAInHF.BProv_formulaAt_of_PA_BProv_with_term_rules
#check @AckermannHF.PAInHF.BProv_HFFin_formulaAt_of_PA_BProv_domainContext
#check @AckermannHF.PAInHF.BProv_HFFin_translateFormula_of_PA_BProv
#check @AckermannHF.PAInHF.BProv_lift_translatedPAAx_to_HF
#check @AckermannHF.PAInHF.BProv_lift_translatedPAAx_to_HFFin
#check @AckermannHF.PAInHF.BProv_HFFin_of_translatedPAAx
#check @AckermannHF.PAInHF.BProv_HFFin_of_BProv_translatedPAAx_context
#check @AckermannHF.PAInHF.BProv_HFFin_of_BProv_translatedPAAx
#check @AckermannHF.PAInHF.standard_sat_translatedPAAx
#check @AckermannHF.sat_HF_model
#check @AckermannHF.standard_sat_HF
#check @AckermannHF.standard_sat_HFFin
#check @AckermannHF.AdjunctionModel.mem_irrefl
#check @AckermannHF.FirstOrderAdjunctionModel.mem_asymm
#check @AckermannHF.HF_extensionality_form
#check @AckermannHF.sat_HF_extensionality
#check @AckermannHF.HFAx_s_empty
#check @AckermannHF.HFAx_s_extensionality
#check @AckermannHF.HFAx_s_adjoin
#check @AckermannHF.HFAx_s_induction
#check @AckermannHF.semantic_empty_of_HFAx_s
#check @AckermannHF.semantic_extensionality_of_HFAx_s
#check @AckermannHF.semantic_adjoin_of_HFAx_s
#check @AckermannHF.semantic_induction_schema_of_HFAx_s
#check @AckermannHF.semantic_mem_irrefl_of_HFAx_s
#check @AckermannHF.FirstOrderHFModel
#check @AckermannHF.firstOrderHFModel_of_HFAx_s
#check @AckermannHF.FirstOrderAdjunctionModel
#check @AckermannHF.FirstOrderAdjunctionModel.mem_irrefl
#check @AckermannHF.FirstOrderAdjunctionModel.adjoin_self_mem
#check @AckermannHF.FirstOrderAdjunctionModel.adjoin_self_ne_self
#check @AckermannHF.FirstOrderAdjunctionModel.adjoin_self_not_mem_of_ordinalLike
#check @AckermannHF.FirstOrderAdjunctionModel.adjoin_self_injective_on_ordinalLike
#check @AckermannHF.FirstOrderAdjunctionModel.ordinalLike_empty
#check @AckermannHF.FirstOrderAdjunctionModel.ordinalLike_adjoin_self
#check @AckermannHF.FirstOrderAdjunctionModel.ordinalLike_eq_succ_of_mem_max
#check @AckermannHF.FirstOrderAdjunctionModel.ordinalLike_empty_or_succ_of_mem_max_exists
#check @AckermannHF.FirstOrderAdjunctionModel.single
#check @AckermannHF.FirstOrderAdjunctionModel.single_spec
#check @AckermannHF.FirstOrderAdjunctionModel.upair
#check @AckermannHF.FirstOrderAdjunctionModel.upair_spec
#check @AckermannHF.FirstOrderAdjunctionModel.kpair
#check @AckermannHF.FirstOrderAdjunctionModel.kpair_mem
#check @AckermannHF.FirstOrderAdjunctionModel.single_injective
#check @AckermannHF.FirstOrderAdjunctionModel.upair_eq_single
#check @AckermannHF.FirstOrderAdjunctionModel.kpair_injective
#check @AckermannHF.FirstOrderAdjunctionModel.HF_emptyAt_empty
#check @AckermannHF.FirstOrderAdjunctionModel.HF_adjoinAt_adjoin
#check @AckermannHF.FirstOrderAdjunctionModel.HF_succAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_singleAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_upairAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_kpairAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairMemAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.PairFunctional
#check @AckermannHF.FirstOrderAdjunctionModel.PairKeysBelowSucc
#check @AckermannHF.FirstOrderAdjunctionModel.PairTotalBelowSucc
#check @AckermannHF.FirstOrderAdjunctionModel.PairSuccStep
#check @AckermannHF.FirstOrderAdjunctionModel.zeroSuccRecGraph
#check @AckermannHF.FirstOrderAdjunctionModel.zeroSuccRecGraph_base
#check @AckermannHF.FirstOrderAdjunctionModel.zeroSuccRecGraph_succRecApprox
#check @AckermannHF.FirstOrderAdjunctionModel.succRecTotal_empty
#check @AckermannHF.FirstOrderAdjunctionModel.succRecGraphSucc
#check @AckermannHF.FirstOrderAdjunctionModel.succRecGraphSucc_old
#check @AckermannHF.FirstOrderAdjunctionModel.succRecGraphSucc_new
#check @AckermannHF.FirstOrderAdjunctionModel.succRecGraphSucc_succRecApprox
#check @AckermannHF.FirstOrderAdjunctionModel.succRecTotal_succ
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairFunctionalAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairKeysBelowSuccAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairTotalBelowSuccAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairSuccStepAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairBaseAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_pairZeroBaseAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.SuccRecApprox
#check @AckermannHF.FirstOrderAdjunctionModel.SuccRecTotal
#check @AckermannHF.FirstOrderAdjunctionModel.HF_succRecApproxAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_succRecTotalAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.HF_succRecTotalOnOrdinalAt_spec
#check @AckermannHF.FirstOrderAdjunctionModel.succRecTotal_of_ordinalLike_of_predecessor
#check @AckermannHF.FirstOrderAdjunctionModel.succRecTotal_of_ordinalLike_of_mem_max_exists
#check @AckermannHF.firstOrderAdjunctionModel_of_HFAx_s
#check @AckermannHF.ordinalHF_sat_HF
#check @AckermannHF.ordinalPA_sat_PA
#check @AckermannHF.standardShallowBiInterpretation
#check @AckermannHF.TheoryInterpretation
#check @AckermannHF.TheoryInterpretation.comp
#check @AckermannHF.setTheoryIdentityInterpretationOfAxiomProofs
#check @AckermannHF.translatedPATheoryInHFFinInterpretation
#check @AckermannHF.paInHFFinOfTranslatedPATheoryInterpretation
#check @AckermannHF.paInHFFinTheoryInterpretation
#check @AckermannHF.hfInTranslatedHFFinTheoryInterpretation
#check @AckermannHF.hfInPAOfTranslatedHFFinTheoryInterpretation
#check @AckermannHF.paIdentityInterpretationOfAxiomProofs
#check @AckermannHF.translatedHFFinTheoryInPAInterpretationOfAxiomProofs
#check @AckermannHF.translatedHFFinTheoryInPAInterpretationOfProofs
#check @AckermannHF.hfInPAInterpretationOfTranslatedHFFinAxiomProofs
#check @AckermannHF.hfInPAInterpretationOfTranslatedHFFinProofs
#check @AckermannHF.DeductiveBiInterpretationCertificate
#check AckermannHF.PAHFDeductiveBiInterpretationCertificate
#check AckermannHF.PAHFFinDeductiveBiInterpretationCertificate
#check @AckermannHF.StandardModelInterpretationCertificateFor
#check @AckermannHF.StandardModelInterpretationCertificate
#check @AckermannHF.StandardModelFiniteInterpretationCertificate
#check @AckermannHF.standardModelInterpretation
#check @AckermannHF.standardModelFiniteInterpretation
#check @AckermannHF.PA_standard_model_interpretable_with_HF
#check @AckermannHF.PA_standard_model_interpretable_with_HFFin
#check @AckermannHF.PA_biinterpretable_with_HF_standard
#check @AckermannHF.PA_biinterpretable_with_HFFin_standard
#print axioms PA.Formula.sat_axiom
#print axioms PA.Formula.sat_axiom_s
#print axioms PA.Formula.soundness
#print axioms PA.Formula.soundness_BProv
#print axioms AckermannHF.sat_HF_model
#print axioms AckermannHF.standard_sat_HF
#print axioms AckermannHF.standard_sat_HFFin
#print axioms AckermannHF.PA_standard_model_interpretable_with_HF
#print axioms AckermannHF.PA_standard_model_interpretable_with_HFFin
#print axioms AckermannHF.PA_biinterpretable_with_HF_standard
#print axioms AckermannHF.PA_biinterpretable_with_HFFin_standard

-- the shallow self-contained pair, with their free dependency audits
#check @Forward.Pairing
#check @Forward.Union
#check @Forward.Replacement
#check @Forward.Infinity
#print axioms Forward.Pairing
#check @Reverse.Closure_holds
#print axioms Reverse.Closure_holds
