(** Assumption audit for restricted-proof endpoint admissibility. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedProofAdmissibility.

Import PABoundedRawCodedRestrictedProofAdmissibility.

Check raw_fixedLevelTruthAdmissible_of_bounded_atomic_assignment.
Check raw_restrictedProof_rule_endpoint_admissible.
Check raw_restrictedProof_rule_endpoint_admissible_zero.
Check raw_proofAtomicallyAdequate_recursive_child.
Check raw_restrictedProofAtomicallyAdequate_recursive_child.
Check raw_restrictedProof_recursive_child_rule_endpoint_admissible.
Check raw_restrictedProof_recursive_child_rule_endpoint_admissible_zero.

Print Assumptions
  raw_fixedLevelTruthAdmissible_of_bounded_atomic_assignment.
Print Assumptions raw_restrictedProof_rule_endpoint_admissible.
Print Assumptions raw_restrictedProof_rule_endpoint_admissible_zero.
Print Assumptions raw_proofAtomicallyAdequate_recursive_child.
Print Assumptions raw_restrictedProofAtomicallyAdequate_recursive_child.
Print Assumptions
  raw_restrictedProof_recursive_child_rule_endpoint_admissible.
Print Assumptions
  raw_restrictedProof_recursive_child_rule_endpoint_admissible_zero.
