(** Assumption audit for admissibility-guarded coherence at every fixed
    metatheoretic truth level. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthAdmissibleCoherence.

Import PABoundedRawCodedFixedLevelTruthAdmissibleCoherence.

Check RawCodedFormulaShapeSyntaxRow.
Check raw_codedFormulaAtomicallyAdequate_shape_at.
Check raw_fixedLevelTruthAdmissible_imp_children_core.
Check raw_fixedLevelTruthAdmissible_and_children_core.
Check raw_fixedLevelTruthAdmissible_or_children_core.
Check raw_fixedLevelTruthAdmissible_all_child_core.
Check raw_fixedLevelTruthAdmissible_ex_child_core.

Check RawFixedLevelAdmissibleLoweringBelow.
Check fixedLevelAdmissibleLoweringBelowTermAt.
Check raw_sat_fixedLevelAdmissibleLoweringBelowTermAt_iff.
Check raw_fixedLevelAdmissibleLoweringBelow_all.
Check raw_fixedLevelTruthCertificate_admissible_successor_lower.

Check RawFixedLevelAdmissibleRaisingBelow.
Check fixedLevelAdmissibleRaisingBelowTermAt.
Check raw_sat_fixedLevelAdmissibleRaisingBelowTermAt_iff.
Check raw_fixedLevelAdmissibleRaisingBelow_all.
Check raw_fixedLevelTruthCertificate_admissible_successor_raise.

Check raw_fixedLevelAdmissibleTruthCertificateCoherence_all.
Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_raw_valid.
Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_closed.
Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_closed_sentence.
Check PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula_closed.
Check PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula.

Print Assumptions raw_codedFormulaAtomicallyAdequate_shape_at.
Print Assumptions raw_fixedLevelAdmissibleLoweringBelow_all.
Print Assumptions raw_fixedLevelTruthCertificate_admissible_successor_lower.
Print Assumptions raw_fixedLevelAdmissibleRaisingBelow_all.
Print Assumptions raw_fixedLevelTruthCertificate_admissible_successor_raise.
Print Assumptions raw_fixedLevelAdmissibleTruthCertificateCoherence_all.
Print Assumptions
  PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula.
