(** Assumption audit for represented positive/all-level single-substitution
    Tarski transport. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthOperationTarskiSubstitutionPositive.

Import
  PABoundedRawCodedFixedLevelTruthOperationTarskiSubstitutionPositive.

Check codedFormulaSubstitutionOpeningCompatibilityTermAt.
Check raw_sat_codedFormulaSubstitutionOpeningCompatibilityTermAt_iff.
Check raw_codedFormulaSubstitutionOpeningCompatibility_root.
Check raw_codedFormulaSubstitutionOpeningCompatibility_prepend.
Check raw_codedFormulaShiftAssignmentLocalCompatibility_amount_prepend.
Check codedFormulaSubstitutionBinderCompatibilityTermAt.
Check raw_sat_codedFormulaSubstitutionBinderCompatibilityTermAt_iff.
Check raw_codedFormulaSubstitutionBinderCompatibility_prepend.
Check raw_codedTermOpening_evaluation_values_agree_local.
Check raw_formulaSubstitutionEqOperationRow_rankZero_outputs_agree_local.
Check raw_formulaSubstitutionEqOperationRow_scheduled_transport.
Check formulaSubstitutionScheduledTransportBelowTermAt.
Check raw_sat_formulaSubstitutionScheduledTransportBelowTermAt_iff.
Check raw_formulaSubstitutionScheduledTransportBelow_succ.
Check raw_formulaSubstitutionScheduledTransportBelow_all.
Check raw_formulaSubstitutionOperationTrace_scheduled_transport.
Check raw_fixedLevelFormulaSingleSubstitutionTarskiStep_scheduled.
Check raw_fixedLevelFormulaSingleSubstitutionTarskiStep_all.
Check fixedLevelFormulaSubstitutionTarskiStepFormula.
Check PA_proves_fixedLevelFormulaSubstitutionTarskiStepFormula.

Print Assumptions
  raw_codedFormulaSubstitutionOpeningCompatibility_prepend.
Print Assumptions raw_codedTermOpening_evaluation_values_agree_local.
Print Assumptions
  raw_formulaSubstitutionEqOperationRow_scheduled_transport.
Print Assumptions raw_formulaSubstitutionScheduledTransportBelow_succ.
Print Assumptions raw_formulaSubstitutionScheduledTransportBelow_all.
Print Assumptions
  raw_fixedLevelFormulaSingleSubstitutionTarskiStep_scheduled.
Print Assumptions raw_fixedLevelFormulaSingleSubstitutionTarskiStep_all.
Print Assumptions
  PA_proves_fixedLevelFormulaSubstitutionTarskiStepFormula.
