(** Assumption audit for operation/evaluator Tarski compatibility and the
    complete level-zero fixed-truth transport theorem. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthOperationTarski.

Import PABoundedRawCodedFixedLevelTruthOperationTarski.

Check raw_termEvaluationCertificate_var_view.
Check raw_termEvaluationCertificate_succ_view.
Check raw_termEvaluationCertificate_add_view.
Check raw_termEvaluationCertificate_mul_view.
Check raw_termOperationEvaluationAgreementBelow_all.
Check raw_codedTermShift_evaluation_values_agree.
Check raw_codedTermShift_zero_evaluation_values_agree.
Check raw_codedTermOpening_zero_evaluation_values_agree_of_prepend.

Check raw_rankZeroTruthCertificate_eq_view.
Check raw_formulaShiftEqOperationRow_rankZero_outputs_agree.
Check raw_formulaSubstitutionEqOperationRow_zero_rankZero_outputs_agree.
Check raw_formulaOperationRankZeroAgreementBelow_all.
Check raw_codedFormulaShift_rankZero_outputs_agree.
Check raw_codedFormulaSingleSubstitution_rankZero_outputs_agree.

Check raw_fixedLevelTruthCertificateTransport_zero_of_outputs_agree.
Check raw_fixedLevelFormulaShiftTarskiStep_zero.
Check raw_fixedLevelFormulaSubstitutionTarskiStep_zero.
Check PA_proves_fixedLevelFormulaShiftTarskiStepFormula_zero.
Check PA_proves_fixedLevelFormulaSubstitutionTarskiStepFormula_zero.
Check RawCodedFormulaShiftAssignmentLocalCompatibility.
Check raw_codedFormulaShiftAssignmentRelation_local.
Check raw_shiftedIndex_under_successors.
Check raw_codedFormulaShiftAssignmentLocalCompatibility_prepend.
Check RawTermOperationEvaluationAgreementBiBelow.
Check raw_termOperationEvaluationAgreementBiBelow_all.
Check raw_codedTermShift_evaluation_values_agree_local.

Print Assumptions raw_termOperationEvaluationAgreementBelow_all.
Print Assumptions raw_codedTermShift_evaluation_values_agree.
Print Assumptions raw_codedTermOpening_zero_evaluation_values_agree_of_prepend.
Print Assumptions raw_formulaOperationRankZeroAgreementBelow_all.
Print Assumptions raw_codedFormulaShift_rankZero_outputs_agree.
Print Assumptions raw_codedFormulaSingleSubstitution_rankZero_outputs_agree.
Print Assumptions raw_fixedLevelFormulaShiftTarskiStep_zero.
Print Assumptions raw_fixedLevelFormulaSubstitutionTarskiStep_zero.
Print Assumptions PA_proves_fixedLevelFormulaShiftTarskiStepFormula_zero.
Print Assumptions
  PA_proves_fixedLevelFormulaSubstitutionTarskiStepFormula_zero.
Print Assumptions
  raw_codedFormulaShiftAssignmentLocalCompatibility_prepend.
Print Assumptions raw_termOperationEvaluationAgreementBiBelow_all.
Print Assumptions raw_codedTermShift_evaluation_values_agree_local.
