From BoundedPAConsistency Require Import
  RawCodedRestrictedPADynamicSoundnessSubstitution.

Import PABoundedRawCodedRestrictedPADynamicSoundnessSubstitution.

Check rawRestrictedPADynamicSourceContextSubstitutionTree.
Check rawRestrictedPADynamicSourceContextSubstitutionTree_valid.
Check rawRestrictedPADynamicSoundnessSubstitutionTree.
Check rawRestrictedPADynamicSoundnessSubstitutionTree_valid.
Check raw_codedRestrictedPADynamicSoundnessSource_substitution.

Print Assumptions rawRestrictedPADynamicSourceContextSubstitutionTree_valid.
Print Assumptions rawRestrictedPADynamicSoundnessSubstitutionTree_valid.
Print Assumptions raw_codedRestrictedPADynamicSoundnessSource_substitution.
