From BoundedPAConsistency Require Import
  RawCodedScopedFormulaDiagonalSubstitution.

Import PABoundedRawCodedScopedFormulaDiagonalSubstitution.

Check StandardTermScoped.
Check StandardFormulaScoped.
Check raw_codedTermOpening_standard_identity_below.
Check raw_codedFormulaSubstitutionAtom_standard_identity_below.
Check raw_codedFormulaDiagonalSubstitution_standard_scoped.
Check raw_codedFormulaDiagonalSubstitution_standard_positive.
Check raw_codedFormulaDiagonalSubstitution_standard_closed.

Print Assumptions raw_codedTermOpening_standard_identity_below.
Print Assumptions raw_codedFormulaDiagonalSubstitution_standard_scoped.
Print Assumptions raw_codedFormulaDiagonalSubstitution_standard_positive.
Print Assumptions raw_codedFormulaDiagonalSubstitution_standard_closed.
