From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyShiftRealization.

Import PABoundedRawCodedRestrictedPAConsistencyShiftRealization.

Check restrictedPAProofAssumptionFormulaContext.
Check restrictedPAProofAfterWitnessFormulaContext.
Check restrictedPAProofAfterProofFormulaContext.
Check restrictedPAProofAssumptionFormulaContext_shift_supported.
Check rawRestrictedPAProofAssumptionIteratedShiftCode.
Check rawRestrictedPAProofAfterWitnessIteratedShiftCode.
Check rawRestrictedPAProofAfterProofIteratedShiftCode.
Check raw_restrictedPAFormulaShiftOrbit_realized.
Check raw_restrictedPAExistentialDescentContexts_realized.

Print Assumptions
  restrictedPAProofAssumptionFormulaContext_shift_supported.
Print Assumptions raw_restrictedPAFormulaShiftOrbit_realized.
Print Assumptions raw_restrictedPAExistentialDescentContexts_realized.
