(** Public surface and assumption audit for the transparent target-code graph. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyFormulaCode.

Import PABoundedRawCodedRestrictedPAConsistencyFormulaCode.

Check rawTargetTermEqb.
Check restrictedPAConsistencyLevelMarker.
Check RestrictedPAConsistencyLevelMarkerExact.
Check rawMarkedTermCode.
Check rawMarkedFormulaCode.
Check RawMarkedFormulaCodeAt.
Check raw_markedFormulaCodeAt_total.
Check RawRestrictedPAConsistencyFormulaCodeAt.
Check raw_restrictedPAConsistencyFormulaCodeAt_total.
Check RestrictedPAConsistencyFormulaCodeGraphRepresentation.
Check restrictedPAConsistencyFormulaCodeGraphTotalityFormula.
Check restrictedPAConsistencyFormulaCodeGraphTotalityFormula_sentence.
Check PA_proves_restrictedPAConsistencyFormulaCodeGraphTotality_of_representation.
Check RawNumeralTermCodeAtFunctional.
Check raw_restrictedPAConsistencyFormulaCodeAt_functional_of_numeral.
Check raw_numeralTermCodeAt_standard_output.
Check raw_numeralTermCodeAt_standard.
Check raw_markedFormulaCodeAt_standard.
Check raw_restrictedPAConsistencyFormulaCodeAt_standard_of_marker_exact.

Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_total.
Print Assumptions raw_markedFormulaCodeAt_standard.
Print Assumptions
  PA_proves_restrictedPAConsistencyFormulaCodeGraphTotality_of_representation.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_functional_of_numeral.
Print Assumptions raw_numeralTermCodeAt_standard_output.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_standard_of_marker_exact.
