(** Public surface and assumption audit for the transparent target-code graph. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyFormulaCode.

Import PABoundedRawCodedRestrictedPAConsistencyFormulaCode.

Check rawTargetTermEqb.
Check restrictedPAConsistencyLevelMarker.
Check rawMarkedTermCode.
Check rawMarkedFormulaCode.
Check RawMarkedFormulaCodeAt.
Check raw_markedFormulaCodeAt_total.
Check RestrictedTargetTermContext.
Check RestrictedTargetFormulaContext.
Check instantiateRestrictedTargetTermContext.
Check instantiateRestrictedTargetFormulaContext.
Check rawRestrictedTargetFormulaContextCode.
Check restrictedPAConsistencyFormulaContext.
Check restrictedPAConsistencyFormulaContext_instance_exact.
Check RawRestrictedPAConsistencyFormulaCodeAt.
Check raw_restrictedPAConsistencyFormulaCodeAt_total.
Check RestrictedPAConsistencyFormulaCodeGraphRepresentation.
Check restrictedPAConsistencyFormulaCodeGraphTotalityFormula.
Check restrictedPAConsistencyFormulaCodeGraphTotalityFormula_sentence.
Check PA_proves_restrictedPAConsistencyFormulaCodeGraphTotality_of_representation.
Check RawNumeralTermCodeAtFunctional.
Check RawNumeralTermCodeTablesAgreeAt.
Check numeralTermCodeTablesAgreeAtTermAt.
Check raw_sat_numeralTermCodeTablesAgreeAtTermAt_iff.
Check raw_numeralTermCodeTablesAgreeAt_zero.
Check raw_numeralTermCodeTablesAgreeAt_succ.
Check raw_numeralTermCodeAt_functional.
Check raw_restrictedPAConsistencyFormulaCodeAt_functional_of_numeral.
Check raw_restrictedPAConsistencyFormulaCodeAt_functional.
Check raw_numeralTermCodeAt_standard_output.
Check raw_numeralTermCodeAt_standard.
Check raw_markedFormulaCodeAt_standard.
Check raw_restrictedPAConsistencyFormulaCodeAt_standard.

Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_total.
Print Assumptions raw_markedFormulaCodeAt_standard.
Print Assumptions restrictedPAConsistencyFormulaContext_instance_exact.
Print Assumptions
  PA_proves_restrictedPAConsistencyFormulaCodeGraphTotality_of_representation.
Print Assumptions raw_numeralTermCodeAt_functional.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_functional_of_numeral.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_functional.
Print Assumptions raw_numeralTermCodeAt_standard_output.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_standard.
