(** Assumption audit for model-internal raw-proof syntax traversal. *)

From BoundedPAConsistency Require Import
  RawCodedProofTraversal.

Import PABoundedRawCodedProofTraversal.

Check rawProofCodeSupported.
Check proofCodeSupportedTermAt.
Check raw_sat_proofCodeSupportedTermAt_iff.

Check RawProofChildrenClosedCase.
Check proofChildrenClosedCaseTermAt.
Check raw_sat_proofAllChildrenClosedTermAt_iff.
Check raw_sat_proofChildrenClosedCaseTermAt_iff.
Check raw_sat_proofChildrenCasesClosedTermAt_iff.

Check RawProofConstructorClosed.
Check proofConstructorClosedTermAt.
Check raw_sat_proofConstructorClosedTermAt_iff.
Check RawProofSyntaxStep.
Check proofSyntaxStepTermAt.
Check raw_sat_proofSyntaxStepTermAt_iff.

Check RawProofSyntaxTraversal.
Check proofSyntaxTraversalTermAt.
Check raw_sat_proofSyntaxTraversalTermAt_iff.
Check RawProofSyntaxCertificateWithSupport.
Check proofSyntaxCertificateWithSupportTermAt.
Check raw_sat_proofSyntaxCertificateWithSupportTermAt_iff.
Check RawProofSyntaxRealizable.
Check proofSyntaxRealizableTermAt.
Check raw_sat_proofSyntaxRealizableTermAt_iff.

Check raw_proofSyntaxStep_constructor_exists.
Check raw_proofSyntaxStep_closes_constructor.
Check raw_proofSyntaxStep_constructor_descent.
Check raw_proofConstructorClosed_recursive_child.
Check raw_proofSyntaxTraversal_supported_occurrence.
Check raw_proofSyntaxTraversal_closes_constructor.
Check raw_proofSyntaxTraversal_recursive_child.
Check raw_proofSyntaxTraversal_weaken.
Check raw_proofSyntaxCertificate_root_occurrence.
Check raw_proofSyntaxCertificate_recursive_child.
Check raw_proofSyntaxCertificates_cross_constructor.
Check raw_proofSyntaxCertificates_cross_recursive_child.

Check RawProofConstructorOccurrence.
Check proofConstructorOccurrenceTermAt.
Check raw_sat_proofConstructorOccurrenceTermAt_iff.
Check RawProofConstructorOccurrenceTotalityFor.
Check raw_proofConstructorOccurrence_totality_for_syntax.
Check proofSyntaxOccurrenceTotalityFormula.
Check raw_sat_proofSyntaxOccurrenceTotalityFormula_iff.
Check proofSyntaxOccurrenceTotalityFormula_sentence.
Check proofSyntaxOccurrenceTotalityFormula_raw_valid.
Check PA_proves_proofSyntaxOccurrenceTotalityFormula.

Print Assumptions raw_sat_proofCodeSupportedTermAt_iff.
Print Assumptions raw_sat_proofAllChildrenClosedTermAt_iff.
Print Assumptions raw_sat_proofChildrenClosedCaseTermAt_iff.
Print Assumptions raw_sat_proofChildrenCasesClosedTermAt_iff.
Print Assumptions raw_sat_proofConstructorClosedTermAt_iff.
Print Assumptions raw_sat_proofSyntaxStepTermAt_iff.
Print Assumptions raw_sat_proofSyntaxTraversalTermAt_iff.
Print Assumptions
  raw_sat_proofSyntaxCertificateWithSupportTermAt_iff.
Print Assumptions raw_sat_proofSyntaxRealizableTermAt_iff.

Print Assumptions raw_proofConstructorClosed_recursive_child.
Print Assumptions raw_proofSyntaxTraversal_supported_occurrence.
Print Assumptions raw_proofSyntaxTraversal_recursive_child.
Print Assumptions raw_proofSyntaxTraversal_weaken.
Print Assumptions raw_proofSyntaxCertificate_recursive_child.
Print Assumptions raw_proofSyntaxCertificates_cross_constructor.
Print Assumptions raw_proofSyntaxCertificates_cross_recursive_child.

Print Assumptions raw_sat_proofConstructorOccurrenceTermAt_iff.
Print Assumptions raw_proofConstructorOccurrence_totality_for_syntax.
Print Assumptions raw_sat_proofSyntaxOccurrenceTotalityFormula_iff.
Print Assumptions proofSyntaxOccurrenceTotalityFormula_sentence.
Print Assumptions proofSyntaxOccurrenceTotalityFormula_raw_valid.
Print Assumptions PA_proves_proofSyntaxOccurrenceTotalityFormula.
