(** Assumption audit for arbitrary-model rank-zero truth realization. *)

From BoundedPAConsistency Require Import
  RawCodedRankZeroTruthRealization.

Import PABoundedRawCodedRankZeroTruthRealization.

Check RawRankZeroSyntaxWitnessRow.
Check rankZeroSyntaxWitnessRowTermAt.
Check raw_sat_rankZeroSyntaxWitnessRowTermAt_iff.
Check RawRankZeroSyntaxTraversal.
Check rankZeroSyntaxTraversalTermAt.
Check raw_sat_rankZeroSyntaxTraversalTermAt_iff.

Check RawRankZeroSyntaxTermAdequate.
Check rankZeroSyntaxTermAdequateTermAt.
Check raw_sat_rankZeroSyntaxTermAdequateTermAt_iff.
Check RawRankZeroSyntaxCertificateWithSupport.
Check rankZeroSyntaxCertificateWithSupportTermAt.
Check raw_sat_rankZeroSyntaxCertificateWithSupportTermAt_iff.
Check RawRankZeroSyntaxRealizable.
Check rankZeroSyntaxRealizableTermAt.
Check raw_sat_rankZeroSyntaxRealizableTermAt_iff.

Check RawRankZeroAtomicTermCapacity.
Check raw_rankZeroTruthClosedStep_output_bit.
Check raw_rankZeroSyntaxStep_truth_exists.
Check raw_rankZeroTruthClosedStep_beta_extend.

Check RawRankZeroTruthCodingStep.
Check raw_sat_rankZeroTruthCodingStepTermAt_iff.
Check raw_rankZeroTruthCodingStep_exists.
Check RawRankZeroTruthTableCapacity.
Check raw_rankZeroTruthTableCapacity_of_codingStep.
Check raw_rankZeroTruthTableCapacity_exists.

Check RawRankZeroTruthPrefixRealized.
Check rankZeroTruthPrefixRealizedTermAt.
Check raw_sat_rankZeroTruthPrefixRealizedTermAt_iff.
Check raw_rankZeroTruthPrefixRealized_succ.
Check RawRankZeroTruthPrefixRealizedThrough.
Check rankZeroTruthPrefixRealizedThroughTermAt.
Check raw_sat_rankZeroTruthPrefixRealizedThroughTermAt_iff.
Check raw_rankZeroTruthPrefixRealized_through_all.

Check raw_rankZeroTruthCertificateWithTables_exists_of_syntax_capacity.
Check raw_rankZeroTruthCertificate_exists_of_syntax_capacity.
Check raw_rankZeroTruthCertificate_exists_unique_of_syntax_capacity.
Check RawRankZeroTruthAdmissible.
Check raw_rankZeroTruthCertificate_totality_for_admissible.

Print Assumptions raw_sat_rankZeroSyntaxWitnessRowTermAt_iff.
Print Assumptions raw_sat_rankZeroSyntaxTraversalTermAt_iff.
Print Assumptions raw_sat_rankZeroSyntaxTermAdequateTermAt_iff.
Print Assumptions raw_sat_rankZeroSyntaxCertificateWithSupportTermAt_iff.
Print Assumptions raw_sat_rankZeroSyntaxRealizableTermAt_iff.
Print Assumptions raw_rankZeroTruthClosedStep_output_bit.
Print Assumptions raw_rankZeroSyntaxStep_truth_exists.
Print Assumptions raw_rankZeroTruthClosedStep_beta_extend.
Print Assumptions raw_sat_rankZeroTruthCodingStepTermAt_iff.
Print Assumptions raw_rankZeroTruthCodingStep_exists.
Print Assumptions raw_rankZeroTruthTableCapacity_exists.
Print Assumptions raw_sat_rankZeroTruthPrefixRealizedTermAt_iff.
Print Assumptions raw_rankZeroTruthPrefixRealized_succ.
Print Assumptions raw_sat_rankZeroTruthPrefixRealizedThroughTermAt_iff.
Print Assumptions raw_rankZeroTruthPrefixRealized_through_all.
Print Assumptions
  raw_rankZeroTruthCertificateWithTables_exists_of_syntax_capacity.
Print Assumptions raw_rankZeroTruthCertificate_exists_of_syntax_capacity.
Print Assumptions
  raw_rankZeroTruthCertificate_exists_unique_of_syntax_capacity.
Print Assumptions raw_rankZeroTruthCertificate_totality_for_admissible.
