(** Assumption audit for nonstandard coded-term realization. *)

From BoundedPAConsistency Require Import
  RawCodedTermEvaluationRealization.

Import PABoundedRawCodedTermEvaluationRealization.

Check RawTermSyntaxWitnessRow.
Check termSyntaxWitnessRowTermAt.
Check raw_sat_termSyntaxWitnessRowTermAt_iff.
Check RawTermSyntaxTraversal.
Check termSyntaxTraversalTermAt.
Check raw_sat_termSyntaxTraversalTermAt_iff.

Check RawTermSyntaxAssignmentAdequate.
Check termSyntaxAssignmentAdequateTermAt.
Check raw_sat_termSyntaxAssignmentAdequateTermAt_iff.
Check RawTermSyntaxCertificateWithSupport.
Check termSyntaxCertificateWithSupportTermAt.
Check raw_sat_termSyntaxCertificateWithSupportTermAt_iff.
Check RawTermSyntaxRealizable.
Check termSyntaxRealizableTermAt.
Check raw_sat_termSyntaxRealizableTermAt_iff.

Check raw_termSyntaxStep_evaluation_exists.
Check raw_termEvaluationClosedStep_beta_extend.
Check RawTermEvaluationFixedStepCapacity.
Check RawTermEvaluationRealizationCapacity.
Check raw_termEvaluationTraversal_beta_extend.

Check RawTermEvaluationPrefixRealized.
Check termEvaluationPrefixRealizedTermAt.
Check raw_sat_termEvaluationPrefixRealizedTermAt_iff.
Check raw_termEvaluationPrefixRealized_succ.
Check RawTermEvaluationPrefixRealizedThrough.
Check termEvaluationPrefixRealizedThroughTermAt.
Check raw_sat_termEvaluationPrefixRealizedThroughTermAt_iff.
Check raw_termEvaluationPrefixRealized_through_all.

Check raw_termEvaluationCertificateWithTables_exists_of_syntax_capacity.
Check raw_termEvaluationCertificate_exists_of_syntax_capacity.
Check raw_termEvaluationCertificate_exists_unique_of_syntax_capacity.

Print Assumptions raw_sat_termSyntaxWitnessRowTermAt_iff.
Print Assumptions raw_sat_termSyntaxTraversalTermAt_iff.
Print Assumptions raw_sat_termSyntaxAssignmentAdequateTermAt_iff.
Print Assumptions raw_sat_termSyntaxCertificateWithSupportTermAt_iff.
Print Assumptions raw_sat_termSyntaxRealizableTermAt_iff.
Print Assumptions raw_termSyntaxStep_evaluation_exists.
Print Assumptions raw_termEvaluationClosedStep_beta_extend.
Print Assumptions raw_termEvaluationPrefixRealized_succ.
Print Assumptions raw_sat_termEvaluationPrefixRealizedThroughTermAt_iff.
Print Assumptions raw_termEvaluationPrefixRealized_through_all.
Print Assumptions
  raw_termEvaluationCertificateWithTables_exists_of_syntax_capacity.
Print Assumptions raw_termEvaluationCertificate_exists_of_syntax_capacity.
Print Assumptions
  raw_termEvaluationCertificate_exists_unique_of_syntax_capacity.
