(** Assumption audit for globally closed fixed-level truth traversals.

    The formula constructors have exact semantics in arbitrary raw models.
    Structural functionality and realization use only the existing PA-model
    interface.  Positive-level schedule realization is printed merely as a
    definition of the remaining obligation; it is not assumed by any theorem
    audited below. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthTraversal.

Import PABoundedRawCodedFixedLevelTruthTraversal.

Check raw_fixedTruthTraversal_eval_liftTerm_five.
Check raw_fixedTruthTraversal_eval_liftTerm_ten.
Check raw_fixedLevelStateLookup_functional.

Check fixedLevelClosedZeroRowTermAt.
Check RawFixedLevelClosedZeroRow.
Check raw_sat_fixedLevelClosedZeroRowTermAt_iff.
Check fixedLevelClosedSuccessorRowTermAt.
Check RawFixedLevelClosedSuccessorRow.
Check raw_sat_fixedLevelClosedSuccessorRowTermAt_iff.

Check fixedLevelZeroTruthTraversalRowsTermAt.
Check RawFixedLevelZeroTruthTraversalRows.
Check raw_sat_fixedLevelZeroTruthTraversalRowsTermAt_iff.
Check fixedLevelSuccessorTruthTraversalRowsTermAt.
Check RawFixedLevelSuccessorTruthTraversalRows.
Check raw_sat_fixedLevelSuccessorTruthTraversalRowsTermAt_iff.

Check fixedLevelZeroTruthTraversalTermAt.
Check RawFixedLevelZeroTruthTraversal.
Check raw_sat_fixedLevelZeroTruthTraversalTermAt_iff.
Check fixedLevelSuccessorTruthTraversalTermAt.
Check RawFixedLevelSuccessorTruthTraversal.
Check raw_sat_fixedLevelSuccessorTruthTraversalTermAt_iff.

Check fixedLevelSigmaTruthCertificateTermAt.
Check fixedLevelPiFalsityCertificateTermAt.
Check RawFixedLevelSigmaTruthCertificate.
Check RawFixedLevelPiFalsityCertificate.
Check raw_sat_fixedLevelTruthCertificateTermAt_iff.
Check raw_sat_fixedLevelSigmaTruthCertificateTermAt_iff.
Check raw_sat_fixedLevelPiFalsityCertificateTermAt_iff.

Check raw_fixedLevelZeroTruthTraversal_row_exists_unique.
Check raw_fixedLevelSuccessorTruthTraversal_row_exists_unique.
Check raw_fixedLevelZeroTruthTraversal_root_row.
Check raw_fixedLevelSuccessorTruthTraversal_root_row.
Check raw_fixedLevelSuccessorTruthTraversal_closes_earlier.
Check raw_fixedLevelZeroTruthTraversal_restrict_to_row.
Check raw_fixedLevelSuccessorTruthTraversal_restrict_to_row.
Check raw_fixedLevelSigmaTruthCertificate_domain.
Check raw_fixedLevelPiFalsityCertificate_domain.
Check raw_fixedLevelGlobalAssemblyFor_closed_certificates.

Check raw_fixedLevelClosedZeroRow_singleton_traversal.
Check raw_fixedLevelSigmaTruthCertificate_zero_of_local.
Check raw_fixedLevelPiFalsityCertificate_zero_of_local.
Check RawFixedLevelZeroTruthAdmissible.
Check raw_fixedLevelTruthCertificate_zero_decides.

Check RawFixedLevelPositiveTruthScheduleRealizationFor.
Check RawFixedLevelTruthCertificateTotalityFor.
Check raw_fixedLevelTruthCertificate_totality_from_positive_schedule.

Print Assumptions raw_fixedLevelStateLookup_functional.
Print Assumptions raw_sat_fixedLevelClosedZeroRowTermAt_iff.
Print Assumptions raw_sat_fixedLevelClosedSuccessorRowTermAt_iff.
Print Assumptions raw_sat_fixedLevelZeroTruthTraversalRowsTermAt_iff.
Print Assumptions raw_sat_fixedLevelSuccessorTruthTraversalRowsTermAt_iff.
Print Assumptions raw_sat_fixedLevelZeroTruthTraversalTermAt_iff.
Print Assumptions raw_sat_fixedLevelSuccessorTruthTraversalTermAt_iff.
Print Assumptions raw_sat_fixedLevelTruthCertificateTermAt_iff.
Print Assumptions raw_sat_fixedLevelSigmaTruthCertificateTermAt_iff.
Print Assumptions raw_sat_fixedLevelPiFalsityCertificateTermAt_iff.
Print Assumptions raw_fixedLevelZeroTruthTraversal_row_exists_unique.
Print Assumptions raw_fixedLevelSuccessorTruthTraversal_row_exists_unique.
Print Assumptions raw_fixedLevelSuccessorTruthTraversal_closes_earlier.
Print Assumptions raw_fixedLevelZeroTruthTraversal_restrict_to_row.
Print Assumptions raw_fixedLevelSuccessorTruthTraversal_restrict_to_row.
Print Assumptions raw_fixedLevelSigmaTruthCertificate_domain.
Print Assumptions raw_fixedLevelPiFalsityCertificate_domain.
Print Assumptions raw_fixedLevelGlobalAssemblyFor_closed_certificates.
Print Assumptions raw_fixedLevelClosedZeroRow_singleton_traversal.
Print Assumptions raw_fixedLevelTruthCertificate_zero_decides.
Print Assumptions raw_fixedLevelTruthCertificate_totality_from_positive_schedule.
