(** Assumption audit for admissibility-guarded fixed-level lowering. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthAdmissibleLowering.

Import PABoundedRawCodedFixedLevelTruthAdmissibleLowering.

Check raw_codedAssignmentDefinedThrough_of_lt.
Check raw_codedFormulaAtomicallyAdequate_at_lookup.
Check raw_fixedLevelTruthAdmissible_child_core.
Check raw_codedAssignmentPrepend_child_defined.

Check raw_formulaZeroOccurrenceSupportPrefix_exists.
Check raw_formulaSyntaxTraversal_rankZeroSyntaxRealizable.
Check raw_fixedLevelTruthAdmissible_zeroSyntaxRealizable.

Check raw_fixedLevelOneRankZeroAgreementBelow_all.
Check raw_fixedLevelSigmaTruthCertificate_one_rankZero.
Check raw_fixedLevelPiFalsityCertificate_one_rankZero.
Check raw_fixedLevelSigmaTruthCertificate_one_lower.
Check raw_fixedLevelPiFalsityCertificate_one_lower.
Check raw_fixedLevelAdmissibleTruthCertificateCoherence_zero.

Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero_raw_valid.
Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero_closed.
Check fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero_closed_sentence.
Check PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero_closed.
Check PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero.

Print Assumptions raw_formulaZeroOccurrenceSupportPrefix_exists.
Print Assumptions raw_formulaSyntaxTraversal_rankZeroSyntaxRealizable.
Print Assumptions raw_fixedLevelTruthAdmissible_zeroSyntaxRealizable.
Print Assumptions raw_fixedLevelOneRankZeroAgreementBelow_all.
Print Assumptions raw_fixedLevelSigmaTruthCertificate_one_lower.
Print Assumptions raw_fixedLevelPiFalsityCertificate_one_lower.
Print Assumptions raw_fixedLevelAdmissibleTruthCertificateCoherence_zero.
Print Assumptions
  PA_proves_fixedLevelAdmissibleTruthCertificateCoherenceFormula_zero.
