(** Assumption audit for the beta-coded rank-zero truth traversal. *)

From BoundedPAConsistency Require Import RawCodedRankZeroTruthTraversal.

Import PABoundedRawCodedRankZeroTruthTraversal.

Check raw_sat_rankZeroEqCertifiedRowTermAt_iff.
Check raw_sat_rankZeroTruthClosedWitnessRowTermAt_iff.
Check raw_sat_rankZeroTruthClosedStepTermAt_iff.
Check raw_sat_rankZeroTruthTraversalTermAt_iff.
Check raw_sat_rankZeroTruthCertificateTermAt_iff.
Check raw_sat_rankZeroTruthTablesAgreeBelowTermAt_iff.
Check raw_rankZeroTruthClosedStep_extensional.
Check raw_rankZeroTruthTraversals_agree_below.
Check raw_rankZeroTruthCertificate_output_functional.
Check raw_rankZeroTruthCertificate_root_closed_step.
Check raw_sat_rankZeroTruthCertificateTermAt_functional.
Check PA_proves_rankZeroTruthCertificateFunctionalFormula.
Check raw_rankZeroTruthTables_append_exists.
Check RawRankZeroTruthCertificateTotalityFor.

Print Assumptions raw_sat_rankZeroEqCertifiedRowTermAt_iff.
Print Assumptions raw_sat_rankZeroTruthClosedWitnessRowTermAt_iff.
Print Assumptions raw_sat_rankZeroTruthClosedStepTermAt_iff.
Print Assumptions raw_sat_rankZeroTruthTraversalTermAt_iff.
Print Assumptions raw_sat_rankZeroTruthCertificateTermAt_iff.
Print Assumptions raw_sat_rankZeroTruthTablesAgreeBelowTermAt_iff.
Print Assumptions raw_rankZeroTruthClosedStep_extensional.
Print Assumptions raw_rankZeroTruthTraversals_agree_below.
Print Assumptions raw_rankZeroTruthCertificate_output_functional.
Print Assumptions raw_rankZeroTruthCertificate_root_closed_step.
Print Assumptions raw_sat_rankZeroTruthCertificateTermAt_functional.
Print Assumptions PA_proves_rankZeroTruthCertificateFunctionalFormula.
Print Assumptions raw_rankZeroTruthTables_append_exists.
