From BoundedPAConsistency Require Import
  RawCodedRestrictedProofCoveredSoundness.

Import PABoundedRawCodedRestrictedProofCoveredSoundness.

Check RawRestrictedProofCoveredRecursiveChildrenSigmaSound.
Check RawRestrictedProofCoveredRuleTruthSound.
Check RawRestrictedProofCoveredSigmaSoundBelow.
Check raw_sat_restrictedProofCoveredSigmaSoundBelowTermAt_iff.
Check raw_restrictedProofCoveredSigmaSoundBelow_zero.
Check raw_restrictedProofCoveredSigmaSoundBelow_succ.
Check raw_restrictedProofCoveredSigmaSoundBelow_all.
Check raw_restrictedProofCovered_root_sigma_sound.
Check raw_restrictedProofCovered_bottom_exclusion.

Print Assumptions raw_sat_restrictedProofCoveredSigmaSoundBelowTermAt_iff.
Print Assumptions raw_restrictedProofCoveredSigmaSoundBelow_all.
Print Assumptions raw_restrictedProofCovered_bottom_exclusion.
