From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyTripleExDescent.

Import PABoundedRawCodedRestrictedPAConsistencyTripleExDescent.

Check rawRestrictedPAOpenRootContextCode.
Check rawRestrictedPAAfterWitnessContextCode.
Check rawRestrictedPAAfterProofContextCode.
Check rawRestrictedPAFieldsContextCode.
Check RawRestrictedPAExistentialDescentContexts.
Check rawRestrictedPAThirdExERoot.
Check rawRestrictedPASecondExERoot.
Check rawRestrictedPATripleExERoot.
Check raw_codedPAOpenProofOf_bottom_of_restrictedPA_fields.
Check RawRestrictedPAConsistencyFieldRefutationCompiler.
Check RawRestrictedPAConsistencyFieldRefutationCompilerInAllModels.
Check raw_restrictedPAConsistencyOpenCompiler_of_fieldRefutation.
Check raw_restrictedPAConsistencyOpenCompilerInAllModels_of_fieldRefutation.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_fieldRefutation.

Print Assumptions
  raw_codedPAOpenProofOf_bottom_of_restrictedPA_fields.
Print Assumptions
  raw_restrictedPAConsistencyOpenCompiler_of_fieldRefutation.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_fieldRefutation.
