(** Assumption audit for represented positive/all-level formula-shift
    Tarski transport. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthOperationTarskiPositive.

Import PABoundedRawCodedFixedLevelTruthOperationTarskiPositive.

Check codedFormulaShiftAssignmentLocalCompatibilityTermAt.
Check raw_sat_codedFormulaShiftAssignmentLocalCompatibilityTermAt_iff.
Check raw_formulaShiftEqOperationRow_rankZero_outputs_agree_local.
Check raw_formulaShiftEqOperationRow_scheduled_transport.
Check formulaShiftScheduledTransportBelowTermAt.
Check raw_sat_formulaShiftScheduledTransportBelowTermAt_iff.
Check raw_formulaShiftScheduledTransportBelow_succ.
Check raw_formulaShiftScheduledTransportBelow_all.
Check raw_formulaShiftOperationTrace_scheduled_transport.
Check raw_fixedLevelFormulaShiftTarskiStep_scheduled.
Check raw_fixedLevelFormulaShiftTarskiStep_all.
Check fixedLevelFormulaShiftTarskiStepFormula.
Check PA_proves_fixedLevelFormulaShiftTarskiStepFormula.

Print Assumptions raw_formulaShiftEqOperationRow_scheduled_transport.
Print Assumptions raw_formulaShiftScheduledTransportBelow_succ.
Print Assumptions raw_formulaShiftScheduledTransportBelow_all.
Print Assumptions raw_fixedLevelFormulaShiftTarskiStep_scheduled.
Print Assumptions raw_fixedLevelFormulaShiftTarskiStep_all.
Print Assumptions PA_proves_fixedLevelFormulaShiftTarskiStepFormula.
