From BoundedPAConsistency Require Import RawCodedPAAxiomTruth.

Import PABoundedRawCodedPAAxiomTruth.

Check RawFixedLevelPAAxiomInductionSigmaSound.
Check raw_standardZeroAssignment_represents.
Check raw_codedPAAxiomFiniteWitness_sigma_zero.
Check raw_codedPAAxiomInduction_standard_sigma_zero.
Check raw_codedPAAxiomWitness_sigma_zero.
Check RawContextAllFixedLevelAdmissibleWithTables.
Check raw_codedPAAxiomWitnessContextWithTables_sigma_zero.
Check RawCodedPAAxiomWitnessContextAdmissible.
Check raw_contextAllAtomicallyAdequate_member.
Check raw_contextAllBounded_member.
Check raw_codedPAAxiomWitnessContext_admissible_of_bounded_atomic.
Check raw_codedPAAxiomWitnessContext_sigma_zero.
Check raw_codedPAAxiomWitnessContext_sigma_zero_of_bounded_atomic.

Print Assumptions raw_codedPAAxiomFiniteWitness_sigma_zero.
Print Assumptions raw_codedPAAxiomInduction_standard_sigma_zero.
Print Assumptions raw_codedPAAxiomWitness_sigma_zero.
Print Assumptions raw_codedPAAxiomWitnessContextWithTables_sigma_zero.
Print Assumptions
  raw_codedPAAxiomWitnessContext_admissible_of_bounded_atomic.
Print Assumptions raw_codedPAAxiomWitnessContext_sigma_zero.
Print Assumptions
  raw_codedPAAxiomWitnessContext_sigma_zero_of_bounded_atomic.
