(** Assumption audit for fixed-truth traversal concatenation primitives. *)

From BoundedPAConsistency Require Import RawCodedFixedLevelTruthConcatenation.

Import PABoundedRawCodedFixedLevelTruthConcatenation.

Check RawFixedLevelPositiveTraversalBundle.
Check fixedLevelPositiveTraversalBundleTermAt.
Check raw_sat_fixedLevelPositiveTraversalBundleTermAt_iff.
Check RawFixedLevelTraversalCopyState.
Check fixedLevelTraversalCopyStateTermAt.
Check raw_sat_fixedLevelTraversalCopyStateTermAt_iff.
Check raw_add_zero_right_fixedTruthConcat.
Check raw_fixedLevelStateOffsetEmbedding_zero.
Check raw_fixedLevelTraversalCopyState_zero.
Check raw_fixedLevelTraversalCopyState_succ.
Check raw_fixedLevelTraversalCopyState_all.
Check raw_fixedLevelSuccessorTruthTraversals_concatenate.
Check raw_fixedLevelPositiveTraversalBundle_of_traversal.
Check raw_fixedLevelPositiveTraversalBundle_append.

Print Assumptions raw_fixedLevelPositiveTraversalBundle_of_traversal.
Print Assumptions raw_sat_fixedLevelPositiveTraversalBundleTermAt_iff.
Print Assumptions raw_sat_fixedLevelTraversalCopyStateTermAt_iff.
Print Assumptions raw_fixedLevelTraversalCopyState_zero.
Print Assumptions raw_fixedLevelTraversalCopyState_succ.
Print Assumptions raw_fixedLevelTraversalCopyState_all.
Print Assumptions raw_fixedLevelSuccessorTruthTraversals_concatenate.
Print Assumptions raw_fixedLevelPositiveTraversalBundle_append.
