(** Assumption audit for pointwise fixed-level truth of coded contexts. *)

From BoundedPAConsistency Require Import RawCodedFixedLevelContextTruth.

Import PABoundedRawCodedFixedLevelContextTruth.

Check RawContextAllSigmaTrueWithTables.
Check contextAllSigmaTrueWithTablesTermAt.
Check raw_sat_contextAllSigmaTrueWithTablesTermAt_iff.

Check RawContextAllSigmaTrue.
Check contextAllSigmaTrueTermAt.
Check raw_sat_contextAllSigmaTrueTermAt_iff.
Check raw_contextAllSigmaTrue_realizable.
Check raw_contextAllSigmaTrueWithTables_member.
Check raw_contextAllSigmaTrue_member.
Check raw_contextAllSigmaTrue_empty.
Check raw_contextAllSigmaTrue_cons.

Print Assumptions raw_sat_contextAllSigmaTrueWithTablesTermAt_iff.
Print Assumptions raw_sat_contextAllSigmaTrueTermAt_iff.
Print Assumptions raw_contextAllSigmaTrue_realizable.
Print Assumptions raw_contextAllSigmaTrueWithTables_member.
Print Assumptions raw_contextAllSigmaTrue_member.
Print Assumptions raw_contextAllSigmaTrue_empty.
Print Assumptions raw_contextAllSigmaTrue_cons.
