(** Assumption audit for the beta-coded global term-evaluation traversal. *)

From BoundedPAConsistency Require Import RawCodedTermEvaluationTraversal.

Import PABoundedRawCodedTermEvaluationTraversal.

Check raw_sat_termEvaluationClosedWitnessRowTermAt_iff.
Check raw_sat_termEvaluationClosedStepTermAt_iff.
Check raw_sat_termEvaluationTraversalTermAt_iff.
Check raw_sat_termEvaluationCertificateTermAt_iff.
Check raw_sat_termEvaluationTablesAgreeBelowTermAt_iff.
Check raw_termEvaluationClosedStep_extensional.
Check raw_termEvaluationTraversals_agree_below.
Check raw_termEvaluationCertificate_value_functional.
Check raw_sat_termEvaluationCertificateTermAt_functional.
Check PA_proves_termEvaluationCertificateFunctionalFormula.
Check raw_termEvaluationTables_append_exists.

Print Assumptions raw_sat_termEvaluationClosedWitnessRowTermAt_iff.
Print Assumptions raw_sat_termEvaluationClosedStepTermAt_iff.
Print Assumptions raw_sat_termEvaluationTraversalTermAt_iff.
Print Assumptions raw_sat_termEvaluationCertificateTermAt_iff.
Print Assumptions raw_sat_termEvaluationTablesAgreeBelowTermAt_iff.
Print Assumptions raw_termEvaluationClosedStep_extensional.
Print Assumptions raw_termEvaluationTraversals_agree_below.
Print Assumptions raw_termEvaluationCertificate_value_functional.
Print Assumptions raw_sat_termEvaluationCertificateTermAt_functional.
Print Assumptions PA_proves_termEvaluationCertificateFunctionalFormula.
Print Assumptions raw_termEvaluationTables_append_exists.
