(** Audit the PA-definable positive-level assignment-locality theorem. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthAssignmentInvariancePositive.

Import PABoundedRawCodedFixedLevelTruthAssignmentInvariancePositive.

Check raw_codedAssignmentPrepends_agree_of_sources.

Check fixedLevelTruthAssignmentTransportBelowTermAt.
Check RawFixedLevelTruthAssignmentTransportBelow.
Check raw_sat_fixedLevelTruthAssignmentTransportBelowTermAt_iff.
Check raw_fixedLevelTruthAssignmentTransportBelow_zero.
Check raw_fixedLevelTruthCertificateTransport_of_sigma_iff.
Check raw_fixedLevelSigmaTruthCertificate_assignment_transport_shape.
Check raw_fixedLevelTruthAssignmentTransportBelow_succ.
Check raw_fixedLevelTruthAssignmentTransportBelow_all.
Check raw_fixedLevelTruthCertificate_assignment_invariance.

Print Assumptions raw_codedAssignmentPrepends_agree_of_sources.
Print Assumptions raw_sat_fixedLevelTruthAssignmentTransportBelowTermAt_iff.
Print Assumptions raw_fixedLevelSigmaTruthCertificate_assignment_transport_shape.
Print Assumptions raw_fixedLevelTruthAssignmentTransportBelow_all.
Print Assumptions raw_fixedLevelTruthCertificate_assignment_invariance.
