(** Assumption audit for the discharged term-evaluation capacity seam. *)

From BoundedPAConsistency Require Import
  RawCodedTermEvaluationCapacity.

Import PABoundedRawCodedTermEvaluationCapacity.

Check RawTermEvaluationCodingStep.
Check raw_sat_termEvaluationCodingStepTermAt_iff.
Check raw_termEvaluationCodingStep_exists.
Check raw_termEvaluationCodingStep_old_of_sum.
Check raw_termEvaluationCodingStep_value_bound.

Check RawTermEvaluationTraceCapacity.
Check termEvaluationTraceCapacityTermAt.
Check raw_sat_termEvaluationTraceCapacityTermAt_iff.
Check raw_termEvaluationTraceCapacity_zero.
Check raw_termEvaluation_next_value_independent.
Check raw_termEvaluationTraceCapacity_succ.

Check RawTermEvaluationTraceCapacityThrough.
Check termEvaluationTraceCapacityThroughTermAt.
Check raw_sat_termEvaluationTraceCapacityThroughTermAt_iff.
Check raw_termEvaluationTraceCapacity_through_all.
Check raw_termEvaluationTraversal_exists_of_syntax.

Check raw_termEvaluationTraversal_restrict.
Check raw_codedAssignmentLookup_lt_betaModulus.
Check raw_termEvaluationFixedStepCapacity_of_complete_traversal.
Check raw_termEvaluationRealizationCapacity_of_syntax.
Check raw_termEvaluationRealizationCapacity_of_certificate.
Check raw_termEvaluationCertificate_exists_of_syntax.
Check raw_termEvaluationCertificate_exists_unique_of_syntax.

Print Assumptions raw_sat_termEvaluationCodingStepTermAt_iff.
Print Assumptions raw_termEvaluationCodingStep_exists.
Print Assumptions raw_termEvaluationCodingStep_old_of_sum.
Print Assumptions raw_termEvaluationCodingStep_value_bound.
Print Assumptions raw_sat_termEvaluationTraceCapacityTermAt_iff.
Print Assumptions raw_termEvaluationTraceCapacity_zero.
Print Assumptions raw_termEvaluation_next_value_independent.
Print Assumptions raw_termEvaluationTraceCapacity_succ.
Print Assumptions raw_sat_termEvaluationTraceCapacityThroughTermAt_iff.
Print Assumptions raw_termEvaluationTraceCapacity_through_all.
Print Assumptions raw_termEvaluationTraversal_exists_of_syntax.
Print Assumptions raw_termEvaluationTraversal_restrict.
Print Assumptions raw_codedAssignmentLookup_lt_betaModulus.
Print Assumptions raw_termEvaluationFixedStepCapacity_of_complete_traversal.
Print Assumptions raw_termEvaluationRealizationCapacity_of_syntax.
Print Assumptions raw_termEvaluationRealizationCapacity_of_certificate.
Print Assumptions raw_termEvaluationCertificate_exists_of_syntax.
Print Assumptions raw_termEvaluationCertificate_exists_unique_of_syntax.
