From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyOpenCompiler.

Import PABoundedRawCodedRestrictedPAConsistencyOpenCompiler.

Check rawRestrictedPAProofAssumptionCode.
Check raw_restrictedPAConsistencyTargetCode_view.
Check raw_restrictedPAConsistencyFormulaCodeAt_open_view.
Check RawRestrictedPAConsistencyOpenContradictionCompiler.
Check RawRestrictedPAConsistencyOpenContradictionCompilerInAllModels.
Check raw_restrictedPAConsistencyCertificateSuccessor_of_openCompiler.
Check
  raw_restrictedPAConsistencyCertificateSuccessorInAllModels_of_openCompiler.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_openCompiler.

Print Assumptions raw_restrictedPAConsistencyTargetCode_view.
Print Assumptions raw_restrictedPAConsistencyFormulaCodeAt_open_view.
Print Assumptions
  raw_restrictedPAConsistencyCertificateSuccessor_of_openCompiler.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_openCompiler.
