(** Assumption audit for proof-wide atomic-term adequacy. *)
From BoundedPAConsistency Require Import RawCodedProofAtomicAdequacy.

Import PABoundedRawCodedProofAtomicAdequacy.

Check RawContextAllAtomicallyAdequateWithTables.
Check raw_sat_contextAllAtomicallyAdequateWithTablesTermAt_iff.
Check RawContextAllAtomicallyAdequate.
Check raw_sat_contextAllAtomicallyAdequateTermAt_iff.
Check RawCodedTermUniversallyAdequate.
Check raw_sat_codedTermUniversallyAdequateTermAt_iff.
Check RawProofConstructorPayloadAtomicallyAdequate.
Check raw_sat_proofConstructorPayloadAtomicallyAdequateTermAt_iff.
Check RawProofConstructorPayloadsAtomicallyAdequate.
Check raw_sat_proofConstructorPayloadsAtomicallyAdequateTermAt_iff.
Check RawProofEndpointAtomicallyAdequate.
Check raw_sat_proofEndpointAtomicallyAdequateTermAt_iff.
Check RawProofAtomicAdequacyWithSupport.
Check raw_sat_proofAtomicAdequacyWithSupportTermAt_iff.
Check RawProofAtomicallyAdequate.
Check raw_sat_proofAtomicallyAdequateTermAt_iff.
Check raw_proofAtomicAdequacy_root_endpoint.
Check raw_proofAtomicallyAdequate_root_endpoint.
Check raw_proofAtomicAdequacy_root_constructor_payloads.
Check raw_proofAtomicallyAdequate_root_constructor_payloads.
Check raw_proofAtomicAdequacy_recursive_child.

Print Assumptions
  raw_sat_proofConstructorPayloadsAtomicallyAdequateTermAt_iff.
Print Assumptions raw_sat_proofAtomicallyAdequateTermAt_iff.
Print Assumptions raw_proofAtomicAdequacy_root_endpoint.
Print Assumptions raw_proofAtomicAdequacy_root_constructor_payloads.
Print Assumptions raw_proofAtomicAdequacy_recursive_child.
