From BoundedPAConsistency Require Import
  RawCodedRestrictedPADynamicSoundnessSource.

Import PABoundedRawCodedRestrictedPADynamicSoundnessSource.

Check restrictedPADynamicSourceTermContext.
Check restrictedPADynamicSourceFormulaContext.
Check restrictedPADynamicOccurrenceSourceFormula.
Check restrictedPADynamicSoundnessImplicationFormula.
Check restrictedPADynamicSoundnessSourceFormula.
Check rawRestrictedPADynamicSoundnessSourceCode.

Check standardTermOpening_after_shift_one.
Check standardFormulaSingleSubstitution_after_shift_one.
Check restrictedPADynamicSourceTermContext_substitute_numeral.
Check restrictedPADynamicSourceFormulaContext_substitute_numeral.
Check restrictedPADynamicOccurrenceContext_shift_supported.
Check restrictedPADynamicSoundnessSourceFormula_substitute_numeral.
Check raw_restrictedPADynamicSoundnessImplicationCode_standard.

Print Assumptions
  restrictedPADynamicSoundnessSourceFormula_substitute_numeral.
Print Assumptions raw_restrictedPADynamicSoundnessImplicationCode_standard.
