From BoundedPAConsistency Require Import
  RawCodedFormulaDiagonalOperationComposition.

Import PABoundedRawCodedFormulaDiagonalOperationComposition.

Check RawDiagonalFormulaOperationOffsetEmbedding.
Check raw_diagonalFormulaOperationTraversalRow_offset.
Check RawDiagonalFormulaOperationCopyState.
Check raw_sat_diagonalFormulaOperationCopyStateTermAt_iff.
Check raw_diagonalFormulaOperationCopyState_all.
Check raw_diagonalFormulaOperationTraces_concatenate.

Check raw_codedFormulaDiagonalOperation_eq.
Check raw_codedFormulaDiagonalOperation_bot.
Check raw_codedFormulaDiagonalOperation_binary.
Check raw_codedFormulaDiagonalOperation_imp.
Check raw_codedFormulaDiagonalOperation_and.
Check raw_codedFormulaDiagonalOperation_or.
Check raw_codedFormulaDiagonalOperation_ex.

Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_eq.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_bot.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_imp.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_and.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_or.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_all.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_ex.

Check RawCodedFormulaDiagonalSubstitutionAtPositiveDepths.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_all_of_positive.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_ex_of_positive.
Check raw_codedFormulaDiagonalSubstitutionAtAllDepths_inductionBody.

Print Assumptions raw_diagonalFormulaOperationTraces_concatenate.
Print Assumptions raw_codedFormulaDiagonalSubstitutionAtAllDepths_eq.
Print Assumptions
  raw_codedFormulaDiagonalSubstitutionAtAllDepths_inductionBody.
