(** Assumption audit for fixed-level formula-operation transport interfaces.

    The final Tarski-step objects below are represented implications, not
    assumed theorems.  The audit therefore prints assumptions only for exact
    semantics and the concrete assignment/domain/admissibility results. *)

From BoundedPAConsistency Require Import
  RawCodedFixedLevelTruthOperationTransport.

Import PABoundedRawCodedFixedLevelTruthOperationTransport.

Check codedFormulaShiftAssignmentRelationTermAt.
Check RawCodedFormulaShiftAssignmentRelation.
Check raw_sat_codedFormulaShiftAssignmentRelationTermAt_iff.
Check raw_codedFormulaUnitShiftAssignmentRelation_of_prepend.

Check codedFormulaSubstitutionAssignmentRelationTermAt.
Check RawCodedFormulaSubstitutionAssignmentRelation.
Check raw_sat_codedFormulaSubstitutionAssignmentRelationTermAt_iff.

Check codedFormulaRankAgreementTermAt.
Check RawCodedFormulaRankAgreement.
Check raw_sat_codedFormulaRankAgreementTermAt_iff.
Check raw_codedFormulaRankAgreement_of_operationRankPreserving.
Check raw_codedFormulaShift_rankAgreement.
Check raw_codedFormulaSingleSubstitution_rankAgreement.
Check raw_fixedLevel_domains_iff_of_rankAgreement.

Check codedFormulaTargetAdmissibilityDataTermAt.
Check RawCodedFormulaTargetAdmissibilityData.
Check raw_sat_codedFormulaTargetAdmissibilityDataTermAt_iff.
Check raw_fixedLevelTruthAdmissible_transport_of_rankAgreement.

Check fixedLevelTruthCertificateTransportTermAt.
Check RawFixedLevelTruthCertificateTransport.
Check raw_sat_fixedLevelTruthCertificateTransportTermAt_iff.

Check fixedLevelFormulaShiftTransportReadyTermAt.
Check RawFixedLevelFormulaShiftTransportReady.
Check raw_sat_fixedLevelFormulaShiftTransportReadyTermAt_iff.
Check raw_fixedLevelFormulaShiftTransportReady_target_admissible.
Check raw_fixedLevelFormulaShiftTransportReady_of_rankPreservation.

Check fixedLevelFormulaSubstitutionTransportReadyTermAt.
Check RawFixedLevelFormulaSubstitutionTransportReady.
Check raw_sat_fixedLevelFormulaSubstitutionTransportReadyTermAt_iff.
Check raw_fixedLevelFormulaSubstitutionTransportReady_target_admissible.
Check
  raw_fixedLevelFormulaSubstitutionTransportReady_of_rankPreservation.

Check fixedLevelFormulaShiftTarskiStepTermAt.
Check RawFixedLevelFormulaShiftTarskiStep.
Check raw_sat_fixedLevelFormulaShiftTarskiStepTermAt_iff.
Check fixedLevelFormulaSubstitutionTarskiStepTermAt.
Check RawFixedLevelFormulaSubstitutionTarskiStep.
Check raw_sat_fixedLevelFormulaSubstitutionTarskiStepTermAt_iff.

Print Assumptions
  raw_sat_codedFormulaShiftAssignmentRelationTermAt_iff.
Print Assumptions raw_codedFormulaUnitShiftAssignmentRelation_of_prepend.
Print Assumptions
  raw_sat_codedFormulaSubstitutionAssignmentRelationTermAt_iff.
Print Assumptions raw_sat_codedFormulaRankAgreementTermAt_iff.
Print Assumptions raw_codedFormulaRankAgreement_of_operationRankPreserving.
Print Assumptions raw_fixedLevel_domains_iff_of_rankAgreement.
Print Assumptions
  raw_sat_codedFormulaTargetAdmissibilityDataTermAt_iff.
Print Assumptions
  raw_fixedLevelTruthAdmissible_transport_of_rankAgreement.
Print Assumptions
  raw_sat_fixedLevelTruthCertificateTransportTermAt_iff.
Print Assumptions
  raw_sat_fixedLevelFormulaShiftTransportReadyTermAt_iff.
Print Assumptions
  raw_fixedLevelFormulaShiftTransportReady_target_admissible.
Print Assumptions
  raw_fixedLevelFormulaShiftTransportReady_of_rankPreservation.
Print Assumptions
  raw_sat_fixedLevelFormulaSubstitutionTransportReadyTermAt_iff.
Print Assumptions
  raw_fixedLevelFormulaSubstitutionTransportReady_target_admissible.
Print Assumptions
  raw_fixedLevelFormulaSubstitutionTransportReady_of_rankPreservation.
Print Assumptions raw_sat_fixedLevelFormulaShiftTarskiStepTermAt_iff.
Print Assumptions
  raw_sat_fixedLevelFormulaSubstitutionTarskiStepTermAt_iff.
