(* ===================================================================== *)
(*  PAHF/Audit.v                                                        *)
(*                                                                       *)
(*  Type-check the PA/HF interpretability surface and print assumptions. *)
(* ===================================================================== *)

From PAHF Require Import PAHF PAHFProofCalculus
  PAHFOrdinalCode PAHFTranslatedHFFin
  PAHFOrdinalCodeMulCore PAHFOrdinalCodeTermMul
  PAHFConcreteAssembly.

(* Canonical sentence invariant for the PA axiom theory. *)
Check PA.Formula.sentence_ax_s.

(* PA/HF translation and finite-HF bridge. *)
Check PA.Term.addRightNumeral.
Check PA.Term.mulRightNumeral.
Check PA.Term.rename_numeral.
Check PA.Term.subst_numeral.
Check PA.Term.subst_subst_numeral.
Check PA.Term.addRightNumeral_numeral.
Check PA.Term.subst_comp.
Check PA.Term.subst_rename_succ_up.
Check PA.Term.upSubst_comp.
Check PA.Term.subst_ext_free.
Check PA.Term.subst_id.
Check PA.Formula.Ax_s.
Check PA.Formula.sat_axiom_s.
Check PA.Formula.Sentences.
Check PA.Formula.rename_eq_of_sentence.
Check PA.Formula.term_subst_var_rename.
Check PA.Formula.term_subst_instTerm_var.
Check PA.Formula.subst_var_rename.
Check PA.Formula.subst_instTerm_var.
Check PA.Formula.subst_comp.
Check PA.Formula.subst_rename_succ_up.
Check PA.Formula.subst_ext_free.
Check PA.Formula.subst_id.
Check PA.Formula.subst_eq_of_sentence.
Check PA.Formula.term_subst_instTerm_rename_succ.
Check iterEx.
Check iterRenameContextSucc.
Check openedContext.
Check openedExContext.
Check BProv_context_prefix.
Check PA.Formula.BProv_context_two.
Check PA.Formula.BProv_context_three.
Check BProv_iterRenameSucc_of_sentences.
Check BProv_lift_openedContext_of_sentences.
Check BProv_iterExE_of_sentences.
Check subst_three_witnesses_rename_three_succ.
Print Assumptions BProv_iterExE_of_sentences.
Print Assumptions BProv_iterRenameSucc_of_sentences.
Check BProv_PA_iffForm_intro.
Check BProv_PA_iffForm_forward.
Check BProv_PA_iffForm_reverse.
Check BProv_PA_imp_trans.
Check BProv_PA_imp_mono.
Check BProv_PA_and_mono.
Check BProv_PA_or_mono.
Check BProv_PA_ex_mono_of_sentences.
Check BProv_PA_iffForm_ex_congr_of_sentences.
Check BProv_Ax_s_all_of_strongStep_under.
Check BProv_ordinalCodeGraphTermAt_congr.
Check PA.Formula.term_subst_instTerm_rename_two_succ.
Check PA.Formula.term_subst_upSubst_instTerm_rename_two_succ.
Check PA.Formula.term_subst_upSubst_instTerm_rename_three_succ.
Check PA.Formula.term_subst_up_up_instTerm_rename_three_succ.
Check PA.Formula.term_subst_up_up_instTerm_rename_two_var_zero.
Check PA.Formula.term_subst_up_up_instTerm_rename_four_succ.
Check PA.Formula.term_subst_up_up_up_instTerm_rename_four_succ.
Check PA.Formula.term_subst_up_up_up_instTerm_rename_five_succ.
Check PA.Formula.term_subst_up_up_up_up_instTerm_rename_five_succ.
Check PA.Formula.term_subst_up_up_up_up_instTerm_rename_six_succ.
Check PA.Formula.term_subst_up_up_up_up_up_instTerm_rename_six_succ.
Check PA.Formula.term_subst_up_up_up_up_up_up_instTerm_rename_seven_succ.
Check PA.Formula.iterUpSubst.
Check PA.Formula.term_subst_iterUpSubst_rename_add.
Check PA.Formula.term_subst_iterUpSubst_instTerm_rename_add_succ_offset.
Check PA.Formula.term_subst_iterUpSubst_instTerm_rename_ext.
Check PA.Formula.term_subst_iterUpSubst_instTerm_var_depth.
Check PA.Formula.term_subst_iterUpSubst_instTerm_var_rename_add_succ.
Check PA.Formula.term_subst_iterUpSubst_instTerm_rename_add_succ.
Check PA.Formula.subst_instTerm_rename_succ.
Check PA.Formula.subst_instTerm_var_zero_rename_up_succ.
Check PA.Formula.subst_instTerm_var_zero_up_var_one_rename_up_up_succ_twice.
Check PA.Formula.subst_instTerm_subst_up.
Check PA.Formula.map_subst_rename_succ_up.
Check PA.Formula.term_substZero_rename_succ.
Check PA.Formula.substZero_eq_instTerm.
Check PA.Formula.term_subst_iterUpSubst_substZero_rename_add_succ.
Check PA.Formula.term_subst_iterUpSubst_substSuccVar_rename_add_succ.
Check PA.Formula.term_subst_iterUpSubst_substSuccVar_rename_ext.
Check PA.Formula.term_substSuccVar_rename_succ.
Check PA.Formula.term_subst_up_up_up_substZero_rename_four_succ.
Check PA.Formula.term_subst_up_substZero_rename_two_succ.
Check PA.Formula.term_subst_up_substSuccVar_rename_two_succ.
Check PA.Formula.term_subst_up_up_up_substSuccVar_rename_four_succ.
Check PA.Formula.rename_hfMemAt.
Check PA.Formula.leConstAt.
Check PA.Formula.succPredAt.
Check PA.Formula.zeroOrSuccPredAt.
Check PA.Formula.betaDiv2StepsThroughConstAt.
Check PA.Formula.leConstAt_nat.
Check PA.Formula.succPredAt_nat.
Check PA.Formula.zeroOrSuccPredAt_nat.
Check PA.Formula.betaDiv2StepsThroughConstAt_nat.
Check PA.Formula.BetaShiftTailThrough.
Check PA.Formula.boolTermAt.
Check PA.Formula.div2StepTermAt.
Check PA.Formula.boolTermAt_nat.
Check PA.Formula.div2StepTermAt_nat.
Check PA.Formula.leTermAt_nat.
Check PA.Formula.ltTermAt_nat.
Check PA.Formula.BProv_Ax_s_zeroOrSuccPredAt_all.
Check PA.Formula.BProv_Ax_s_zeroOrSuccPred_term.
Check PA.Formula.BProv_Ax_s_zeroOrSuccPredAt.
Check PA.Formula.BProv_Ax_s_add_eq_zero_left_all.
Check PA.Formula.BProv_Ax_s_add_eq_zero_left_terms.
Check PA.Formula.BProv_Ax_s_leConstAt_of_leAt_eqConst.
Check PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leConstAt_zero.
Check PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leAt_eqConst_zero.
Check PA.Formula.BProv_Ax_s_leConstAt_succ_cases.
Check PA.Formula.BProv_Ax_s_addRightNumeral.
Check PA.Formula.BProv_Ax_s_mulRightNumeral.
Check PA.Formula.BProv_Ax_s_addNumerals.
Check PA.Formula.BProv_Ax_s_mulRightNumeral_numeral.
Check PA.Formula.BProv_Ax_s_mulNumerals.
Check PA.Formula.BProv_Ax_s_leAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_ltAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_ltConst_of_eqConst.
Check PA.Formula.BProv_Ax_s_ltConst_closed.
Check PA.Formula.BProv_Ax_s_dvdAt_of_eqConst_mul.
Check PA.Formula.BProv_Ax_s_dvdAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_boolAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_div2StepAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_div2StepAt_zero_one_bot.
Check PA.Formula.BProv_Ax_s_div2StepAt_zero_half_zero.
Check PA.Formula.BProv_Ax_s_div2StepAt_closedSubst.
Check PA.Formula.BProv_Ax_s_div2StepAt_constValueHalfSubst_of_eqConst.
Check PA.Formula.BProv_Ax_s_remAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_remAt_constMod_of_eqConst.
Check PA.Formula.BProv_Ax_s_remAt_constRemMod_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaModTerm_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaModTerm_constIdx_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAt_constOutSubst_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAt_constOutIdxSubst_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAt_constIdxSubst_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAtConstIdx_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAtSuccIdx_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAtSuccIdx_constOutSubst_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaDiv2BitAt_of_eqConst.
Check PA.Formula.BProv_Ax_s_betaAt_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaAt_constOutSubst_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaAt_constOutIdxSubst_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaAtConstIdx_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaAtSuccIdx_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaAtSuccIdx_constOutSubst_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_of_eqConst_step.
Check PA.Formula.BProv_Ax_s_betaDiv2BitAt_of_eqConst_step.
Check PA.Formula.BProv_Ax_s_betaDiv2StepWitnessAt_body_zero_next_zero.
Check PA.Formula.BProv_Ax_s_betaDiv2BitAt_body_zero_one_bot.
Check PA.Formula.BProv_Ax_s_betaDiv2BitAt_current_zero_bot.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_zero_of_eqConst_step.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_zero_of_eqConst_step.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_succ_of_eqConst_step.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_of_const_eqConst.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughConstAt_of_eqConst_trace.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughAt_of_eqConst_trace.
Check PA.Formula.remTermTermAt.
Check PA.Formula.betaModTermTerm.
Check PA.Formula.betaTermTermAt.
Check PA.Formula.betaTermTermAtConstIdx.
Check PA.Formula.betaTermTermAtSuccIdx.
Check PA.Formula.twoEntryBetaStepTerm.
Check PA.Formula.twoEntryBetaCodeTerm.
Check PA.Formula.crtExtendCodeTerm.
Check PA.Formula.crtInverseProductQuotTerm.
Check PA.Formula.crtPositiveInverseTerm.
Check PA.Formula.crtPositiveInverseQuotTerm.
Check PA.Formula.betaPairBezoutPositiveCoeffTerm.
Check PA.Formula.betaPairBezoutNegativeCoeffTerm.
Check PA.Formula.dvdTermTermAt.
Check PA.Formula.commonMultipleThroughTermAt.
Check PA.Formula.commonMultipleExistsTermAt.
Check PA.Formula.commonMultipleExistsTermAtBody.
Check PA.Formula.positiveCommonMultipleThroughTermAt.
Check PA.Formula.positiveCommonMultipleExistsTermAt.
Check PA.Formula.positiveCommonMultipleExistsTermAtBody.
Check PA.Formula.crtInverseTermAt.
Check PA.Formula.crtInverseExistsTermAt.
Check PA.Formula.crtInverseExistsTermAtQuotEx.
Check PA.Formula.crtInverseExistsTermAtBody.
Check PA.Formula.dvdTermTermAt_nat.
Check PA.Formula.commonMultipleThroughTermAt_nat.
Check PA.Formula.commonMultipleExistsTermAt_nat.
Check PA.Formula.positiveCommonMultipleThroughTermAt_nat.
Check PA.Formula.positiveCommonMultipleExistsTermAt_nat.
Check PA.Formula.crtInverseTermAt_nat.
Check PA.Formula.crtInverseExistsTermAt_nat.
Check PA.Formula.BProv_Ax_s_betaModTermTerm_zero.
Check PA.Formula.BProv_Ax_s_betaModTermTerm_one_add_self.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_of_eq_modulus.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_zero_double_step_of_one.
Check PA.Formula.BProv_Ax_s_remTermTermAt_of_eq_modulus.
Check PA.Formula.BProv_Ax_s_mul_mul_reorder_middle_terms.
Check PA.Formula.BProv_Ax_s_crtInverseProductQuot_expand.
Check PA.Formula.BProv_Ax_s_crtPositiveInverseTerm_add.
Check PA.Formula.BProv_Ax_s_crtPositiveInverseQuotTerm_add.
Check PA.Formula.BProv_Ax_s_crtPositiveInverse_of_negative.
Check PA.Formula.BProv_Ax_s_betaPair_negative_bezout.
Check PA.Formula.BProv_Ax_s_betaPair_positive_inverse.
Check PA.Formula.BProv_Ax_s_betaPair_positive_inverse_of_gap_scale.
Check PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_of_certificate.
Check PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_one.
Check PA.Formula.crtInverseExistsTermAtOpenedContext.
Check PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_ltTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_leTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_ltTermAt_of_succ_leTermAt.
Check PA.Formula.BProv_Ax_s_ltTermAt_gapPred_of_eq_add_succ_terms.
Check PA.Formula.BProv_Ax_s_ltTermAt_zero_mul_succ_right.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleThroughTermAt_zero.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleThroughTermAt_succ.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_of_through.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_zero.
Check PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_succ.
Check PA.Formula.BProv_Ax_s_all_positiveCommonMultipleExistsTermAt.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_of_betaPrefixDividesTermAt.
Check PA.Formula.BProv_Ax_s_betaPrefixDividesTermAt_zero.
Check PA.Formula.BProv_Ax_s_betaPrefixDividesTermAt_succ.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorTermAt_zero.
Check PA.Formula.BProv_Ax_s_betaPair_crtInverseExists_of_lt_commonMultiple.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_mul_terms.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_mul_right.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_divisor.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_value.
Check PA.Formula.BProv_Ax_s_dvdTermTermAt_of_commonMultipleThroughTermAt.
Check PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_zero.
Check PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_succ.
Check PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_of_through.
Check PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_zero.
Check PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_succ.
Check PA.Formula.BProv_Ax_s_all_commonMultipleExistsTermAt.
Check PA.Formula.BProv_Ax_s_leTermAt_of_ltTermAt_succ_right.
Check PA.Formula.BProv_Ax_s_eq_of_leTermAt_leTermAt.
Check PA.Formula.BProv_Ax_s_ltTermAt_succ_right_cases.
Check PA.Formula.BProv_Ax_s_crtInverse_mul.
Check PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_mul.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorTermAt_succ.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_of_term.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_zero.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_succ.
Check PA.Formula.BProv_Ax_s_all_betaPrefixCRTAccumulatorExistsTermAt_of_common.
Check PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_self.
Check PA.Formula.BProv_Ax_s_crtProductFactor_mul.
Check PA.Formula.BProv_Ax_s_crtExtendCodeTerm_preserve_decomposition.
Check PA.Formula.BProv_Ax_s_crtExtendCodeTerm_new_decomposition.
Check PA.Formula.BProv_Ax_s_remTermTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_remTermTermAt_crtExtend_preserve.
Check PA.Formula.BProv_Ax_s_remTermTermAt_crtExtend_new.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_opened_body_modEq.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_opened_body_rem.
Check PA.Formula.BProv_Ax_s_remTermTermAt_of_betaTermTermAt.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_crtExtend_preserve.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_crtExtend_new.
Check PA.Formula.div2TotalOpenedStepContext.
Check PA.Formula.div2TotalOpenedDoubleContext.
Check PA.Formula.div2TotalOpenedOddContext.
Check PA.Formula.strictSuccContext.
Check PA.Formula.strictSuccTarget.
Check PA.Formula.strictSuccOpenedTotalTarget.
Check PA.Formula.strictSuccOpenedHighDoubleLowDoubleContext.
Check PA.Formula.strictSuccOpenedHighDoubleLowOddContext.
Check PA.Formula.strictSuccOpenedHighOddLowDoubleContext.
Check PA.Formula.strictSuccOpenedHighOddLowOddContext.
Check PA.Formula.strictSuccOpenedHighDoubleLowOddMemContext.
Check PA.Formula.strictSuccOpenedHighDoubleLowOddMemTarget.
Check PA.Formula.strictHighOddSuccWitnessTerm.
Check PA.Formula.succOpenedWitnessMemTermFormula.
Check PA.Formula.succOpenedWitnessLowMemFormula.
Check PA.Formula.succOpenedWitnessBodyFormula.
Check PA.Formula.strictSuccOpenedHighOddCarryTarget.
Check PA.Formula.strictSuccOpenedHighOddLowDoubleOpenedIHContext.
Check PA.Formula.strictSuccOpenedHighOddLowOddOpenedIHContext.
Check PA.Formula.strictSuccOpenedHighOddOpenedIHTarget.
Check PA.Formula.strictSuccOpenedHighOddOpenedIHHighCode.
Check PA.Formula.strictSuccOpenedHighOddOpenedIHLow.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemFormula.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccLowMemFormula.
Check PA.Formula.BProv_succOpenedWitness_hfSomeDistinguishesTermAt.
Check PA.Formula.BProv_Ax_s_strictSuccOpenedHighOddOpenedIHTarget_of_succ_witness_mem_and_low_bot.
Check PA.Formula.BProv_Ax_s_subst_hfMemTermAt_of_components.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessHighHalfMemOpenedStepPredContext.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfTargetFormula.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfSubst.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfCode.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfEntryFormula.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfStepsFormula.
Check PA.Formula.strictSuccOpenedHighOddOpenedWitnessSuccMemOpenedHighHalfBitExFormula.
Check PA.Formula.BProv_Ax_s_strictSuccOpenedHighOddOpenedWitnessSuccMem_opened_high_half_of_components.
Check PA.Formula.BProv_Ax_s_ltTermAt_succ_right_of_leTermAt.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_zero.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_one_bound.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_two_mul_modulus_zero.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_modulus_one_square.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_one_value.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_one.
Check PA.Formula.BProv_Ax_s_twoEntryBetaTerm_entries.
Check PA.Formula.BProv_betaTermTermAt_congr_modulus.
Check PA.Formula.BProv_betaTermTermAt_congr.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_of_eq_output.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_of_eq_index.
Check PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_zero_bound.
Check PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_zero_of_eqConst_step_zero.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_of_through.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_zero_bound.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_of_eqConst_step_zero.
Check PA.Formula.BProv_Ax_s_eq_of_remTermTermAt_remTermTermAt_eq_modulus.
Check PA.Formula.BProv_Ax_s_eq_of_betaTermTermAt_betaTermTermAt_same_index.
Check PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_one_bound_of_entries.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_one_bound_of_entries.
Check PA.Formula.BProv_Ax_s_all_betaShiftTailExistsTermAt_of_successor.
Check PA.Formula.BProv_Ax_s_betaTermTermAtSuccIdx_of_succ.
Check PA.Formula.betaTermAt_eq_betaTermTermAt_var.
Check PA.Formula.BProv_Ax_s_remTermTermAt_of_eq_add_mul_terms.
Check PA.Formula.BProv_Ax_s_remTermTermAt_zero_modulus_one.
Check PA.Formula.BProv_Ax_s_ltTermAt_of_remTermTermAt.
Check PA.Formula.BProv_Ax_s_eq_zero_of_ltTermAt_one.
Check PA.Formula.BProv_Ax_s_eq_zero_of_remTermTermAt_eq_one.
Check PA.Formula.BProv_Ax_s_betaModTermTerm_eq_one_of_eq_step_zero.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_of_rem.
Check PA.Formula.BProv_Ax_s_betaTermTermAt_zero_of_eq_step_zero.
Check PA.Formula.BProv_Ax_s_eq_zero_of_betaTermTermAt_eq_step_zero.
Check PA.Formula.betaModTermTerm_nat.
Check PA.Formula.betaPrefixDividesTermAt.
Check PA.Formula.betaPrefixCRTAccumulatorTermAt.
Check PA.Formula.betaPrefixCRTAccumulatorExistsTermAt.
Check PA.Formula.betaPrefixCRTAccumulatorExistsTermAtBody.
Check PA.Formula.betaPrefixDividesTermAt_nat.
Check PA.Formula.betaPrefixCRTAccumulatorTermAt_nat.
Check PA.Formula.betaPrefixCRTAccumulatorExistsTermAt_nat.
Check PA.Formula.remTermTermAt_nat.
Check PA.Formula.betaTermTermAt_nat_entry.
Check PA.Formula.betaTermTermAtSuccIdx_nat_entry.
Check PA.Formula.betaDiv2StepWitnessTermAt.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermTermAt_step_of_leTerm.
Check PA.Formula.BProv_Ax_s_betaDiv2StepsThroughTermTermAt_step_succ_of_leTerm.
Check PA.Formula.BProv_Ax_s_betaDiv2StepWitnessTermSuccIdxAt_of_components.
Check PA.Formula.BProv_Ax_s_betaDiv2StepWitnessTermSuccIdxAt_of_termAt.
Check PA.Formula.BProv_Ax_s_hfMemTermAt_slot4_steps_of_term_trace.
Check PA.Formula.BProv_Ax_s_subst_betaAt_of_betaTermTermAt.
Check PA.Formula.BProv_Ax_s_subst_betaAtSuccIdx_of_betaTermTermAt_succ.
Check PA.Formula.BProv_Ax_s_betaDiv2BitTermAt_of_components.
Check PA.Formula.BProv_Ax_s_subst_betaDiv2BitAt_of_betaDiv2BitTermAt.
Check PA.Formula.BProv_Ax_s_subst_bitOneEx_of_betaDiv2BitOneTermExAt.
Check PA.Formula.BProv_Ax_s_hfMemTermAt_slot4_bitEx_of_betaDiv2BitOneTermExAt.
Check PA.Formula.betaDiv2StepWitnessTermAt_nat.
Check PA.Formula.betaDiv2StepWitnessTermSuccIdxAt.
Check PA.Formula.betaDiv2StepsThroughTermAt.
Check PA.Formula.betaDiv2StepsThroughTermAt_nat.
Check PA.Formula.betaDiv2StepsThroughTermTermAt.
Check PA.Formula.betaDiv2StepsThroughTermTermAt_nat.
Check PA.Formula.betaShiftTailThroughTermAt.
Check PA.Formula.betaShiftTailThroughTermAt_nat.
Check PA.Formula.betaShiftTailExistsTermAt.
Check PA.Formula.betaShiftTailExistsTermAtBody.
Check PA.Formula.betaShiftTailExistsTermAtStepEx.
Check PA.Formula.betaShiftTailExistsTermAtOpenedContext.
Check PA.Formula.betaShiftTailExistsTermAt_nat.
Check PA.Formula.betaShiftTailThroughConstAt.
Check PA.Formula.betaShiftTailThroughConstAt_nat.
Check PA.Formula.betaDiv2BitTermAt.
Check PA.Formula.betaDiv2BitTermAt_nat.
Check PA.Formula.betaDiv2BitOneTermExAt.
Check PA.Formula.betaDiv2BitOneTermExAt_nat.
Check PA.Formula.BProv_Ax_s_betaTermTermAtConstIdx_of_beta.
Check PA.Formula.BProv_Ax_s_hfMemAt_bitOneEx_of_bit.
Check PA.Formula.BProv_Ax_s_hfMemAt_of_closed_components.
Check PA.Formula.BProv_Ax_s_hfMemAt_of_closed_bit_components.
Check PA.Formula.BProv_Ax_s_hfMemTermAt_entry_of_betaTermTermAt_zero.
Check PA.Formula.BProv_Ax_s_betaShiftTailThroughTermAt_entry_of_leTerm.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_elim_opened.
Check PA.Formula.BProv_Ax_s_betaShiftTailExistsTermAt_assumption_elim_opened.
Check PA.Formula.BProv_Ax_s_hfMemAt_entryComponent_of_eqConst_entry.
Check PA.Formula.BProv_Ax_s_hfMemAt_bitComponent_of_eqConst_bit.
Check PA.Formula.BProv_Ax_s_hfMemAt_stepsComponent_of_eqConst_trace.

Check PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_trace_with_steps.
Check PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_trace.
Check PA.Formula.BProv_Ax_s_hfMemAt_of_eqConst_mem.
Check PA.Formula.BProv_Ax_s_hfMemAt_bot_of_opened_final_current_zero.
Check PA.Formula.BProv_Ax_s_HF_empty_zero_body_of_member_bot.
Check PA.Formula.BProv_Ax_s_translated_HF_empty_of_zero_body.
Check PA.Formula.BProv_Ax_s_translated_HF_empty_of_zero_member_bot.
Check PA.Formula.hfContextAt.
Check PA.Formula.translateHFContext.
Check PA.Formula.translateHFContext_eq_hfContextAt_id.
Check PA.Formula.hfFormulaAt_ext.
Check PA.Formula.hfFormulaAt_ext_free.
Check PA.Formula.hfFormulaAt_source_rename.
Check PA.Formula.rename_hfFormulaAt.
Check PA.Formula.hfUpVarMap_id.
Check PA.Formula.hfFormulaAt_rename_natural.
Check PA.Formula.hfFormulaAt_id_rename.
Check PA.Formula.hfFormulaAt_rename_succ.
Check PA.Formula.hfContextAt_rename_succ.
Check PA.Formula.hfContextAt_cons_rename_succ.
Check PA.Formula.subst_instTerm_var_hfFormulaAt.
Check PA.Formula.hfFormulaAt_eq_translateHFFormula_of_HF_sentence.
Check PA.Formula.Prov_hfFormulaAt_of_Prov.
Check PA.Formula.Prov_subst.
Check PA.Formula.BProv_hfFormulaAt_of_BProv_HFFin.
Check PA.Formula.BProv_translateHFFormula_of_BProv_HFFin.
Check PA.Formula.BProv_lift.
Check PA.Formula.BProv_eqElim.
Check PA.Formula.BProv_eqRefl.
Check PA.Formula.BProv_eqSym.
Check PA.Formula.BProv_eqTrans.
Check PA.Formula.BProv_eq_congr_term.
Check PA.Formula.BProv_eq_congr_succ.
Check PA.Formula.BProv_eq_congr_add_left.
Check PA.Formula.BProv_eq_congr_add_right.
Check PA.Formula.BProv_eq_congr_add.
Check PA.Formula.BProv_eq_congr_mul_left.
Check PA.Formula.BProv_eq_congr_mul_right.
Check PA.Formula.BProv_eq_congr_mul.
Check PA.Formula.BProv_context_cons.
Check PA.Formula.BProv_impI.
Check PA.Formula.BProv_impI_after_prefix.
Check PA.Formula.BProv_andI.
Check PA.Formula.BProv_botE.
Check PA.Formula.BProv_andE1.
Check PA.Formula.BProv_andE2.
Check PA.Formula.BProv_orI1.
Check PA.Formula.BProv_orI2.
Check PA.Formula.BProv_orE.
Check PA.Formula.BProv_allE.
Check PA.Formula.BProv_exI.
Check PA.Formula.BProv_allI_of_sentences.
Check PA.Formula.BProv_exE_of_sentences.
Check PA.Formula.BProv_weaken_nil.
Check PA.Formula.BProv_ass.
Check PA.Formula.BProv_rename_of_sentences.
Check PA.Formula.BProv_subst_of_sentences.
Check PA.Formula.BProv_closeN_allE_rename.
Check PA.Formula.BProv_sealPA_allE_rename.
Check PA.Formula.BProv_inductionForm_mp.
Check PA.Formula.BProv_Ax_s_of_sealPA_rename.
Check PA.Formula.BProv_Ax_s_succInj_rename.
Check PA.Formula.BProv_Ax_s_succInj.
Check PA.Formula.BProv_Ax_s_succInj_terms.
Check PA.Formula.BProv_Ax_s_zeroNotSucc_rename.
Check PA.Formula.BProv_Ax_s_zeroNotSucc.
Check PA.Formula.BProv_Ax_s_zeroNotSucc_term.
Check PA.Formula.BProv_Ax_s_addZero_rename.
Check PA.Formula.BProv_Ax_s_addZero.
Check PA.Formula.BProv_Ax_s_addZero_term.
Check PA.Formula.BProv_Ax_s_addSucc_rename.
Check PA.Formula.BProv_Ax_s_addSucc.
Check PA.Formula.BProv_Ax_s_addSucc_terms.
Check PA.Formula.BProv_Ax_s_mulZero_rename.
Check PA.Formula.BProv_Ax_s_mulZero.
Check PA.Formula.BProv_Ax_s_mulZero_term.
Check PA.Formula.BProv_Ax_s_mulSucc_rename.
Check PA.Formula.BProv_Ax_s_mulSucc.
Check PA.Formula.BProv_Ax_s_mulSucc_terms.
Check PA.Formula.BProv_Ax_s_inductionForm_rename.
Check PA.Formula.BProv_Ax_s_inductionForm.
Check PA.Formula.BProv_Ax_s_induction_rule.
Check PA.Formula.TranslatedHFAxiomProofs.
Check PA.Formula.TranslatedHFFinAxiomProofs.
Check PA.Formula.BProv_Ax_s_of_translatedHFAx_of_proofs.
Check PA.Formula.BProv_Ax_s_of_translatedHFFinAx_of_proofs.
Check PA.Formula.soundness_BProv.
Check PA.Formula.translated_HF_axiom_sat_nat.
Check PA.Formula.translated_HFFin_axiom_sat_nat.
Check PA.Formula.standard_sat_translatedHFAx.
Check PA.Formula.standard_sat_translatedHFFinAx.

Check HFAx_s.
Check HFFinAx_s.
Check Sentences_HF.
Check Sentences_HFFin.
Check HF_finite_induction_form.
Check HF_finite_induction_form_spec.
Check prefix_below.
Check mem_prefix_below_iff.
Check prefix_below_self_eq.
Check sat_HF_finite_induction_standard.
Check standard_sat_HF.
Check standard_sat_HFFin.
Check rename_HF_emptyAt.
Check rename_HF_adjoinAt.
Check rename_HF_succAt.
Check rename_HF_singleAt.
Check rename_HF_upairAt.
Check rename_HF_kpairAt.
Check rename_HF_pairMemAt.
Check rename_HF_pairFunctionalAt.
Check rename_HF_pairKeysBelowSuccAt.
Check rename_HF_pairTotalBelowSuccAt.
Check rename_HF_pairSuccStepAt.
Check rename_HF_pairBaseAt.
Check rename_HF_pairZeroBaseAt.
Check rename_HF_succRecApproxAt.
Check rename_addGraphAt.
Check rename_mulStepAt.
Check rename_mulRecApproxAt.
Check rename_mulGraphAt.
Check termGraphAt_map_ext_free.
Check termGraphAt_PA_rename.
Check termGraphAt_rename.
Check termGraphAt_inst_out.
Check formulaAt_PA_rename.
Check rename_domainForm_up.
Check formulaAt_rename.
Check formulaAt_rename_succ_upVarMap.
Check formulaAt_subst_instTerm_var.
Check formulaAt_map_ext_free.
Check formulaAt_eq_translateFormula_of_PA_sentence.
Check translateContextAt.
Check translateContextAt_id.
Check translateContextAt_rename_succ_upVarMap.
Check mem_translateContextAt_of_mem.
Check BProv_translate_allE_raw.
Check BProv_formulaAt_ass.
Check BProv_formulaAt_ax.
Check domainContextAt.
Check rename_domainForm_inst.
Check rename_domainForm_inst_zero.
Check domainContextAt_rename.
Check mem_domainContextAt.
Check mem_domainContextAt_mono.
Check BProv_mono_domainContextAt.
Check domainContextAt_upVarMap_succ.
Check BProv_domainContextAt_var.
Check BProv_formulaAt_impI.
Check BProv_formulaAt_impE.
Check BProv_formulaAt_botE.
Check BProv_formulaAt_lem.
Check BProv_formulaAt_eqRefl_var.
Check formulaAt_eqRefl_zero_valid_of_HFFinAx_s.
Check BProv_HFFin_formulaAt_eqRefl_zero_nil.
Check BProv_HFFin_formulaAt_eqRefl_zero.
Check BProv_formulaAt_eq_var_of_eq.
Check BProv_formulaAt_andI.
Check BProv_formulaAt_andE1.
Check BProv_formulaAt_andE2.
Check BProv_formulaAt_orI1.
Check BProv_formulaAt_orI2.
Check BProv_formulaAt_orE.
Check BProv_formulaAt_eq_of_termGraphsAt.
Check BProv_termGraphAt_eqElim_out.
Check BProv_formulaAt_eqRefl_of_termGraphAt.
Check BProv_eq_of_formulaAt_eq_var.
Check BProv_formulaAt_eqElim_var.
Check BProv_formulaAt_allI_raw.
Check BProv_formulaAt_allI.
Check BProv_formulaAt_allI_domainContext.
Check BProv_formulaAt_allI_domainContext_of_sentences.
Check BProv_formulaAt_allE_raw.
Check BProv_formulaAt_allE_var.
Check BProv_formulaAt_allE_slot_context.
Check BProv_formulaAt_slot_eqElim_context.
Check BProv_formulaAt_allE_equal_slot_context.
Check BProv_formulaAt_allE_var_context.
Check BProv_formulaAt_allE_var_domainContext.
Check BProv_formulaAt_exI_raw.
Check BProv_formulaAt_exI_var.
Check BProv_formulaAt_exI_slot_context.
Check BProv_formulaAt_exI_equal_slot_context.
Check BProv_formulaAt_exI_var_context.
Check BProv_formulaAt_exI_var_domainContext.
Check BProv_formulaAt_exE_raw.
Check BProv_formulaAt_exE.
Check BProv_formulaAt_exE_domainContext_of_sentences.
Check BProv_formulaAt_of_Prov_with_term_rules.
Check BProv_formulaAt_of_PA_BProv_with_term_rules.

Check firstOrderFiniteAdjunctionModel_of_HFFinAx_s.
Check formulaAt_induction_valid_finite_model.
Check translated_induction_sat_of_HFFinAx_s.
Check BProv_HFFin_translated_induction.
Check BProv_HFFin_translated_PA_axiom.
Check BProv_HFFin_of_translatedPAAx.
Check BProv_HFFin_of_BProv_translatedPAAx.
Check standard_sat_translatedPAAx.

Check ShallowBiInterpretation.
Check TheoryInterpretation.
Check TheoryInterpretation_comp.
Check setTheoryIdentityInterpretationOfAxiomProofs.
Check translatedPATheoryInHFFinInterpretation.
Check paInHFFinOfTranslatedPATheoryInterpretation.
Check paIdentityInterpretationOfAxiomProofs.
Check DeductiveBiInterpretationCertificate.
Check PAHFDeductiveBiInterpretationCertificate.
Check PAHFFinDeductiveBiInterpretationCertificate.
Check concreteTranslatedHFFinAxiomProofs.
Check concretePAOrdinalCodeMulTermCompatibility.
(** The multiplication induction is shared by the historical and corrected
    core packages; the audit keeps that weaker, reusable boundary visible. *)
Check PAOrdinalCodeMulOpenCoreForwardCompatibility_of_open.
Check PAOrdinalCodeTermMulCompatibility_of_total_core_halves.
Print Assumptions PAOrdinalCodeTermMulCompatibility_of_total_core_halves.
Check concretePARoundTripProof.
Check concreteHFRoundTripProof.
Check paHFFinDeductiveBiInterpretation.
Print Assumptions paHFFinDeductiveBiInterpretation.
Check StandardModelInterpretationCertificateFor.
Check StandardModelHFInterpretationCertificate.
Check StandardModelFiniteInterpretationCertificate.
Check standardModelHFInterpretation.
Check standardModelFiniteInterpretation.
Check PA_standard_model_interpretable_with_HF_semantic.
Check PA_standard_model_interpretable_with_HFFin.
Check PA_biinterpretable_with_HF_standard.
Check PA_biinterpretable_with_HFFin_standard.

Print Assumptions PA.Formula.sat_axiom_s.
Print Assumptions PA.Formula.soundness_BProv.
Print Assumptions sat_HF_model.
Print Assumptions standard_sat_HF.
Print Assumptions standard_sat_HFFin.
Print Assumptions PA_standard_model_interpretable_with_HF_semantic.
Print Assumptions PA_standard_model_interpretable_with_HFFin.
Print Assumptions PA_biinterpretable_with_HF_standard.
Print Assumptions PA_biinterpretable_with_HFFin_standard.
