/-
  PAHF/Audit.lean — type-check the PA/HF interpretability surface and print
  the axioms of its main semantic and deductive checkpoints.
-/
import PAHF

open SetTheory

-- canonical sentence invariant for the PA axiom theory
#check @PA.Formula.Ax_s_sentences

-- PA/HF Ackermann/von-Neumann semantic bi-interpretability checkpoint
#check @PA.Formula.Ax
#check @PA.Formula.sat_axiom
#check @PA.Formula.Ax_s
#check @PA.Formula.sat_axiom_s
#check @AckermannHF.not_mem_zero_of_double
#check @AckermannHF.mem_succ_double_iff
#check @AckermannHF.mem_succ_odd_double_iff
#check @AckermannHF.mem_succ_of_double_mem_succ
#check @PA.Formula.HFMemTrace_pred_of_succ_double
#check @PA.Formula.HFMemTrace_pred_of_succ_odd_double
#check @PA.Formula.HFMemTrace_pred_of_succ_div2Step
#check @PA.Formula.HFMemTrace_pred_of_shift_tail
#check @PA.Formula.HFMemTrace_pred_of_shift_tail_exists
#check @AckermannHF.mem_succ_double_not_mem_succ_odd_double_of_mem_not_mem
#check @AckermannHF.mem_succ_double_not_mem_succ_double_of_mem_not_mem
#check @AckermannHF.mem_succ_odd_double_not_mem_succ_double_of_mem_not_mem
#check @AckermannHF.mem_succ_odd_double_not_mem_succ_odd_double_of_mem_not_mem
#check @PA.Formula.Prov
#check @PA.Formula.Prov_weaken
#check @PA.Formula.Prov_cons
#check @PA.Formula.rename_ext
#check @PA.Formula.rename_comp
#check @PA.Formula.subst_rename
#check @PA.Formula.rename_subst
#check @PA.Term.subst_comp
#check @PA.Term.subst_rename_succ_up
#check @PA.Term.upSubst_comp
#check @PA.Term.subst_ext_free
#check @PA.Term.subst_id
#check @PA.Formula.subst_comp
#check @PA.Formula.subst_rename_succ_up
#check @PA.Formula.subst_ext_free
#check @PA.Formula.subst_id
#check @PA.Formula.subst_eq_of_sentence
#check @PA.Formula.subst_instTerm_rename_up
#check @PA.Formula.subst_instTerm_subst_up
#check @PA.Formula.term_subst_var_rename
#check @PA.Formula.subst_var_rename
#check @PA.Formula.term_subst_instTerm_var
#check @PA.Formula.subst_instTerm_var
#check @PA.Formula.Prov_rename
#check @PA.Formula.Prov_subst
#check @PA.Formula.Prov_cut
#check @PA.Formula.term_subst_instTerm_rename_succ
#check PA.Formula.iterEx
#check PA.Formula.iterRenameContextSucc
#check PA.Formula.openedContext
#check PA.Formula.openedExContext
#check @PA.Formula.BProv_context_prefix
#check @PA.Formula.BProv_context_two
#check @PA.Formula.BProv_context_three
#check @PA.Formula.BProv_iterRenameSucc_of_sentences
#check @PA.Formula.BProv_lift_openedContext_of_sentences
#check @PA.Formula.BProv_iterExE_of_sentences
#check @PA.Formula.subst_three_witnesses_rename_three_succ
#print axioms PA.Formula.BProv_iterExE_of_sentences
#print axioms PA.Formula.BProv_iterRenameSucc_of_sentences
#check @PA.Formula.term_subst_instTerm_rename_two_succ
#check @PA.Formula.term_subst_upSubst_instTerm_rename_two_succ
#check @PA.Formula.term_subst_upSubst_instTerm_rename_three_succ
#check @PA.Formula.term_subst_up_up_instTerm_rename_three_succ
#check @PA.Formula.term_subst_up_up_instTerm_rename_two_var_zero
#check @PA.Formula.term_subst_up_up_instTerm_rename_four_succ
#check @PA.Formula.term_subst_up_up_up_instTerm_rename_four_succ
#check @PA.Formula.term_subst_up_up_up_instTerm_rename_five_succ
#check @PA.Formula.term_subst_up_up_up_up_instTerm_rename_five_succ
#check @PA.Formula.term_subst_up_up_up_up_up_instTerm_rename_six_succ
#check @PA.Formula.term_subst_up_up_up_up_up_up_instTerm_rename_seven_succ
#check @PA.Formula.term_subst_up_up_up_up_substZero_rename_five_succ
#check @PA.Formula.term_subst_up_up_substZero_rename_three_succ
#check @PA.Formula.term_subst_up_up_substSuccVar_rename_three_succ
#check @PA.Formula.term_subst_up_up_up_up_up_substZero_rename_six_succ
#check @PA.Formula.term_subst_up_up_up_up_substSuccVar_rename_five_succ
#check @PA.Formula.term_subst_up_up_up_up_up_substSuccVar_rename_six_succ
#check @PA.Formula.term_subst_up_up_up_up_substZero_rename_add_five
#check @PA.Formula.term_subst_up_up_up_up_up_substZero_rename_add_six
#check @PA.Formula.term_subst_up_up_up_up_substSuccVar_rename_add_five
#check @PA.Formula.term_subst_up_up_up_up_up_substSuccVar_rename_add_six
#check PA.Formula.iterUpSubst
#check @PA.Formula.term_subst_iterUpSubst_instTerm_var_rename_add_succ
#check @PA.Formula.term_subst_iterUpSubst_instTerm_rename_add_succ
#check @PA.Formula.term_rename_up_succ_rename_succ
#check @PA.Formula.term_subst_instTerm_rename_up_up_succ
#check @PA.Formula.subst_instTerm_rename_succ
#check @PA.Formula.subst_instTerm_var_zero_rename_up_succ
#check @PA.Formula.subst_instTerm_var_zero_up_var_one_rename_up_up_succ_twice
#check @PA.Formula.soundness
#check @PA.Formula.BProv
#check @PA.Formula.BProv_mono
#check @PA.Formula.BProv_weaken_nil
#check @PA.Formula.BProv_ax
#check @PA.Formula.BProv_of_Prov
#check @PA.Formula.BProv_rename_of_sentences
#check @PA.Formula.BProv_subst_of_sentences
#check @PA.Formula.BProv_mp
#check @PA.Formula.BProv_lift
#check @PA.Formula.BProv_cut
#check @PA.Formula.BProv_theory_mono
#check @PA.Formula.BProv_eqElim
#check @PA.Formula.BProv_eqRefl
#check @PA.Formula.BProv_eqSym
#check @PA.Formula.BProv_eqTrans
#check @PA.Formula.BProv_eq_congr_term
#check @PA.Formula.BProv_eq_congr_succ
#check @PA.Formula.BProv_eq_congr_add_left
#check @PA.Formula.BProv_eq_congr_add_right
#check @PA.Formula.BProv_eq_congr_add
#check @PA.Formula.BProv_eq_congr_mul_left
#check @PA.Formula.BProv_eq_congr_mul_right
#check @PA.Formula.BProv_eq_congr_mul
#check @PA.Formula.BProv_context_cons
#check @PA.Formula.BProv_rename_succ_context_cons_of_sentences
#check @PA.Formula.BProv_impI
#check @PA.Formula.BProv_impI_after_prefix
#check @PA.Formula.BProv_andI
#check @PA.Formula.BProv_botE
#check @PA.Formula.BProv_andE1
#check @PA.Formula.BProv_andE2
#check @PA.Formula.BProv_orI1
#check @PA.Formula.BProv_orI2
#check @PA.Formula.BProv_orE
#check @PA.Formula.BProv_allE
#check @PA.Formula.BProv_exI
#check @PA.Formula.BProv_allI_of_sentences
#check @PA.Formula.BProv_closeN_nil_of_sentences
#check @PA.Formula.BProv_exE_of_sentences
#check @PA.Formula.BProv_closeN_allE_rename
#check @PA.Formula.BProv_sealPA_allE_rename
#check @PA.Formula.soundness_BProv
#check @PA.Term.Free
#check @PA.Term.free_lt_bound
#check @PA.Term.numeral
#check @PA.Term.addRightNumeral
#check @PA.Term.mulRightNumeral
#check @PA.Term.numeralValue
#check @PA.Term.eval_numeral
#check @PA.Term.numeralValue_natModel
#check @PA.Term.eval_numeral_natModel
#check @PA.Term.rename_numeral
#check @PA.Term.subst_numeral
#check @PA.Term.numeral_succ
#check @PA.Term.addRightNumeral_numeral
#check @PA.Term.rename_ext
#check @PA.Term.rename_ext_free
#check @PA.Term.rename_id
#check @PA.Term.rename_comp
#check @PA.Term.subst_ext
#check @PA.Term.subst_rename
#check @PA.Term.rename_subst
#check @PA.Formula.substTermAt
#check @PA.Formula.substTermAt_zero
#check @PA.Formula.upSubst_substTermAt
#check @PA.Formula.Free
#check @PA.Formula.Sentence
#check @PA.Formula.Sentences
#check @PA.Formula.rename_ext_free
#check @PA.Formula.rename_id
#check @PA.Formula.rename_eq_of_sentence
#check @PA.Formula.sealPA_sentence
#check @PA.Formula.sentence_ax_s
#check @PA.Formula.BProv_inductionForm_mp
#check @PA.Formula.Ax_s_succInj
#check @PA.Formula.Ax_s_zeroNotSucc
#check @PA.Formula.Ax_s_addZero
#check @PA.Formula.Ax_s_addSucc
#check @PA.Formula.Ax_s_mulZero
#check @PA.Formula.Ax_s_mulSucc
#check @PA.Formula.Ax_s_induction
#check @PA.Formula.BProv_Ax_s_of_sealPA_rename
#check @PA.Formula.BProv_Ax_s_succInj_rename
#check @PA.Formula.BProv_Ax_s_succInj
#check @PA.Formula.BProv_Ax_s_succInj_terms
#check @PA.Formula.BProv_Ax_s_zeroNotSucc_rename
#check @PA.Formula.BProv_Ax_s_zeroNotSucc
#check @PA.Formula.BProv_Ax_s_zeroNotSucc_term
#check @PA.Formula.BProv_Ax_s_addZero_rename
#check @PA.Formula.BProv_Ax_s_addZero
#check @PA.Formula.BProv_Ax_s_addZero_term
#check @PA.Formula.BProv_Ax_s_addSucc_rename
#check @PA.Formula.BProv_Ax_s_addSucc
#check @PA.Formula.BProv_Ax_s_addSucc_terms
#check @PA.Formula.BProv_Ax_s_zero_add_all
#check @PA.Formula.BProv_Ax_s_zero_add_term
#check @PA.Formula.BProv_Ax_s_succ_add_all
#check @PA.Formula.BProv_Ax_s_succ_add_terms
#check @PA.Formula.BProv_Ax_s_succ_add_cancel_terms
#check @PA.Formula.BProv_Ax_s_add_cancel_left_all
#check @PA.Formula.BProv_Ax_s_add_cancel_left_terms
#check @PA.Formula.BProv_Ax_s_add_cancel_right_all
#check @PA.Formula.BProv_Ax_s_add_cancel_right_terms
#check @PA.Formula.BProv_Ax_s_add_assoc_all
#check @PA.Formula.BProv_Ax_s_add_assoc_terms
#check @PA.Formula.BProv_Ax_s_add_comm_all
#check @PA.Formula.BProv_Ax_s_add_comm_terms
#check @PA.Formula.BProv_Ax_s_add_succ_ne_self_all
#check @PA.Formula.BProv_Ax_s_add_succ_ne_self_terms
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPredAt_all
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPred_term
#check @PA.Formula.BProv_Ax_s_zeroOrSuccPredAt
#check @PA.Formula.BProv_nonzeroAt_elim
#check @PA.Formula.BProv_nonzeroAt_of_succPredAt
#check @PA.Formula.term_substZero_rename_succ
#check @PA.Formula.term_substSuccVar_rename_succ
#check @PA.Formula.BProv_Ax_s_add_eq_zero_left_all
#check @PA.Formula.BProv_Ax_s_add_eq_zero_left_terms
#check @PA.Formula.BProv_Ax_s_add_eq_zero_right_terms
#check @PA.Formula.BProv_Ax_s_leConstAt_of_leAt_eqConst
#check @PA.Formula.BProv_Ax_s_leConstAt_of_leTermAt_eq_numeral
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leConstAt_zero
#check @PA.Formula.BProv_Ax_s_eqConstAt_zero_of_leAt_eqConst_zero
#check @PA.Formula.BProv_Ax_s_leConstAt_succ_cases
#check @PA.Formula.BProv_Ax_s_mulZero_rename
#check @PA.Formula.BProv_Ax_s_mulZero
#check @PA.Formula.BProv_Ax_s_mulZero_term
#check @PA.Formula.BProv_Ax_s_mulSucc_rename
#check @PA.Formula.BProv_Ax_s_mulSucc
#check @PA.Formula.BProv_Ax_s_mulSucc_terms
#check @PA.Formula.BProv_Ax_s_zero_mul_all
#check @PA.Formula.BProv_Ax_s_zero_mul_term
#check @PA.Formula.BProv_Ax_s_succ_mul_all
#check @PA.Formula.BProv_Ax_s_succ_mul_terms
#check @PA.Formula.BProv_Ax_s_mul_comm_all
#check @PA.Formula.BProv_Ax_s_mul_comm_terms
#check @PA.Formula.BProv_Ax_s_mul_add_all
#check @PA.Formula.BProv_Ax_s_mul_add_terms
#check @PA.Formula.BProv_Ax_s_add_mul_all
#check @PA.Formula.BProv_Ax_s_add_mul_terms
#check @PA.Formula.BProv_Ax_s_mul_assoc_all
#check @PA.Formula.BProv_Ax_s_mul_assoc_terms
#check @PA.Formula.BProv_Ax_s_mul_one_all
#check @PA.Formula.BProv_Ax_s_mul_one_term
#check @PA.Formula.BProv_Ax_s_one_mul_all
#check @PA.Formula.BProv_Ax_s_one_mul_term
#check @PA.Formula.BProv_Ax_s_addRightNumeral
#check @PA.Formula.BProv_Ax_s_mulRightNumeral
#check @PA.Formula.BProv_Ax_s_mul_two_right_terms
#check @PA.Formula.BProv_Ax_s_addNumerals
#check @PA.Formula.BProv_Ax_s_mulRightNumeral_numeral
#check @PA.Formula.BProv_Ax_s_mulNumerals
#check @PA.Formula.BProv_Ax_s_leAt_of_eq
#check @PA.Formula.BProv_Ax_s_leAt_of_eqConst_zero_left
#check @PA.Formula.BProv_Ax_s_leAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_leTermAt_numeral_of_eqConst
#check @PA.Formula.BProv_Ax_s_ltAt_of_eqConst
#check @PA.Formula.BProv_Ax_s_leAt_of_ltAt
#check @PA.Formula.BProv_Ax_s_leAt_refl
#check @PA.Formula.BProv_Ax_s_leAt_trans
#check @PA.Formula.BProv_Ax_s_eq_of_leAt_leAt
#check @PA.Formula.BProv_Ax_s_ltAt_trans
#check @PA.Formula.BProv_Ax_s_ltAt_leAt_trans
#check @PA.Formula.BProv_Ax_s_leAt_ltAt_trans
#check @PA.Formula.BProv_Ax_s_ltAt_irrefl_bot
#check @PA.Formula.BProv_Ax_s_ltAt_leAt_bot
#check @PA.Formula.BProv_Ax_s_ltTermAt_leTermAt_bot
#check @PA.Formula.BProv_Ax_s_ltAt_asymm_bot
#check @PA.Formula.BProv_Ax_s_ltAt_eq_bot
#check @PA.Formula.BProv_Ax_s_ltAt_of_eqConst_zero_succPredAt
#check @PA.Formula.BProv_Ax_s_succPredAt_of_ltAt
#check @PA.Formula.BProv_leTermAt_of_eq_left
#check @PA.Formula.BProv_leTermAt_of_eq_right
#check @PA.Formula.BProv_ltTermAt_of_eq_left
#check @PA.Formula.BProv_ltTermAt_of_eq_right
#check @PA.Formula.BProv_Ax_s_leTermAt_refl
#check @PA.Formula.BProv_Ax_s_leTermAt_zero_left
#check @PA.Formula.BProv_Ax_s_ltTermAt_zero_succ
#check @PA.Formula.BProv_Ax_s_ltTermAt_self_succ
#check @PA.Formula.BProv_Ax_s_remTermTermAt_of_eq_add_mul_terms
#check @PA.Formula.BProv_Ax_s_remTermTermAt_of_eq_modulus
#check @PA.Formula.BProv_Ax_s_remTermTermAt_zero_modulus_one
#check @PA.Formula.BProv_Ax_s_ltTermAt_of_remTermTermAt
#check @PA.Formula.BProv_Ax_s_eq_zero_of_remTermTermAt_eq_one
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_mul_terms
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_mul_right
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_divisor
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_of_eq_value
#check @PA.Formula.BProv_Ax_s_ltTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_leTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_leTermAt_succ_left_of_ltTermAt
#check @PA.Formula.BProv_Ax_s_ltTermAt_of_succ_leTermAt
#check @PA.Formula.BProv_Ax_s_ltTermAt_of_lt_leTermAt
#check @PA.Formula.BProv_Ax_s_crtCorrectionExistsTermAt_of_lt
#check @PA.Formula.BProv_Ax_s_ltTermAt_gapPred_of_eq_add_succ_terms
#check @PA.Formula.BProv_Ax_s_ltTermAt_zero_mul_succ_right
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_of_commonMultipleThroughTermAt
#check @PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_of_le
#check @PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_mul_right
#check @PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_zero
#check @PA.Formula.BProv_Ax_s_commonMultipleThroughTermAt_succ
#check @PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_of_through
#check @PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_zero
#check @PA.Formula.BProv_Ax_s_commonMultipleExistsTermAt_succ
#check @PA.Formula.BProv_Ax_s_all_commonMultipleExistsTermAt
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleThroughTermAt_zero
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleThroughTermAt_succ
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_of_through
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_zero
#check @PA.Formula.BProv_Ax_s_positiveCommonMultipleExistsTermAt_succ
#check @PA.Formula.BProv_Ax_s_all_positiveCommonMultipleExistsTermAt
#check @PA.Formula.BProv_Ax_s_betaCodingStepTermAt_of_positiveCommon
#check @PA.Formula.BProv_Ax_s_betaCodingStepExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_betaCodingStepExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_betaCodingStepExistsTermAt
#check @PA.Formula.BProv_Ax_s_betaPrependCodingStepTermAt_of_positiveCommon
#check @PA.Formula.BProv_Ax_s_betaPrependCodingStepExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_betaPrependCodingStepExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_betaPrependCodingStepExistsTermAt
#check @PA.Formula.BProv_Ax_s_betaPair_positive_inverse_of_gap_scale
#check @PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_of_certificate
#check @PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_one
#check @PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_crtCorrectionExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_crtCorrectionExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_crtInverseExistsTermAt_mul
#check @PA.Formula.BProv_Ax_s_betaPair_crtInverseExists_of_lt_commonMultiple
#check @PA.Formula.BProv_Ax_s_dvdTermTermAt_of_betaPrefixDividesTermAt
#check @PA.Formula.BProv_Ax_s_betaPrefixAgreementTermAt_crtExtend
#check @PA.Formula.BProv_Ax_s_betaCodeExtensionTermAt_crtExtend
#check @PA.Formula.BProv_Ax_s_betaCodeExtensionExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_betaCodeExtensionExistsTermAt_of_prefix_inverse
#check @PA.Formula.BProv_Ax_s_betaPrefixDividesTermAt_zero
#check @PA.Formula.BProv_Ax_s_betaPrefixDividesTermAt_succ
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorTermAt_zero
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorTermAt_succ
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_elim_opened
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_zero
#check @PA.Formula.BProv_Ax_s_betaPrefixCRTAccumulatorExistsTermAt_succ
#check @PA.Formula.BProv_Ax_s_all_betaPrefixCRTAccumulatorExistsTermAt_of_common
#check @PA.Formula.BProv_Ax…35055 tokens truncated…paCompositeAt_up
#check @PA.Formula.rename_succ_rawBody
#check @PA.Formula.subst_instTerm_range_rawBody
#check @PA.Formula.subst_instTerm_total_codedBody
#check @PA.Formula.standard_sat_ordinalCodeGraphTotal
#check @PA.Formula.standard_sat_ordinalCodeGraphRange
#check @PA.Formula.OrdinalCodeGraphProofs
#check @PA.Formula.codedOrdinalDomain_free
#check @PA.Formula.subst_instTerm_var_zero_codedOrdinalDomain
#check @PA.Formula.subst_instTerm_total_codedOrdinalDomain
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraph_range_of_domain
#check @PA.Formula.BProv_Ax_s_codedOrdinalDomain_of_ordinalCodeGraph
#check @PA.Formula.PACompositeStructuralProofs
#check @PA.Formula.BProv_Ax_s_pa_roundTrip_of_structuralProofs
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepsTermAt_zero
#check @PA.Formula.ordinalCodeGraphBodyTermAt
#check @PA.Formula.subst_ordinalCodeGraphTermAt
#check @PA.Formula.rename_ordinalCodeGraphTermAt
#check @PA.Formula.subst_instTerm_ordinalCodeGraphBody_inner
#check @PA.Formula.subst_instTerm_ordinalCodeGraphBody_outer
#check @PA.Formula.BProv_ordinalCodeGraphTermAt_of_body
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_elim_opened
#check @PA.Formula.OrdinalCodeGraphBodyFunctional
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_functional_of_body
#check @PA.Formula.ordinalCodeTraceAgreementAt
#check @PA.Formula.subst_ordinalCodeTraceAgreementAt
#check @PA.Formula.rename_ordinalCodeTraceAgreementAt
#check @PA.Formula.BProv_Ax_s_eq_of_hfSameMembersTermAt
#check @PA.Formula.BProv_Ax_s_hfAdjoinGraphTermAt_functional
#check @PA.Formula.BProv_Ax_s_ordinalCodeTraceAgreementAt_zero
#check @PA.Formula.BProv_Ax_s_hfAdjoinGraphTermAt_congr_inputs
#check @PA.Formula.BProv_ordinalCodeTraceAgreementAt_of_components
#check @PA.Formula.BProv_Ax_s_ordinalCodeTraceAgreementAt_succ
#check @PA.Formula.BProv_Ax_s_eq_of_ordinalCodeTraceAgreementAt
#check @PA.Formula.OrdinalCodeTraceAgreementProof
#check @PA.Formula.ordinalCodeTraceAgreementProof
#check @PA.Formula.OrdinalCodeGraphBodyFunctional_of_traceAgreement
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_functional_of_traceAgreement
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_zero
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_zero_exists
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepWitnessTermAt_of_components
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepsTermAt_step_of_ltTerm
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepWitnessTermAt_of_prefixAgreement
#check @PA.Formula.subst_betaPrefixAgreementTermAt
#check @PA.Formula.rename_betaPrefixAgreementTermAt
#check @PA.Formula.subst_betaCodeExtensionTermAt
#check @PA.Formula.rename_betaCodeExtensionTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepsTermAt_succ_of_extension
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphBodyTermAt_succ_of_extension
#check @PA.Formula.BProv_Ax_s_betaCodingStepTermAt_old_of_sum_capacity
#check @PA.Formula.BProv_Ax_s_betaCodeExtensionExistsTermAt_of_sum_capacity
#check @PA.Formula.ordinalCodeGraphBodyExistsTermAt
#check @PA.Formula.subst_ordinalCodeGraphBodyExistsTermAt
#check @PA.Formula.rename_ordinalCodeGraphBodyExistsTermAt
#check @PA.Formula.BProv_ordinalCodeGraphBodyExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphBodyExistsTermAt_elim_opened
#check @PA.Formula.ordinalCodeTraceCapacityTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphBodyTermAt_zero_at_step
#check @PA.Formula.BProv_Ax_s_ordinalCodeTraceCapacityTermAt_zero
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphBodyExistsTermAt_succ_of_sum_capacity
#check @PA.Formula.rename_betaCodingStepTermAt
#check @PA.Formula.rename_ordinalCodeTraceCapacityTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeTraceCapacityTermAt_trace_of_coding
#check @PA.Formula.BProv_Ax_s_ordinalCodeTraceCapacityTermAt_succ
#check @PA.Formula.subst_betaCodingStepTermAt
#check @PA.Formula.subst_ordinalCodeTraceCapacityTermAt
#check @PA.Formula.ordinalCodeTotalCapacityTermAt
#check @PA.Formula.subst_ordinalCodeTotalCapacityTermAt
#check @PA.Formula.rename_ordinalCodeTotalCapacityTermAt
#check @PA.Formula.BProv_ordinalCodeTotalCapacityTermAt_of_terms
#check @PA.Formula.BProv_Ax_s_ordinalCodeTotalCapacityTermAt_zero
#check @PA.Formula.BProv_Ax_s_hfAdjoinExistsTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeTotalCapacityTermAt_succ_of_terms
#check @PA.Formula.BProv_Ax_s_ordinalCodeTotalCapacityTermAt_succ
#check @PA.Formula.BProv_Ax_s_all_ordinalCodeTotalCapacityTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_of_bodyExists
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_of_capacity
#check @PA.Formula.ordinalCodeGraphExistsTermAt
#check @PA.Formula.subst_ordinalCodeGraphExistsTermAt
#check @PA.Formula.rename_ordinalCodeGraphExistsTermAt
#check @PA.Formula.BProv_ordinalCodeGraphExistsTermAt_of_term
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphExistsTermAt_of_totalCapacity
#check @PA.Formula.OrdinalCodeGraphProofs_total
#check @PA.Formula.BProv_Ax_s_all_of_strongStep
#check @PA.Formula.ordinalCodeGraphRangePoint
#check @PA.Formula.ordinalCodeGraphRangeExistsTermAt
#check @PA.Formula.subst_instTerm_ordinalCodeGraphRangePoint
#check @PA.Formula.rename_rSkipParam_ordinalCodeGraphRangePoint
#check @PA.Formula.ordinalCodeDomainSuccBodyTermAt
#check @PA.Formula.ordinalCodeDomainZeroOrSuccTermAt
#check @PA.Formula.OrdinalCodeGraphRangeStrongStep
#check @PA.Formula.OrdinalCodeGraphRangeLocalFacts
#check @PA.Formula.BProv_ordinalCodeGraphRangePoint_of_strongBelow
#check @PA.Formula.OrdinalCodeGraphRangeStrongStep_of_localFacts
#check @PA.Formula.OrdinalCodeGraphProofs_range_of_strongStep
#check @PA.Formula.HF_ordinalCodeZeroCase
#check @PA.Formula.HF_ordinalCodeSuccBody
#check @PA.Formula.HF_ordinalCodeZeroOrSuccPoint
#check @PA.Formula.HF_ordinalCodeZeroOrSuccSentence
#check @PA.Formula.HF_ordinalCodeZeroOrSuccSentence_sentence
#check @PA.Formula.BProv_HFFin_ordinalCodeZeroOrSuccSentence
#check @PA.Formula.ordinalCodeZeroCase
#check @PA.Formula.ordinalCodeMemSuccBody
#check @PA.Formula.ordinalCodeMemZeroOrSuccPoint
#check @PA.Formula.translateHFFormula_ordinalCodeZeroOrSuccSentence
#check @PA.Formula.BProv_Ax_s_ordinalCodeMemZeroOrSuccSentence
#check @PA.Formula.ordinalCodeZeroCaseTermAt
#check @PA.Formula.ordinalCodeMemSuccBodyTermAt
#check @PA.Formula.ordinalCodeMemZeroOrSuccTermAt
#check @PA.Formula.subst_instTerm_ordinalCodeMemZeroOrSuccPoint
#check @PA.Formula.BProv_Ax_s_hfEmptyTermAt_zero
#check @PA.Formula.BProv_hfEmptyTermAt_not_mem
#check @PA.Formula.BProv_Ax_s_same_members_of_hfEmptyTermAt
#check @PA.Formula.BProv_Ax_s_eq_of_hfEmptyTermAt_hfEmptyTermAt
#check @PA.Formula.BProv_Ax_s_eq_zero_of_hfEmptyAt
#check @PA.Formula.BProv_Ax_s_eq_zero_of_ordinalCodeGraphTermAt_zero
#check @PA.Formula.BProv_Ax_s_ordinalCodeMemZeroOrSuccTermAt_of_domain
#check @PA.Formula.BProv_Ax_s_ordinalCodeDomainZeroOrSuccAt_of_domain
#check @PA.Formula.subst_ordinalCodeDomainZeroOrSuccTermAt
#check @PA.Formula.BProv_Ax_s_all_ordinalCodeDomainZeroOrSucc
#check @PA.Formula.OrdinalCodeGraphRangeLocalFacts_domain_decompose
#check @PA.Formula.OrdinalCodeGraphSuccClosure
#check @PA.Formula.OrdinalCodeGraphCodomain
#check @PA.Formula.OrdinalCodeGraphRangeLocalFacts_of_succ_codomain
#check @PA.Formula.OrdinalCodeGraphProofs_range_of_succ_codomain
#check @PA.Formula.codeEqualityBodyTermAt
#check @PA.Formula.codeEqualityTermAt
#check @PA.Formula.subst_codeEqualityBodyTermAt
#check @PA.Formula.subst_codeEqualityTermAt
#check @PA.Formula.rename_codeEqualityTermAt
#check @PA.Formula.subst_instTerm_codeEqualityBody_inner
#check @PA.Formula.subst_instTerm_codeEqualityBody_outer
#check @PA.Formula.BProv_codeEqualityTermAt_of_components
#check @PA.Formula.BProv_ordinalCodeGraphTermAt_congr_raw
#check @PA.Formula.BProv_ordinalCodeGraphTermAt_congr_coded
#check @PA.Formula.BProv_ordinalCodeGraphTermAt_congr
#check @PA.Formula.OrdinalCodeGraphFunctional
#check @PA.Formula.OrdinalCodeGraphFunctional_of_traceAgreement
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraphTermAt_functional
#check @PA.Formula.ordinalCodeGraphFunctional
#check @PA.Formula.rename_leTermAt
#check @PA.Formula.rename_hfAdjoinGraphTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeStepsTermAt_of_leTerm
#check @PA.Formula.HF_zeroDomainSentence
#check @PA.Formula.HF_zeroDomainSentence_sentence
#check @PA.Formula.BProv_HFFin_zeroDomainSentence
#check @PA.Formula.translateHFFormula_zeroDomainSentence
#check @PA.Formula.BProv_Ax_s_zeroDomainSentence
#check @PA.Formula.BProv_Ax_s_codedOrdinalDomain_zero
#check @PA.Formula.HF_domainSuccSentence
#check @PA.Formula.HF_domainSuccSentence_sentence
#check @PA.Formula.BProv_HFFin_domainSuccSentence
#check @PA.Formula.translateHFFormula_domainSuccSentence
#check @PA.Formula.BProv_Ax_s_domainSuccSentence
#check @PA.Formula.BProv_Ax_s_codedOrdinalDomain_adjoin_self
#check @PA.Formula.ordinalCodePredEdgeTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodePredEdgeTermAt_of_succ_graph
#check @PA.Formula.ordinalCodeCodomainTermAt
#check @PA.Formula.subst_ordinalCodeCodomainTermAt
#check @PA.Formula.rename_ordinalCodeCodomainTermAt
#check @PA.Formula.BProv_Ax_s_ordinalCodeCodomainTermAt_zero
#check @PA.Formula.subst_instTerm_var_one_codedOrdinalDomain
#check @PA.Formula.BProv_Ax_s_ordinalCodeCodomainTermAt_succ
#check @PA.Formula.BProv_Ax_s_all_ordinalCodeCodomain
#check @PA.Formula.rename_subst_instTerm_codedOrdinalDomain
#check @PA.Formula.ordinalCodeGraphCodomain
#check @PA.Formula.ordinalCodeGraphSuccClosure
#check @PA.Formula.BProv_Ax_s_ordinalCodeGraph_range_exact
#check @PA.Formula.BProv_Ax_s_term_graph_var
#check @PA.Formula.compositeTermGraphAt_succ
#check @PA.Formula.BProv_Ax_s_hfAdjoinGraphTermAt_iff_ordinalCodeGraphTermAt_succ
#check @PA.Formula.OrdinalCodeTermGraphProof
#check @PA.Formula.OrdinalCodeTermCompatibilityProofs
#check @PA.Formula.OrdinalCodeTermCompatibilityProofs_zero_compatible
#check @PA.Formula.OrdinalCodeTermGraphProof_zero
#check @PA.Formula.BProv_Ax_s_term_graph_succ_of_shifted_operand
#check @PA.Formula.OrdinalCodeTermGraphProof_succ
#check @PA.Formula.ordinalCodeTermGraphProof_succ
#check @PA.Formula.OrdinalCodeTermAddCompatibility
#check @PA.Formula.OrdinalCodeTermMulCompatibility
#check PA.Formula.ordinalCodeTermAddCompatibility
#check PA.Formula.ordinalCodeTermMulCompatibility
#check @PA.Formula.OrdinalCodeTermCompatibilityProofs_of_add_mul
#check @PA.Formula.OrdinalCodeTermCompatibilityProofs_of_mul
#check @PA.Formula.BProv_Ax_s_term_graph_of_compatibility
#check @PA.Formula.OrdinalCodeGraphRemainingProofs
#check @PA.Formula.OrdinalCodeGraphInjective
#check PA.Formula.ordinalCodeGraphInjective
#check @PA.Formula.OrdinalCodeGraphRemainingProofs_of_injective
#check @PA.Formula.OrdinalCodeGraphProofs_of_remaining_and_compatibility
#check @PA.Formula.OrdinalCodeGraphProofs_of_injective_add_mul
#check @PA.Formula.OrdinalCodeGraphProofs_of_mul
#check PA.Formula.ordinalCodeGraphProofs
#check @PA.Formula.BProv_codeEqualityTermAt_of_eq
#check @PA.Formula.BProv_eq_of_codeEqualityTermAt
#check @PA.Formula.BProv_eq_iff_codeEqualityTermAt
#check @PA.Formula.BProv_iffForm_refl
#check @PA.Formula.BProv_iffForm_symm
#check @PA.Formula.BProv_iffForm_trans
#check @PA.Formula.BProv_iffForm_intro
#check @PA.Formula.BProv_iffForm_forward
#check @PA.Formula.BProv_iffForm_reverse
#check @PA.Formula.BProv_imp_trans
#check @PA.Formula.BProv_imp_mono
#check @PA.Formula.BProv_and_mono
#check @PA.Formula.BProv_or_mono
#check @PA.Formula.BProv_ex_mono_of_sentences
#check @PA.Formula.BProv_all_mono_of_sentences
#check @PA.Formula.BProv_iffForm_imp_congr
#check @PA.Formula.BProv_iffForm_and_congr
#check @PA.Formula.BProv_iffForm_or_congr
#check @PA.Formula.BProv_iffForm_ex_congr_of_sentences
#check @PA.Formula.BProv_iffForm_all_congr_of_sentences
#check @PA.Formula.paCompositeEqBodyAt
#check @PA.Formula.hfFormulaAt_termGraph_left_eq_composite
#check @PA.Formula.hfFormulaAt_termGraph_right_eq_composite
#check @PA.Formula.paCompositeAt_eq_normalForm
#check @PA.Formula.BProv_paCompositeAt_eq_iff_codeEqualityTermAt_of_termGraphs
#check @PA.Formula.BProv_Ax_s_paCompositeAt_eq_exact
#check @PA.Formula.BProv_Ax_s_paCompositeAt_all_forward
#check @PA.Formula.BProv_Ax_s_paCompositeAt_all_reverse
#check @PA.Formula.BProv_Ax_s_paCompositeAt_all_exact
#check @PA.Formula.BProv_Ax_s_paCompositeAt_ex_forward
#check @PA.Formula.BProv_Ax_s_paCompositeAt_ex_reverse
#check @PA.Formula.BProv_Ax_s_paCompositeAt_ex_exact
#check @PA.Formula.BProv_Ax_s_paCompositeAt_formula_exact
#check @PA.Formula.PACompositeStructuralProofs_of_graphProofs
#check @PA.Formula.BProv_Ax_s_pa_roundTrip_of_graphProofs
#check @PA.Formula.QuantifierFree
#check @PA.Formula.BProv_Ax_s_paCompositeAt_iff_of_quantifierFree
#check @AckermannHF.PAHFFinDeductiveBiInterpretationCertificate_of_codeStructuralProofs
#check @AckermannHF.repPairSlotMap
#check @AckermannHF.repPairNatMap
#check @AckermannHF.HF_compositeMemAt
#check @AckermannHF.HF_compositeMemAt_exact_codes
#check @AckermannHF.CompositeMemObj
#check @AckermannHF.HF_compositeMemAt_exact_of_ordinal
#check @AckermannHF.HF_setOrdinalRepCertificateAt
#check @AckermannHF.HF_setOrdinalRepAt
#check @AckermannHF.SetOrdinalRepCertificate
#check @AckermannHF.SetOrdinalRep
#check @AckermannHF.HF_setOrdinalRepCertificateAt_exact
#check @AckermannHF.HF_setOrdinalRepAt_exact
#check @AckermannHF.SetOrdinalRep_code_eq
#check @AckermannHF.standardSetOrdinalRepGraph
#check @AckermannHF.mem_standardSetOrdinalRepGraph_iff
#check @AckermannHF.standardSetOrdinalRepGraph_certificate
#check @AckermannHF.SetOrdinalRep_exists
#check @AckermannHF.SetOrdinalRep_iff
#check @AckermannHF.hfCompositeAt
#check @AckermannHF.hfCompositeAt_id
#check @AckermannHF.rename_HF_compositeMemAt
#check @AckermannHF.HF_compositeMemAt_free
#check @AckermannHF.rename_HF_ordinalLikeAt
#check @AckermannHF.rename_HF_setOrdinalRepCertificateAt
#check @AckermannHF.rename_HF_setOrdinalRepAt
#check @AckermannHF.HF_setOrdinalRepCertificateAt_free
#check @AckermannHF.HF_setOrdinalRepAt_free
#check @AckermannHF.BProv_HF_setOrdinalRepAt_of_set_eq
#check @AckermannHF.BProv_HF_setOrdinalRepAt_of_code_eq
#check @AckermannHF.hfCompositeAt_mem
#check @AckermannHF.BProv_hfCompositeAt_eq_of_eq
#check @AckermannHF.BProv_eq_of_hfCompositeAt_eq
#check @AckermannHF.SetOrdinalRepresentationProofs
#check @AckermannHF.BProv_HFFin_setOrdinalRep_total
#check @AckermannHF.BProv_HFFin_setOrdinalRep_range
#check @AckermannHF.BProv_HFFin_setOrdinalRep_code_functional
#check @AckermannHF.BProv_HFFin_setOrdinalRep_set_injective
#check @AckermannHF.BProv_HFFin_setOrdinalRep_mem_exact
#check AckermannHF.setOrdinalRepresentationProofs
#check @AckermannHF.BProv_HFFin_hfCompositeAt_mem_of_representations
#check @AckermannHF.BProv_HFFin_hfCompositeAt_eq_of_representations
#check @AckermannHF.BProv_fIff_refl
#check @AckermannHF.BProv_fIff_imp_congr
#check @AckermannHF.BProv_fIff_and_congr
#check @AckermannHF.BProv_fIff_or_congr
#check @AckermannHF.HFQuantifierFree
#check @AckermannHF.BProv_HFFin_hfCompositeAt_iff_of_quantifierFree
#check @AckermannHF.hfCompositeAt_all
#check @AckermannHF.hfCompositeAt_ex
#check @AckermannHF.rangeRawMap
#check @AckermannHF.rangeCodedMap
#check @AckermannHF.totalRawMap
#check @AckermannHF.totalCodedMap
#check @AckermannHF.rename_hfCompositeAt
#check @AckermannHF.rename_succ_hfCompositeAt_up
#check @AckermannHF.rename_succ_rawBody
#check @AckermannHF.inst_range_rawBody
#check @AckermannHF.inst_total_codedBody
#check @AckermannHF.BProv_rename_of_sentences
#check @AckermannHF.BProv_HFFin_rep_exists_of_ordinalLike
#check @AckermannHF.BProv_HFFin_ordinalLike_of_rep
#check @AckermannHF.BProv_HFFin_hfCompositeAt_all_forward
#check @AckermannHF.BProv_HFFin_hfCompositeAt_all_reverse
#check @AckermannHF.BProv_HFFin_hfCompositeAt_all
#check @AckermannHF.BProv_HFFin_hfCompositeAt_ex_forward
#check @AckermannHF.BProv_HFFin_hfCompositeAt_ex_reverse
#check @AckermannHF.BProv_HFFin_hfCompositeAt_ex
#check @AckermannHF.BProv_HFFin_hfCompositeAt_iff
#check @AckermannHF.HFCompositeStructuralProofs
#check @AckermannHF.HFCompositeStructuralProofs_of_representationProofs
#check @AckermannHF.BProv_HFFin_hf_roundTrip_of_structuralProofs
#check @AckermannHF.BProv_HFFin_hf_roundTrip_of_representationProofs
#check @AckermannHF.PAHFFinDeductiveBiInterpretationCertificate_of_structuralProofs
#check @AckermannHF.PAHFFinDeductiveBiInterpretationCertificate_of_graphRepresentationProofs
#check @AckermannHF.ModelSetOrdinalRepCertificate
#check @AckermannHF.HF_setOrdinalRepCertificateAt_model
#check @AckermannHF.ModelSetOrdinalRep
#check @AckermannHF.HF_setOrdinalRepAt_model
#check @AckermannHF.BProv_HFFin_setOrdinalRep_total_of_model_total
#check @AckermannHF.NoCompositeMembersOfEmpty
#check @AckermannHF.ModelCompositeMem
#check @AckermannHF.HF_compositeMemAt_01_model
#check @AckermannHF.HF_compositeMemAt_02_model
#check @AckermannHF.emptySetOrdinalRepGraph
#check @AckermannHF.emptySetOrdinalRepGraph_root
#check @AckermannHF.ModelSetOrdinalRep_empty
#check @AckermannHF.PA_BProv_no_hfMem_of_eq_zero
#check @AckermannHF.NoCompositeMembersOfEmpty_of_HFFinAx_s
#check @AckermannHF.ModelSetOrdinalRep_empty_of_HFFinAx_s
#check @AckermannHF.BProv_HFFin_setOrdinalRep_total_of_empty
#check @AckermannHF.ModelSetOrdinalRepAdjoinData
#check @AckermannHF.adjoinSetOrdinalRepGraph
#check @AckermannHF.adjoinSetOrdinalRepGraph_old
#check @AckermannHF.adjoinSetOrdinalRepGraph_new
#check @AckermannHF.ModelSetOrdinalRepCertificate_adjoin
#check @AckermannHF.ModelSetOrdinalRepCertificate_changeEnv
#check @AckermannHF.ModelSetOrdinalRepMergeResult
#check @AckermannHF.ModelSetOrdinalRepMergeLaw
#check @AckermannHF.ModelSetOrdinalRepAdjoinCodeData
#check @AckermannHF.ModelSetOrdinalRep_adjoin_of_merge
#check @AckermannHF.ModelSetOrdinalRep_changeEnv
#check @AckermannHF.canonicalRepEnv
#check @AckermannHF.HasSetOrdinalRep
#check @AckermannHF.setOrdinalRepExists_model
#check @AckermannHF.ModelCompositeAdjoinCodeData
#check @AckermannHF.ModelCompositeAdjoinCodeData_exists_finite
#check @AckermannHF.ModelCompositeAdjoinCodeLaw
#check @AckermannHF.ModelCompositeAdjoinCodeLaw_finite
#check @AckermannHF.HasSetOrdinalRep_adjoin_of_merge_code
#check @AckermannHF.HF_induction_form_spec
#check @AckermannHF.HasSetOrdinalRep_total_of_empty_adjoin
#check @AckermannHF.BProv_HFFin_setOrdinalRep_total_of_merge_code
#check @AckermannHF.StandardModelInterpretationCertificateFor
#check @AckermannHF.StandardModelInterpretationCertificate
#check @AckermannHF.StandardModelFiniteInterpretationCertificate
#check @AckermannHF.standardModelInterpretation
#check @AckermannHF.standardModelFiniteInterpretation
#check @AckermannHF.PA_standard_model_interpretable_with_HF
#check @AckermannHF.PA_standard_model_interpretable_with_HFFin
#check @AckermannHF.PA_biinterpretable_with_HF_standard
#check @AckermannHF.PA_biinterpretable_with_HFFin_standard
#check AckermannHF.paHFFinDeductiveBiInterpretation
#check AckermannHF.PA_biinterpretable_with_HFFin
#print axioms PA.Formula.ordinalCodeTermMulCompatibility
#print axioms PA.Formula.ordinalCodeGraphProofs
#print axioms AckermannHF.setOrdinalRepresentationProofs
#print axioms AckermannHF.paHFFinDeductiveBiInterpretation
#print axioms AckermannHF.PA_biinterpretable_with_HFFin
#print axioms PA.Formula.sat_axiom
#print axioms PA.Formula.sat_axiom_s
#print axioms PA.Formula.soundness
#print axioms PA.Formula.soundness_BProv
#print axioms AckermannHF.sat_HF_model
#print axioms AckermannHF.standard_sat_HF
#print axioms AckermannHF.standard_sat_HFFin
#print axioms AckermannHF.PA_standard_model_interpretable_with_HF
#print axioms AckermannHF.PA_standard_model_interpretable_with_HFFin
#print axioms AckermannHF.PA_biinterpretable_with_HF_standard
#print axioms AckermannHF.PA_biinterpretable_with_HFFin_standard
