import BusyBeaver.BB4.Certificates.R13.C14.Guided.Common

set_option maxRecDepth 10000

namespace SetTheory.BusyBeaver.BB4.Certificates.C14Guided

open Certificates

def work_a02_a03_a01 : Guided.Work :=
  after [a02, a03, a01]

def certificate_a02_a03_a01 : Guided.Certificate :=
  Guided.Certificate.branch16
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.branch16
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool3)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.bool2)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)))
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.branch16
      (Guided.Certificate.bool3)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.branch16
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete)
        (Guided.Certificate.complete))
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1)
      (Guided.Certificate.bool1))
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool2)
    (Guided.Certificate.bool3)

theorem verified_a02_a03_a01 :
    work_a02_a03_a01.check certificate_a02_a03_a01 = true := by
  decide

end SetTheory.BusyBeaver.BB4.Certificates.C14Guided
