import PAFiniteBasisReduction.FiniteBetaCoding
import PAFiniteBasisReduction.NonstandardHFFin

/-!
# Peano arithmetic has two non-isomorphic models

The semantic objects in this file are raw first-order arithmetic structures
which satisfy every member of the sealed PA axiom schema.  This distinction is
essential: `PA.Model` contains induction for every Lean predicate and is thus a
much stronger, categorical, meta-level interface.

The standard model is generated by its standard numerals.  Compactness, via
`NonstandardHFFin`, supplies another first-order PA model with an element above
every standard numeral.  Being numeral-generated is invariant under arithmetic
isomorphism, so the two models cannot be isomorphic.
-/

namespace LeanProofs
namespace PAFiniteBasisReduction

open SetTheory PA

universe u v

namespace TwoNonisomorphicModels

open FiniteSkolemCut NonstandardHFFin

/-- A genuine first-order model of PA: a raw arithmetic structure in which
every sealed PA axiom, including every first-order induction instance, is
semantically valid. -/
structure FirstOrderPAModel where
  Carrier : Type
  preModel : PA.PreModel Carrier
  satisfiesPA : RawPASatisfies preModel

/-- Isomorphism of raw first-order arithmetic structures. -/
structure RawPAIso {alpha : Type u} {beta : Type v}
    (M : PA.PreModel alpha) (N : PA.PreModel beta) where
  toFun : alpha -> beta
  invFun : beta -> alpha
  left_inv : forall x, invFun (toFun x) = x
  right_inv : forall y, toFun (invFun y) = y
  map_zero : toFun M.zero = N.zero
  map_succ : forall x, toFun (M.succ x) = N.succ (toFun x)
  map_add : forall x y, toFun (M.add x y) = N.add (toFun x) (toFun y)
  map_mul : forall x y, toFun (M.mul x y) = N.mul (toFun x) (toFun y)

/-- Every standard numeral is preserved by an arithmetic isomorphism. -/
theorem RawPAIso.map_numeralValue {alpha : Type u} {beta : Type v}
    {M : PA.PreModel alpha} {N : PA.PreModel beta} (i : RawPAIso M N) :
    forall n, i.toFun (PA.Term.numeralValue M n) =
      PA.Term.numeralValue N n
  | 0 => i.map_zero
  | n + 1 => by
      simp only [PA.Term.numeralValue]
      rw [i.map_succ, i.map_numeralValue n]

/-- A raw arithmetic structure is numeral-generated when every element is the
value of an externally standard numeral. -/
def NumeralGenerated {alpha : Type u} (M : PA.PreModel alpha) : Prop :=
  forall x, exists n, x = PA.Term.numeralValue M n

/-- Numeral generation is invariant under arithmetic isomorphism. -/
theorem numeralGenerated_of_iso {alpha : Type u} {beta : Type v}
    {M : PA.PreModel alpha} {N : PA.PreModel beta}
    (i : RawPAIso M N) (hM : NumeralGenerated M) : NumeralGenerated N := by
  intro y
  rcases hM (i.invFun y) with ⟨n, hn⟩
  refine ⟨n, ?_⟩
  calc
    y = i.toFun (i.invFun y) := (i.right_inv y).symm
    _ = i.toFun (PA.Term.numeralValue M n) := congrArg i.toFun hn
    _ = PA.Term.numeralValue N n := i.map_numeralValue n

/-- The usual natural-number structure, packaged at the genuine first-order
PA semantic boundary. -/
def standardPAModel : FirstOrderPAModel where
  Carrier := Nat
  preModel := PA.natModel
  satisfiesPA := fun e phi hphi =>
    PA.Formula.sat_axiom_s PA.natModel e phi hphi

theorem standardPAModel_numeralGenerated :
    NumeralGenerated standardPAModel.preModel := by
  intro n
  exact ⟨n, (PA.Term.numeralValue_natModel n).symm⟩

/-- Compactness supplies a first-order PA model with an element strictly above
every standard numeral.  In particular, that model is not numeral-generated. -/
theorem nonstandardPAModel_exists :
    exists (M : FirstOrderPAModel) (star : M.Carrier),
      (forall n, RawLt M.preModel (PA.Term.numeralValue M.preModel n) star) /\
      ¬NumeralGenerated M.preModel := by
  rcases nonstandardHFFin_fofam_exists with ⟨V, H, star, hstar⟩
  let raw := AckermannHF.PAInHF.fofamPAPreModel H
  have hPA : RawPASatisfies raw := fun e phi hphi =>
    AckermannHF.PAInHF.fofam_PA_Ax_s_valid H phi e hphi
  have habove : forall n, RawLt raw (PA.Term.numeralValue raw n) star := by
    intro n
    have hs : PA.Formula.Sat raw (fun _ => star) (paLtNumeralAt n) := hstar n
    have hlt := (sat_ltTermAt_iff_raw raw (PA.Term.numeral n)
      (PA.Term.var 0) (fun _ => star)).mp hs
    simpa [PA.Term.eval_numeral, PA.Term.eval] using hlt
  let M : FirstOrderPAModel := {
    Carrier := AckermannHF.PAInHF.FOFAMOrdinal H
    preModel := raw
    satisfiesPA := hPA
  }
  refine ⟨M, star, habove, ?_⟩
  intro hgenerated
  rcases hgenerated star with ⟨n, hn⟩
  have hlt := habove n
  rw [← hn] at hlt
  exact not_rawLt_self hPA star hlt

/-- Headline theorem: first-order Peano arithmetic has at least two
non-isomorphic models. -/
theorem peano_arithmetic_has_two_nonisomorphic_models :
    exists M N : FirstOrderPAModel,
      ¬Nonempty (RawPAIso M.preModel N.preModel) := by
  rcases nonstandardPAModel_exists with ⟨N, star, habove, hnotGenerated⟩
  refine ⟨standardPAModel, N, ?_⟩
  rintro ⟨i⟩
  exact hnotGenerated (numeralGenerated_of_iso i
    standardPAModel_numeralGenerated)

end TwoNonisomorphicModels
end PAFiniteBasisReduction
end LeanProofs
