From RiemannHypothesis Require Import PAStatement.

Check mertensRiemannHypothesisSentence.
Check mertensRiemannHypothesisSentence_sentence.
Print Assumptions mertensRiemannHypothesisSentence_sentence.
