import LeanProofs.A198683
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Symbolic identities for OEIS A198683 at n = 12

The local n = 12 probe table has a 14-member class whose numerical values are
near `i^i = exp(-pi/2)`.  This module starts turning that heuristic cluster
analysis into exact Lean facts.  The first theorem below proves one of the
cluster representatives symbolically, using only principal-power identities in
the small island generated by `i`, `i^i`, and `i^(i^i)`.

The definitions are intentionally local to this module: `LeanProofs.A198683`
keeps most of its small-value lemmas private because they serve the direct
`n <= 7` cardinality proof there.
-/

namespace LeanProofs

namespace A198683N12Symbolic

noncomputable section

open Complex

private def rho : ℝ := Real.exp (-(Real.pi / 2))

private def theta : ℝ := Real.pi / 2 * rho

/-- The exact value of `i^i`. -/
def q : ℂ := (rho : ℂ)

/-- The exact value of `i^(-i)`, reciprocal to `q`. -/
def qInv : ℂ := ((Real.exp (Real.pi / 2) : ℝ) : ℂ)

/-- The exact value `i^(i^i)`. -/
def u : ℂ := principalPow Complex.I q

/-- The reciprocal of `(i^i)^(i^i)`. -/
def qqInv : ℂ := ((Real.exp theta : ℝ) : ℂ)

private theorem theta_pos : 0 < theta := by
  dsimp [theta, rho]
  positivity

private theorem theta_lt_pi_div_two : theta < Real.pi / 2 := by
  dsimp [theta, rho]
  have hexp_lt_one : Real.exp (-(Real.pi / 2)) < 1 := by
    exact Real.exp_lt_one_iff.mpr (by linarith [Real.pi_pos])
  simpa using mul_lt_mul_of_pos_left hexp_lt_one (show 0 < Real.pi / 2 by positivity)

private theorem neg_pi_lt_theta : -Real.pi < theta := by
  linarith [theta_pos, Real.pi_pos]

private theorem theta_le_pi : theta ≤ Real.pi := by
  linarith [theta_lt_pi_div_two, Real.pi_pos]

private theorem log_I_real :
    Complex.log Complex.I = ((Real.pi / 2 : ℝ) : ℂ) * Complex.I := by
  rw [Complex.log_I]
  norm_num

private theorem log_q : Complex.log q = (-(Real.pi / 2) : ℂ) := by
  dsimp [q, rho]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]
  norm_num

private theorem log_neg_I_real :
    Complex.log (-Complex.I) = (-(Real.pi / 2 : ℝ) : ℂ) * Complex.I := by
  rw [Complex.log_neg_I]
  norm_num

/-- `i^i = exp(-pi/2)`. -/
theorem I_pow_I_eq_q : principalPow Complex.I Complex.I = q := by
  dsimp [principalPow, q, rho]
  rw [log_I_real]
  rw [show (((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * Complex.I =
      (-(Real.pi / 2) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑Real.pi / 2) : ℂ) = ↑(-(Real.pi / 2)) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem I_pow_q_eq_u : principalPow Complex.I q = u := rfl

private theorem I_pow_q_eq_exp_theta :
    principalPow Complex.I q = Complex.exp ((theta : ℂ) * Complex.I) := by
  dsimp [principalPow, q, theta]
  rw [log_I_real]
  congr 1
  apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, rho]

private theorem log_u : Complex.log u = (theta : ℂ) * Complex.I := by
  dsimp [u]
  rw [I_pow_q_eq_exp_theta]
  rw [Complex.log_exp]
  · simpa [Complex.mul_im] using neg_pi_lt_theta
  · simpa [Complex.mul_im] using theta_le_pi

private theorem theta_mul_exp_pi_div_two :
    theta * Real.exp (Real.pi / 2) = Real.pi / 2 := by
  calc
    theta * Real.exp (Real.pi / 2)
        = Real.pi / 2 * (Real.exp (-(Real.pi / 2)) * Real.exp (Real.pi / 2)) := by
            dsimp [theta, rho]
            ring
    _ = Real.pi / 2 * 1 := by
            rw [← Real.exp_add]
            rw [show -(Real.pi / 2) + Real.pi / 2 = 0 by ring]
            rw [Real.exp_zero]
    _ = Real.pi / 2 := by ring

private theorem exp_pi_div_two_mul_rho :
    Real.exp (Real.pi / 2) * rho = 1 := by
  dsimp [rho]
  rw [← Real.exp_add]
  rw [show Real.pi / 2 + -(Real.pi / 2) = 0 by ring]
  rw [Real.exp_zero]

private theorem neg_pi_div_two_exp_mul_rho :
    (-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho =
        -(Real.pi / 2) * (Real.exp (Real.pi / 2) * rho) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_pi_div_two_mul_rho]
    _ = -(Real.pi / 2) := by ring

private theorem exp_neg_theta_mul_exp_theta :
    Real.exp (-theta) * Real.exp theta = 1 := by
  rw [← Real.exp_add]
  rw [show -theta + theta = 0 by ring]
  rw [Real.exp_zero]

private theorem exp_theta_mul_exp_neg_theta :
    Real.exp theta * Real.exp (-theta) = 1 := by
  rw [← Real.exp_add]
  rw [show theta + -theta = 0 by ring]
  rw [Real.exp_zero]

private theorem neg_pi_div_two_exp_neg_theta_mul_exp_theta :
    (-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta =
        -(Real.pi / 2) * (Real.exp (-theta) * Real.exp theta) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_neg_theta_mul_exp_theta]
    _ = -(Real.pi / 2) := by ring

private theorem neg_pi_div_two_exp_theta_mul_exp_neg_theta :
    (-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta) = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta) =
        -(Real.pi / 2) * (Real.exp theta * Real.exp (-theta)) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_theta_mul_exp_neg_theta]
    _ = -(Real.pi / 2) := by ring

/-- `(i^(i^i))^(i^(-i)) = i`. -/
theorem u_pow_qInv_eq_I : principalPow u qInv = Complex.I := by
  dsimp [principalPow, qInv]
  rw [log_u]
  rw [show ((theta : ℂ) * Complex.I) * ((Real.exp (Real.pi / 2) : ℝ) : ℂ) =
      ((Real.pi / 2 : ℝ) : ℂ) * Complex.I by
    rw [show ((theta : ℂ) * Complex.I) * ((Real.exp (Real.pi / 2) : ℝ) : ℂ) =
        ((theta * Real.exp (Real.pi / 2) : ℝ) : ℂ) * Complex.I by
      apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
    rw [theta_mul_exp_pi_div_two]]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `(i^(i^i))^(-i) = exp(theta)`, the reciprocal of `(i^i)^(i^i)`. -/
theorem u_pow_neg_I_eq_qqInv : principalPow u (-Complex.I) = qqInv := by
  dsimp [principalPow, qqInv]
  rw [log_u]
  rw [show ((theta : ℂ) * Complex.I) * -Complex.I = (theta : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp theta).symm

/-- `(i^i)^i = -i`. -/
theorem q_pow_I_eq_neg_I : principalPow q Complex.I = -Complex.I := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `i^(-i) = exp(pi/2)`. -/
theorem I_pow_neg_I_eq_qInv : principalPow Complex.I (-Complex.I) = qInv := by
  dsimp [principalPow, qInv]
  rw [log_I_real]
  rw [show (((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * -Complex.I =
      ((Real.pi / 2 : ℝ) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (Real.pi / 2)).symm

/-- `(i^i)^(-i) = i`. -/
theorem q_pow_neg_I_eq_I : principalPow q (-Complex.I) = Complex.I := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  rw [show (↑(-(Real.pi / 2)) : ℂ) * -Complex.I =
      ((Real.pi / 2 : ℝ) : ℂ) * Complex.I by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `(-i)^(-i) = exp(-pi/2) = i^i`. -/
theorem neg_I_pow_neg_I_eq_q : principalPow (-Complex.I) (-Complex.I) = q := by
  dsimp [principalPow, q, rho]
  rw [log_neg_I_real]
  rw [show (((-(Real.pi / 2 : ℝ) : ℂ) * Complex.I) * -Complex.I) =
      (-(Real.pi / 2) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑Real.pi / 2) : ℂ) = ↑(-(Real.pi / 2)) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_q_eq_exp_neg_theta :
    principalPow q q = (Real.exp (-theta) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * q = ↑(-theta) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, q, theta]]
  exact (Complex.ofReal_exp (-theta)).symm

private theorem log_q_pow_q :
    Complex.log (principalPow q q) = (-theta : ℂ) := by
  rw [q_pow_q_eq_exp_neg_theta]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]
  norm_num

/-- `((i^i)^(i^i))^(i^(-i)) = i^i`. -/
theorem q_pow_q_pow_qInv_eq_q :
    principalPow (principalPow q q) qInv = q := by
  change Complex.exp (Complex.log (principalPow q q) * qInv) = q
  rw [log_q_pow_q]
  rw [show ((-theta : ℂ) * qInv) =
      (-(theta * Real.exp (Real.pi / 2)) : ℂ) by
    dsimp [qInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑theta * ↑(Real.exp (Real.pi / 2))) : ℂ) =
      (↑(-(theta * Real.exp (Real.pi / 2))) : ℂ) by norm_num]
  rw [theta_mul_exp_pi_div_two]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qInv_eq_exp :
    principalPow q qInv =
      (Real.exp (-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * qInv =
      (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) by
    dsimp [qInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp (Real.pi / 2))).symm

private theorem log_q_pow_qInv :
    Complex.log (principalPow q qInv) =
      (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) := by
  rw [q_pow_qInv_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `((i^i)^(i^(-i)))^(i^i) = i^i`. -/
theorem q_pow_qInv_pow_q_eq_q :
    principalPow (principalPow q qInv) q = q := by
  change Complex.exp (Complex.log (principalPow q qInv) * q) = q
  rw [log_q_pow_qInv]
  rw [show (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) * q =
      (↑((-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, q]]
  rw [neg_pi_div_two_exp_mul_rho]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qq_eq_exp :
    principalPow q (principalPow q q) =
      (Real.exp (-(Real.pi / 2) * Real.exp (-theta)) : ℂ) := by
  change Complex.exp (Complex.log q * principalPow q q) =
    (Real.exp (-(Real.pi / 2) * Real.exp (-theta)) : ℂ)
  rw [q_pow_q_eq_exp_neg_theta]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * ((Real.exp (-theta) : ℝ) : ℂ) =
      (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp (-theta))).symm

private theorem log_q_pow_qq :
    Complex.log (principalPow q (principalPow q q)) =
      (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) := by
  rw [q_pow_qq_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `(i^i)^((i^i)^(i^i))`, raised to `(i^(i^i))^(-i)`, is `i^i`. -/
theorem q_pow_qq_pow_qqInv_eq_q :
    principalPow (principalPow q (principalPow q q)) qqInv = q := by
  change Complex.exp (Complex.log (principalPow q (principalPow q q)) * qqInv) = q
  rw [log_q_pow_qq]
  rw [show (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) * qqInv =
      (↑((-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta) : ℂ) by
    dsimp [qqInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [neg_pi_div_two_exp_neg_theta_mul_exp_theta]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qqInv_eq_exp :
    principalPow q qqInv =
      (Real.exp (-(Real.pi / 2) * Real.exp theta) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * qqInv =
      (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) by
    dsimp [qqInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp theta)).symm

private theorem log_q_pow_qqInv :
    Complex.log (principalPow q qqInv) =
      (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) := by
  rw [q_pow_qqInv_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `(i^i)^((i^(i^i))^(-i))`, raised to `(i^i)^(i^i)`, is `i^i`. -/
theorem q_pow_qqInv_pow_qq_eq_q :
    principalPow (principalPow q qqInv) (principalPow q q) = q := by
  change Complex.exp (Complex.log (principalPow q qqInv) * principalPow q q) = q
  rw [log_q_pow_qqInv]
  rw [q_pow_q_eq_exp_neg_theta]
  rw [show (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) * ((Real.exp (-theta) : ℝ) : ℂ) =
      (↑((-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta)) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [neg_pi_div_two_exp_theta_mul_exp_neg_theta]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

/--
Representative `idx = 562` from the n = 12 near-`i^i` probe class, written
with the same principal-power expression as the local trace:

`i^((i^i)^((i^i)^((i^(i^i))^(i^((i^i)^i)))))`.
-/
def nearIPowerI562 : ℂ :=
  principalPow Complex.I
    (principalPow q
      (principalPow q
        (principalPow (principalPow Complex.I q)
          (principalPow Complex.I (principalPow q Complex.I)))))

/-- Candidate `562` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI562_eq_q : nearIPowerI562 = q := by
  dsimp [nearIPowerI562]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 1901` from the same n = 12 near-`i^i` probe class:

`((i^i)^i)^((i^i)^((i^(i^i))^(i^((i^i)^i))))`.
-/
def nearIPowerI1901 : ℂ :=
  principalPow (principalPow q Complex.I)
    (principalPow q
      (principalPow (principalPow Complex.I q)
        (principalPow Complex.I (principalPow q Complex.I))))

/-- Candidate `1901` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI1901_eq_q : nearIPowerI1901 = q := by
  dsimp [nearIPowerI1901]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [neg_I_pow_neg_I_eq_q]

/--
Representative `idx = 2161` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^i))^(i^((i^i)^((i^i)^((i^i)^i))))`.
-/
def nearIPowerI2161 : ℂ :=
  principalPow (principalPow q q)
    (principalPow Complex.I
      (principalPow q
        (principalPow q (principalPow q Complex.I))))

/-- Candidate `2161` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2161_eq_q : nearIPowerI2161 = q := by
  dsimp [nearIPowerI2161]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_q_pow_qInv_eq_q]

/--
Representative `idx = 2378` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^i))^((i^(i^i))^(i^((i^i)^i)))`.
-/
def nearIPowerI2378 : ℂ :=
  principalPow (principalPow q (principalPow q Complex.I))
    (principalPow (principalPow Complex.I q)
      (principalPow Complex.I (principalPow q Complex.I)))

/-- Candidate `2378` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2378_eq_q : nearIPowerI2378 = q := by
  dsimp [nearIPowerI2378]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 2581` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^i)))^(i^((i^i)^((i^i)^i)))`.
-/
def nearIPowerI2581 : ℂ :=
  principalPow (principalPow q (principalPow Complex.I (principalPow q Complex.I)))
    (principalPow Complex.I (principalPow q (principalPow q Complex.I)))

/-- Candidate `2581` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2581_eq_q : nearIPowerI2581 = q := by
  dsimp [nearIPowerI2581]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]
  rw [q_pow_qInv_pow_q_eq_q]

/--
Representative `idx = 2603` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^(i^i)))^((i^(i^i))^((i^i)^i))`.
-/
def nearIPowerI2603 : ℂ :=
  principalPow (principalPow q (principalPow q q))
    (principalPow (principalPow Complex.I q) (principalPow q Complex.I))

/-- Candidate `2603` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2603_eq_q : nearIPowerI2603 = q := by
  dsimp [nearIPowerI2603]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_q_eq_u]
  rw [u_pow_neg_I_eq_qqInv]
  rw [q_pow_qq_pow_qqInv_eq_q]

/--
Representative `idx = 2847` from the n = 12 near-`i^i` probe class:

`((i^(i^i))^(i^((i^i)^i)))^((i^i)^((i^i)^i))`.
-/
def nearIPowerI2847 : ℂ :=
  principalPow
    (principalPow (principalPow Complex.I q)
      (principalPow Complex.I (principalPow q Complex.I)))
    (principalPow q (principalPow q Complex.I))

/-- Candidate `2847` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2847_eq_q : nearIPowerI2847 = q := by
  dsimp [nearIPowerI2847]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 3035` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^((i^i)^i))))^(i^((i^i)^i))`.
-/
def nearIPowerI3035 : ℂ :=
  principalPow
    (principalPow q
      (principalPow Complex.I (principalPow q (principalPow q Complex.I))))
    (principalPow Complex.I (principalPow q Complex.I))

/-- Candidate `3035` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3035_eq_q : nearIPowerI3035 = q := by
  dsimp [nearIPowerI3035]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_q_pow_qInv_eq_q]

/--
Representative `idx = 3057` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^(i^i))^((i^i)^i)))^((i^i)^(i^i))`.
-/
def nearIPowerI3057 : ℂ :=
  principalPow
    (principalPow q
      (principalPow (principalPow Complex.I q) (principalPow q Complex.I)))
    (principalPow q q)

/-- Candidate `3057` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3057_eq_q : nearIPowerI3057 = q := by
  dsimp [nearIPowerI3057]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_q_eq_u]
  rw [u_pow_neg_I_eq_qqInv]
  rw [q_pow_qqInv_pow_qq_eq_q]

/--
Representative `idx = 3352` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^(i^i))^(i^((i^i)^i))))^((i^i)^i)`.
-/
def nearIPowerI3352 : ℂ :=
  principalPow
    (principalPow q
      (principalPow (principalPow Complex.I q)
        (principalPow Complex.I (principalPow q Complex.I))))
    (principalPow q Complex.I)

/-- Candidate `3352` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3352_eq_q : nearIPowerI3352 = q := by
  dsimp [nearIPowerI3352]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [neg_I_pow_neg_I_eq_q]

/--
Representative `idx = 3731` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^((i^i)^((i^i)^i)))))^(i^i)`.
-/
def nearIPowerI3731 : ℂ :=
  principalPow
    (principalPow q
      (principalPow Complex.I
        (principalPow q (principalPow q (principalPow q Complex.I)))))
    q

/-- Candidate `3731` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3731_eq_q : nearIPowerI3731 = q := by
  dsimp [nearIPowerI3731]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_qInv_pow_q_eq_q]

/--
Representative `idx = 4549` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^((i^(i^i))^(i^((i^i)^i)))))^i`.
-/
def nearIPowerI4549 : ℂ :=
  principalPow
    (principalPow q
      (principalPow q
        (principalPow (principalPow Complex.I q)
          (principalPow Complex.I (principalPow q Complex.I)))))
    Complex.I

/-- Candidate `4549` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI4549_eq_q : nearIPowerI4549 = q := by
  dsimp [nearIPowerI4549]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

end

end A198683N12Symbolic

end LeanProofs
