import LeanProofs.A198683
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Symbolic identities for OEIS A198683 at n = 12

The local n = 12 probe table has a 14-member class whose numerical values are
near `i^i = exp(-pi/2)`.  This module starts turning that heuristic cluster
analysis into exact Lean facts.  It also records positive-real
principal-power associativity proofs for the near-zero doubleton `{2207, 3777}`
and the retained near-one pair `{1404, 4239}`.
The identities use only principal-power reductions in the small islands
generated by `i`, `i^i`, and `i^(i^i)`.

The definitions are intentionally local to this module: `LeanProofs.A198683`
keeps most of its small-value lemmas private because they serve the direct
`n <= 7` cardinality proof there.
-/

namespace LeanProofs

namespace A198683N12Symbolic

noncomputable section

open Complex

private def rho : ℝ := Real.exp (-(Real.pi / 2))

private def theta : ℝ := Real.pi / 2 * rho

/-- The exact value of `i^i`. -/
def q : ℂ := (rho : ℂ)

/-- The exact value of `i^(-i)`, reciprocal to `q`. -/
def qInv : ℂ := ((Real.exp (Real.pi / 2) : ℝ) : ℂ)

/-- The exact value `i^(i^i)`. -/
def u : ℂ := principalPow Complex.I q

/-- The reciprocal of `(i^i)^(i^i)`. -/
def qqInv : ℂ := ((Real.exp theta : ℝ) : ℂ)

/-- The exact value `i^(i^(i^i))`. -/
def v : ℂ := principalPow Complex.I u

/-- The reciprocal-side value `(-i)^(i^(i^i))`. -/
def w : ℂ := principalPow (-Complex.I) u

private def sigma : ℝ := Real.exp ((Real.pi / 2) * Real.exp (Real.pi / 2))

private def tau : ℝ := Real.exp (-(Real.pi / 2) * sigma)

/--
The exact positive-real subtree
`(i^((i^i)^i))^(i^((i^i)^i))`, used by two n = 12 tentative classes.
-/
def nearProbeR : ℂ :=
  principalPow
    (principalPow Complex.I (principalPow q Complex.I))
    (principalPow Complex.I (principalPow q Complex.I))

/-- The exact tiny positive-real subtree `(i^i)^nearProbeR`. -/
def nearProbeS : ℂ := principalPow q nearProbeR

private theorem theta_pos : 0 < theta := by
  dsimp [theta, rho]
  positivity

private theorem theta_lt_pi_div_two : theta < Real.pi / 2 := by
  dsimp [theta, rho]
  have hexp_lt_one : Real.exp (-(Real.pi / 2)) < 1 := by
    exact Real.exp_lt_one_iff.mpr (by linarith [Real.pi_pos])
  simpa using mul_lt_mul_of_pos_left hexp_lt_one (show 0 < Real.pi / 2 by positivity)

private theorem neg_pi_lt_theta : -Real.pi < theta := by
  linarith [theta_pos, Real.pi_pos]

private theorem theta_le_pi : theta ≤ Real.pi := by
  linarith [theta_lt_pi_div_two, Real.pi_pos]

private theorem log_I_real :
    Complex.log Complex.I = ((Real.pi / 2 : ℝ) : ℂ) * Complex.I := by
  rw [Complex.log_I]
  norm_num

private theorem log_q : Complex.log q = (-(Real.pi / 2) : ℂ) := by
  dsimp [q, rho]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]
  norm_num

private theorem log_neg_I_real :
    Complex.log (-Complex.I) = (-(Real.pi / 2 : ℝ) : ℂ) * Complex.I := by
  rw [Complex.log_neg_I]
  norm_num

/-- `i^i = exp(-pi/2)`. -/
theorem I_pow_I_eq_q : principalPow Complex.I Complex.I = q := by
  dsimp [principalPow, q, rho]
  rw [log_I_real]
  rw [show (((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * Complex.I =
      (-(Real.pi / 2) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑Real.pi / 2) : ℂ) = ↑(-(Real.pi / 2)) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem I_pow_q_eq_u : principalPow Complex.I q = u := rfl

private theorem I_pow_q_eq_exp_theta :
    principalPow Complex.I q = Complex.exp ((theta : ℂ) * Complex.I) := by
  dsimp [principalPow, q, theta]
  rw [log_I_real]
  congr 1
  apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, rho]

private theorem log_u : Complex.log u = (theta : ℂ) * Complex.I := by
  dsimp [u]
  rw [I_pow_q_eq_exp_theta]
  rw [Complex.log_exp]
  · simpa [Complex.mul_im] using neg_pi_lt_theta
  · simpa [Complex.mul_im] using theta_le_pi

private theorem theta_mul_exp_pi_div_two :
    theta * Real.exp (Real.pi / 2) = Real.pi / 2 := by
  calc
    theta * Real.exp (Real.pi / 2)
        = Real.pi / 2 * (Real.exp (-(Real.pi / 2)) * Real.exp (Real.pi / 2)) := by
            dsimp [theta, rho]
            ring
    _ = Real.pi / 2 * 1 := by
            rw [← Real.exp_add]
            rw [show -(Real.pi / 2) + Real.pi / 2 = 0 by ring]
            rw [Real.exp_zero]
    _ = Real.pi / 2 := by ring

private theorem exp_pi_div_two_gt_24_div_5 :
    (24 : ℝ) / 5 < Real.exp (Real.pi / 2) := by
  have hpi : (157 : ℝ) / 100 < Real.pi / 2 := by
    linarith [Real.pi_gt_d2]
  have hsum_le :
      (∑ i ∈ Finset.range 7, ((157 : ℝ) / 100) ^ i / (i.factorial : ℝ)) ≤
        Real.exp ((157 : ℝ) / 100) :=
    Real.sum_le_exp_of_nonneg (by norm_num) 7
  have hsum_gt :
      (24 : ℝ) / 5 <
        ∑ i ∈ Finset.range 7, ((157 : ℝ) / 100) ^ i / (i.factorial : ℝ) := by
    norm_num [Finset.sum_range_succ]
  exact hsum_gt.trans_le (hsum_le.trans ((Real.exp_le_exp).2 hpi.le))

private theorem exp_pi_div_two_mul_rho :
    Real.exp (Real.pi / 2) * rho = 1 := by
  dsimp [rho]
  rw [← Real.exp_add]
  rw [show Real.pi / 2 + -(Real.pi / 2) = 0 by ring]
  rw [Real.exp_zero]

private theorem neg_pi_div_two_exp_mul_rho :
    (-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho =
        -(Real.pi / 2) * (Real.exp (Real.pi / 2) * rho) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_pi_div_two_mul_rho]
    _ = -(Real.pi / 2) := by ring

private theorem theta_lt_one_div_three : theta < (1 : ℝ) / 3 := by
  have hpi : Real.pi / 2 < (63 : ℝ) / 40 := by
    linarith [Real.pi_lt_d2]
  have hexp_pos : 0 < Real.exp (Real.pi / 2) := Real.exp_pos _
  nlinarith [hpi, exp_pi_div_two_gt_24_div_5, theta_mul_exp_pi_div_two, theta_pos,
    hexp_pos]

private theorem exp_neg_theta_mul_exp_theta :
    Real.exp (-theta) * Real.exp theta = 1 := by
  rw [← Real.exp_add]
  rw [show -theta + theta = 0 by ring]
  rw [Real.exp_zero]

private theorem exp_theta_mul_exp_neg_theta :
    Real.exp theta * Real.exp (-theta) = 1 := by
  rw [← Real.exp_add]
  rw [show theta + -theta = 0 by ring]
  rw [Real.exp_zero]

private theorem neg_pi_div_two_exp_neg_theta_mul_exp_theta :
    (-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta =
        -(Real.pi / 2) * (Real.exp (-theta) * Real.exp theta) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_neg_theta_mul_exp_theta]
    _ = -(Real.pi / 2) := by ring

private theorem neg_pi_div_two_exp_theta_mul_exp_neg_theta :
    (-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta) = -(Real.pi / 2) := by
  calc
    (-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta) =
        -(Real.pi / 2) * (Real.exp theta * Real.exp (-theta)) := by ring
    _ = -(Real.pi / 2) * 1 := by rw [exp_theta_mul_exp_neg_theta]
    _ = -(Real.pi / 2) := by ring

private theorem u_im_eq_sin_theta : u.im = Real.sin theta := by
  rw [← I_pow_q_eq_u, I_pow_q_eq_exp_theta]
  simp [Complex.exp_im, Complex.mul_re, Complex.mul_im]

private theorem u_im_pos : 0 < u.im := by
  rw [u_im_eq_sin_theta]
  exact Real.sin_pos_of_pos_of_lt_pi theta_pos (by linarith [theta_lt_pi_div_two, Real.pi_pos])

private theorem pi_div_two_mul_sin_theta_lt_log_two :
    Real.pi / 2 * Real.sin theta < Real.log 2 := by
  have hsin_lt_theta : Real.sin theta < theta := Real.sin_lt theta_pos
  have harg_lt_pi_div_six : Real.pi / 2 * Real.sin theta < Real.pi / 6 := by
    nlinarith [Real.pi_pos, u_im_pos, u_im_eq_sin_theta, hsin_lt_theta,
      theta_lt_one_div_three]
  have hpi_div_six_lt_log_two : Real.pi / 6 < Real.log 2 := by
    nlinarith [Real.pi_lt_d2, Real.log_two_gt_d9]
  exact harg_lt_pi_div_six.trans hpi_div_six_lt_log_two

private theorem exp_lt_two_of_lt_log_two {x : ℝ} (hx : x < Real.log 2) :
    Real.exp x < 2 := by
  have h := Real.exp_lt_exp.mpr hx
  rwa [Real.exp_log (by norm_num : (0 : ℝ) < 2)] at h

/-- `(i^(i^i))^(i^(-i)) = i`. -/
theorem u_pow_qInv_eq_I : principalPow u qInv = Complex.I := by
  dsimp [principalPow, qInv]
  rw [log_u]
  rw [show ((theta : ℂ) * Complex.I) * ((Real.exp (Real.pi / 2) : ℝ) : ℂ) =
      ((Real.pi / 2 : ℝ) : ℂ) * Complex.I by
    rw [show ((theta : ℂ) * Complex.I) * ((Real.exp (Real.pi / 2) : ℝ) : ℂ) =
        ((theta * Real.exp (Real.pi / 2) : ℝ) : ℂ) * Complex.I by
      apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
    rw [theta_mul_exp_pi_div_two]]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `(i^(i^i))^(-i) = exp(theta)`, the reciprocal of `(i^i)^(i^i)`. -/
theorem u_pow_neg_I_eq_qqInv : principalPow u (-Complex.I) = qqInv := by
  dsimp [principalPow, qqInv]
  rw [log_u]
  rw [show ((theta : ℂ) * Complex.I) * -Complex.I = (theta : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp theta).symm

/-- `(i^i)^i = -i`. -/
theorem q_pow_I_eq_neg_I : principalPow q Complex.I = -Complex.I := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `i^(-i) = exp(pi/2)`. -/
theorem I_pow_neg_I_eq_qInv : principalPow Complex.I (-Complex.I) = qInv := by
  dsimp [principalPow, qInv]
  rw [log_I_real]
  rw [show (((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * -Complex.I =
      ((Real.pi / 2 : ℝ) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (Real.pi / 2)).symm

/-- `(i^i)^(-i) = i`. -/
theorem q_pow_neg_I_eq_I : principalPow q (-Complex.I) = Complex.I := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  rw [show (↑(-(Real.pi / 2)) : ℂ) * -Complex.I =
      ((Real.pi / 2 : ℝ) : ℂ) * Complex.I by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [Complex.exp_mul_I]
  apply Complex.ext <;> simp

/-- `(-i)^(-i) = exp(-pi/2) = i^i`. -/
theorem neg_I_pow_neg_I_eq_q : principalPow (-Complex.I) (-Complex.I) = q := by
  dsimp [principalPow, q, rho]
  rw [log_neg_I_real]
  rw [show (((-(Real.pi / 2 : ℝ) : ℂ) * Complex.I) * -Complex.I) =
      (-(Real.pi / 2) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑Real.pi / 2) : ℂ) = ↑(-(Real.pi / 2)) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_q_eq_exp_neg_theta :
    principalPow q q = (Real.exp (-theta) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * q = ↑(-theta) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, q, theta]]
  exact (Complex.ofReal_exp (-theta)).symm

private theorem log_q_pow_q :
    Complex.log (principalPow q q) = (-theta : ℂ) := by
  rw [q_pow_q_eq_exp_neg_theta]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]
  norm_num

/-- `((i^i)^(i^i))^(i^(-i)) = i^i`. -/
theorem q_pow_q_pow_qInv_eq_q :
    principalPow (principalPow q q) qInv = q := by
  change Complex.exp (Complex.log (principalPow q q) * qInv) = q
  rw [log_q_pow_q]
  rw [show ((-theta : ℂ) * qInv) =
      (-(theta * Real.exp (Real.pi / 2)) : ℂ) by
    dsimp [qInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [show (-(↑theta * ↑(Real.exp (Real.pi / 2))) : ℂ) =
      (↑(-(theta * Real.exp (Real.pi / 2))) : ℂ) by norm_num]
  rw [theta_mul_exp_pi_div_two]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qInv_eq_exp :
    principalPow q qInv =
      (Real.exp (-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * qInv =
      (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) by
    dsimp [qInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp (Real.pi / 2))).symm

private theorem log_q_pow_qInv :
    Complex.log (principalPow q qInv) =
      (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) := by
  rw [q_pow_qInv_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `((i^i)^(i^(-i)))^(i^i) = i^i`. -/
theorem q_pow_qInv_pow_q_eq_q :
    principalPow (principalPow q qInv) q = q := by
  change Complex.exp (Complex.log (principalPow q qInv) * q) = q
  rw [log_q_pow_qInv]
  rw [show (↑(-(Real.pi / 2) * Real.exp (Real.pi / 2)) : ℂ) * q =
      (↑((-(Real.pi / 2) * Real.exp (Real.pi / 2)) * rho) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im, q]]
  rw [neg_pi_div_two_exp_mul_rho]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qq_eq_exp :
    principalPow q (principalPow q q) =
      (Real.exp (-(Real.pi / 2) * Real.exp (-theta)) : ℂ) := by
  change Complex.exp (Complex.log q * principalPow q q) =
    (Real.exp (-(Real.pi / 2) * Real.exp (-theta)) : ℂ)
  rw [q_pow_q_eq_exp_neg_theta]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * ((Real.exp (-theta) : ℝ) : ℂ) =
      (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp (-theta))).symm

private theorem log_q_pow_qq :
    Complex.log (principalPow q (principalPow q q)) =
      (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) := by
  rw [q_pow_qq_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `(i^i)^((i^i)^(i^i))`, raised to `(i^(i^i))^(-i)`, is `i^i`. -/
theorem q_pow_qq_pow_qqInv_eq_q :
    principalPow (principalPow q (principalPow q q)) qqInv = q := by
  change Complex.exp (Complex.log (principalPow q (principalPow q q)) * qqInv) = q
  rw [log_q_pow_qq]
  rw [show (↑(-(Real.pi / 2) * Real.exp (-theta)) : ℂ) * qqInv =
      (↑((-(Real.pi / 2) * Real.exp (-theta)) * Real.exp theta) : ℂ) by
    dsimp [qqInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [neg_pi_div_two_exp_neg_theta_mul_exp_theta]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem q_pow_qqInv_eq_exp :
    principalPow q qqInv =
      (Real.exp (-(Real.pi / 2) * Real.exp theta) : ℂ) := by
  dsimp [principalPow]
  rw [log_q]
  rw [show (-(↑Real.pi / 2) : ℂ) * qqInv =
      (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) by
    dsimp [qqInv]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * Real.exp theta)).symm

private theorem log_q_pow_qqInv :
    Complex.log (principalPow q qqInv) =
      (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) := by
  rw [q_pow_qqInv_eq_exp]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/-- `(i^i)^((i^(i^i))^(-i))`, raised to `(i^i)^(i^i)`, is `i^i`. -/
theorem q_pow_qqInv_pow_qq_eq_q :
    principalPow (principalPow q qqInv) (principalPow q q) = q := by
  change Complex.exp (Complex.log (principalPow q qqInv) * principalPow q q) = q
  rw [log_q_pow_qqInv]
  rw [q_pow_q_eq_exp_neg_theta]
  rw [show (↑(-(Real.pi / 2) * Real.exp theta) : ℂ) * ((Real.exp (-theta) : ℝ) : ℂ) =
      (↑((-(Real.pi / 2) * Real.exp theta) * Real.exp (-theta)) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  rw [neg_pi_div_two_exp_theta_mul_exp_neg_theta]
  dsimp [q, rho]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem v_mul_w_eq_one : v * w = 1 := by
  dsimp [v, w, principalPow]
  rw [log_I_real, log_neg_I_real]
  rw [← Complex.exp_add]
  rw [show (((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * u +
      (((-(Real.pi / 2 : ℝ) : ℂ) * Complex.I) * u) = 0 by ring]
  exact Complex.exp_zero

private theorem w_mul_v_eq_one : w * v = 1 := by
  rw [mul_comm, v_mul_w_eq_one]

private theorem v_norm_lt_one : ‖v‖ < 1 := by
  dsimp [v, principalPow]
  rw [log_I_real, Complex.norm_exp]
  rw [show ((((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * u).re =
      -(Real.pi / 2) * u.im by
    simp [Complex.mul_re, Complex.mul_im]]
  exact Real.exp_lt_one_iff.mpr (by nlinarith [Real.pi_pos, u_im_pos])

private theorem w_norm_lt_two : ‖w‖ < 2 := by
  dsimp [w, principalPow]
  rw [log_neg_I_real, Complex.norm_exp]
  rw [show ((((-(Real.pi / 2 : ℝ) : ℂ) * Complex.I) * u).re) =
      Real.pi / 2 * u.im by
    simp [Complex.mul_re, Complex.mul_im]]
  rw [u_im_eq_sin_theta]
  exact exp_lt_two_of_lt_log_two pi_div_two_mul_sin_theta_lt_log_two

private theorem abs_v_im_lt_one : |v.im| < 1 :=
  (Complex.abs_im_le_norm v).trans_lt v_norm_lt_one

private theorem abs_w_im_lt_two : |w.im| < 2 :=
  (Complex.abs_im_le_norm w).trans_lt w_norm_lt_two

private theorem log_q_pow_v :
    Complex.log (principalPow q v) = Complex.log q * v := by
  change Complex.log (Complex.exp (Complex.log q * v)) = Complex.log q * v
  rw [Complex.log_exp]
  · rw [log_q]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, (abs_lt.mp abs_v_im_lt_one).1,
      (abs_lt.mp abs_v_im_lt_one).2]
  · rw [log_q]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, (abs_lt.mp abs_v_im_lt_one).1,
      (abs_lt.mp abs_v_im_lt_one).2]

private theorem log_q_pow_w :
    Complex.log (principalPow q w) = Complex.log q * w := by
  change Complex.log (Complex.exp (Complex.log q * w)) = Complex.log q * w
  rw [Complex.log_exp]
  · rw [log_q]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, (abs_lt.mp abs_w_im_lt_two).1,
      (abs_lt.mp abs_w_im_lt_two).2]
  · rw [log_q]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, (abs_lt.mp abs_w_im_lt_two).1,
      (abs_lt.mp abs_w_im_lt_two).2]

/-- `(q^v)^w = q`, with the principal-log branch certified by norm bounds. -/
theorem q_pow_v_pow_w_eq_q : principalPow (principalPow q v) w = q := by
  change Complex.exp (Complex.log (principalPow q v) * w) = q
  rw [log_q_pow_v]
  rw [show (Complex.log q * v) * w = Complex.log q by
    rw [mul_assoc, v_mul_w_eq_one, mul_one]]
  rw [log_q]
  dsimp [q, rho]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

/-- `(q^w)^v = q`, with the principal-log branch certified by norm bounds. -/
theorem q_pow_w_pow_v_eq_q : principalPow (principalPow q w) v = q := by
  change Complex.exp (Complex.log (principalPow q w) * v) = q
  rw [log_q_pow_w]
  rw [show (Complex.log q * w) * v = Complex.log q by
    rw [mul_assoc, w_mul_v_eq_one, mul_one]]
  rw [log_q]
  dsimp [q, rho]
  rw [show (-(↑Real.pi / 2) : ℂ) = (↑(-(Real.pi / 2)) : ℂ) by norm_num]
  exact (Complex.ofReal_exp (-(Real.pi / 2))).symm

private theorem sigma_pos : 0 < sigma := by
  dsimp [sigma]
  positivity

private theorem log_qInv : Complex.log qInv = (↑Real.pi / 2 : ℂ) := by
  dsimp [qInv]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]
  norm_num [div_eq_mul_inv]

private theorem qInv_pow_qInv_eq_sigma :
    principalPow qInv qInv = (sigma : ℂ) := by
  change Complex.exp (Complex.log qInv * qInv) = (sigma : ℂ)
  rw [log_qInv]
  dsimp [qInv, sigma]
  rw [show (↑Real.pi / 2 : ℂ) * ((Real.exp (Real.pi / 2) : ℝ) : ℂ) =
      (↑(Real.pi / 2 * Real.exp (Real.pi / 2)) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (Real.pi / 2 * Real.exp (Real.pi / 2))).symm

private theorem nearProbeR_eq_sigma : nearProbeR = (sigma : ℂ) := by
  dsimp [nearProbeR]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  exact qInv_pow_qInv_eq_sigma

private theorem q_pow_sigma_eq_tau :
    principalPow q (sigma : ℂ) = (tau : ℂ) := by
  change Complex.exp (Complex.log q * (sigma : ℂ)) = (tau : ℂ)
  rw [log_q]
  dsimp [tau]
  rw [show (-(↑Real.pi / 2) : ℂ) * (sigma : ℂ) =
      (↑ (-(Real.pi / 2) * sigma) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-(Real.pi / 2) * sigma)).symm

private theorem nearProbeS_eq_tau : nearProbeS = (tau : ℂ) := by
  dsimp [nearProbeS]
  rw [nearProbeR_eq_sigma]
  exact q_pow_sigma_eq_tau

private theorem log_nearProbeS :
    Complex.log nearProbeS = (↑ (-(Real.pi / 2) * sigma) : ℂ) := by
  rw [nearProbeS_eq_tau]
  dsimp [tau]
  rw [← Complex.ofReal_log (Real.exp_pos _).le, Real.log_exp]

/--
Representative `idx = 2207` from the n = 12 near-zero probe class:

`((i^i)^(i^i))^((i^((i^i)^i))^(i^((i^i)^i)))`.
-/
def nearZero2207 : ℂ := principalPow (principalPow q q) nearProbeR

/--
Representative `idx = 3777` from the n = 12 near-zero probe class:

`((i^i)^((i^((i^i)^i))^(i^((i^i)^i))))^(i^i)`.
-/
def nearZero3777 : ℂ := principalPow nearProbeS q

private theorem nearZero2207_eq_exp :
    nearZero2207 = (Real.exp (-theta * sigma) : ℂ) := by
  change Complex.exp (Complex.log (principalPow q q) * nearProbeR) =
    (Real.exp (-theta * sigma) : ℂ)
  rw [log_q_pow_q]
  rw [nearProbeR_eq_sigma]
  rw [show (-theta : ℂ) * (sigma : ℂ) = (↑(-theta * sigma) : ℂ) by
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]]
  exact (Complex.ofReal_exp (-theta * sigma)).symm

private theorem nearZero3777_eq_exp :
    nearZero3777 = (Real.exp (-theta * sigma) : ℂ) := by
  change Complex.exp (Complex.log nearProbeS * q) = (Real.exp (-theta * sigma) : ℂ)
  rw [log_nearProbeS]
  rw [show (↑ (-(Real.pi / 2) * sigma) : ℂ) * q = (↑(-theta * sigma) : ℂ) by
    dsimp [q, theta]
    apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]
    ring]
  exact (Complex.ofReal_exp (-theta * sigma)).symm

/-- The n = 12 near-zero representatives `2207` and `3777` are exactly equal. -/
theorem nearZero2207_eq_nearZero3777 : nearZero2207 = nearZero3777 := by
  rw [nearZero2207_eq_exp, nearZero3777_eq_exp]

private theorem tau_pos : 0 < tau := by
  dsimp [tau]
  positivity

private theorem tau_lt_one : tau < 1 := by
  dsimp [tau]
  exact Real.exp_lt_one_iff.mpr (by nlinarith [Real.pi_pos, sigma_pos])

private theorem log_I_pow_nearProbeS :
    Complex.log (principalPow Complex.I nearProbeS) =
      Complex.log Complex.I * nearProbeS := by
  change Complex.log (Complex.exp (Complex.log Complex.I * nearProbeS)) =
    Complex.log Complex.I * nearProbeS
  rw [Complex.log_exp]
  · rw [nearProbeS_eq_tau, log_I_real]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, tau_pos]
  · rw [nearProbeS_eq_tau, log_I_real]
    simp [Complex.mul_im]
    nlinarith [Real.pi_pos, tau_lt_one]

/--
Representative `idx = 1404` from the n = 12 near-one probe class:

`(i^i)^((i^i)^((i^((i^i)^i))^(i^((i^i)^i))))`.
-/
def nearOne1404 : ℂ := principalPow q nearProbeS

/--
Representative `idx = 4239` from the n = 12 near-one probe class:

`(i^((i^i)^((i^((i^i)^i))^(i^((i^i)^i)))))^i`.
-/
def nearOne4239 : ℂ := principalPow (principalPow Complex.I nearProbeS) Complex.I

/-- The n = 12 near-one representatives `1404` and `4239` are exactly equal. -/
theorem nearOne1404_eq_nearOne4239 : nearOne1404 = nearOne4239 := by
  change Complex.exp (Complex.log q * nearProbeS) =
    Complex.exp (Complex.log (principalPow Complex.I nearProbeS) * Complex.I)
  rw [log_I_pow_nearProbeS]
  rw [log_q, log_I_real]
  rw [nearProbeS_eq_tau]
  congr 1
  apply Complex.ext <;> simp [Complex.mul_re, Complex.mul_im]

/--
The `n = 11` exponent subtree used by representative `idx = 25`:

`i^(i^(i^(i^(((i^i)^i)^(i^(i^(i^i)))))))`.
-/
def nearOne25Base : ℂ :=
  principalPow Complex.I
    (principalPow Complex.I
      (principalPow Complex.I
        (principalPow Complex.I
          (principalPow (principalPow q Complex.I) v))))

/--
Representative `idx = 25` from the n = 12 near-one probe class:

`i^(i^(i^(i^(i^(((i^i)^i)^(i^(i^(i^i))))))))`.
-/
def nearOne25 : ℂ := principalPow Complex.I nearOne25Base

/-- The retained near-one pair has modulus strictly less than `1`. -/
theorem nearOne1404_norm_lt_one : ‖nearOne1404‖ < 1 := by
  dsimp [nearOne1404, principalPow]
  rw [Complex.norm_exp, log_q, nearProbeS_eq_tau]
  rw [show ((-(Real.pi / 2) : ℂ) * (tau : ℂ)).re = -(Real.pi / 2) * tau by
    simp [Complex.mul_re]]
  exact Real.exp_lt_one_iff.mpr (by nlinarith [Real.pi_pos, tau_pos])

/-- The second retained near-one representative also has modulus strictly less than `1`. -/
theorem nearOne4239_norm_lt_one : ‖nearOne4239‖ < 1 := by
  rw [← nearOne1404_eq_nearOne4239]
  exact nearOne1404_norm_lt_one

/--
If the exact `idx = 25` exponent subtree has negative imaginary part, then
the resulting `idx = 25` value has modulus strictly greater than `1`.

This isolates the remaining hard analytic sign bound for the strict class-25
split.
-/
theorem nearOne25_norm_gt_one_of_base_im_neg (h : nearOne25Base.im < 0) :
    1 < ‖nearOne25‖ := by
  dsimp [nearOne25, principalPow]
  rw [Complex.norm_exp, log_I_real]
  rw [show ((((Real.pi / 2 : ℝ) : ℂ) * Complex.I) * nearOne25Base).re =
      -(Real.pi / 2) * nearOne25Base.im by
    simp [Complex.mul_re, Complex.mul_im]]
  exact Real.one_lt_exp_iff.mpr (by nlinarith [Real.pi_pos, h])

/--
The strict class-25 split follows from the single remaining sign obligation
`nearOne25Base.im < 0`: representative `25` is then not equal to `1404`.
-/
theorem nearOne25_ne_nearOne1404_of_base_im_neg (h : nearOne25Base.im < 0) :
    nearOne25 ≠ nearOne1404 := by
  intro heq
  have hnorm := congrArg (fun z : ℂ => ‖z‖) heq
  have hgt := nearOne25_norm_gt_one_of_base_im_neg h
  have hlt := nearOne1404_norm_lt_one
  linarith

/--
The same sign obligation separates representative `25` from the other retained
near-one representative `4239`.
-/
theorem nearOne25_ne_nearOne4239_of_base_im_neg (h : nearOne25Base.im < 0) :
    nearOne25 ≠ nearOne4239 := by
  intro heq
  have hnorm := congrArg (fun z : ℂ => ‖z‖) heq
  have hgt := nearOne25_norm_gt_one_of_base_im_neg h
  have hlt := nearOne4239_norm_lt_one
  linarith

/--
Representative `idx = 562` from the n = 12 near-`i^i` probe class, written
with the same principal-power expression as the local trace:

`i^((i^i)^((i^i)^((i^(i^i))^(i^((i^i)^i)))))`.
-/
def nearIPowerI562 : ℂ :=
  principalPow Complex.I
    (principalPow q
      (principalPow q
        (principalPow (principalPow Complex.I q)
          (principalPow Complex.I (principalPow q Complex.I)))))

/-- Candidate `562` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI562_eq_q : nearIPowerI562 = q := by
  dsimp [nearIPowerI562]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 1901` from the same n = 12 near-`i^i` probe class:

`((i^i)^i)^((i^i)^((i^(i^i))^(i^((i^i)^i))))`.
-/
def nearIPowerI1901 : ℂ :=
  principalPow (principalPow q Complex.I)
    (principalPow q
      (principalPow (principalPow Complex.I q)
        (principalPow Complex.I (principalPow q Complex.I))))

/-- Candidate `1901` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI1901_eq_q : nearIPowerI1901 = q := by
  dsimp [nearIPowerI1901]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [neg_I_pow_neg_I_eq_q]

/--
Representative `idx = 2161` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^i))^(i^((i^i)^((i^i)^((i^i)^i))))`.
-/
def nearIPowerI2161 : ℂ :=
  principalPow (principalPow q q)
    (principalPow Complex.I
      (principalPow q
        (principalPow q (principalPow q Complex.I))))

/-- Candidate `2161` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2161_eq_q : nearIPowerI2161 = q := by
  dsimp [nearIPowerI2161]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_q_pow_qInv_eq_q]

/--
Representative `idx = 2378` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^i))^((i^(i^i))^(i^((i^i)^i)))`.
-/
def nearIPowerI2378 : ℂ :=
  principalPow (principalPow q (principalPow q Complex.I))
    (principalPow (principalPow Complex.I q)
      (principalPow Complex.I (principalPow q Complex.I)))

/-- Candidate `2378` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2378_eq_q : nearIPowerI2378 = q := by
  dsimp [nearIPowerI2378]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 2581` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^i)))^(i^((i^i)^((i^i)^i)))`.
-/
def nearIPowerI2581 : ℂ :=
  principalPow (principalPow q (principalPow Complex.I (principalPow q Complex.I)))
    (principalPow Complex.I (principalPow q (principalPow q Complex.I)))

/-- Candidate `2581` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2581_eq_q : nearIPowerI2581 = q := by
  dsimp [nearIPowerI2581]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]
  rw [q_pow_qInv_pow_q_eq_q]

/--
Representative `idx = 2574` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^(i^(i^i))))^(((i^i)^i)^(i^(i^i)))`.
-/
def nearIPowerI2574 : ℂ :=
  principalPow (principalPow q v)
    (principalPow (principalPow q Complex.I) u)

/-- Candidate `2574` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2574_eq_q : nearIPowerI2574 = q := by
  dsimp [nearIPowerI2574]
  rw [q_pow_I_eq_neg_I]
  change principalPow (principalPow q v) w = q
  exact q_pow_v_pow_w_eq_q

/--
Representative `idx = 2603` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^(i^i)))^((i^(i^i))^((i^i)^i))`.
-/
def nearIPowerI2603 : ℂ :=
  principalPow (principalPow q (principalPow q q))
    (principalPow (principalPow Complex.I q) (principalPow q Complex.I))

/-- Candidate `2603` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2603_eq_q : nearIPowerI2603 = q := by
  dsimp [nearIPowerI2603]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_q_eq_u]
  rw [u_pow_neg_I_eq_qqInv]
  rw [q_pow_qq_pow_qqInv_eq_q]

/--
Representative `idx = 2847` from the n = 12 near-`i^i` probe class:

`((i^(i^i))^(i^((i^i)^i)))^((i^i)^((i^i)^i))`.
-/
def nearIPowerI2847 : ℂ :=
  principalPow
    (principalPow (principalPow Complex.I q)
      (principalPow Complex.I (principalPow q Complex.I)))
    (principalPow q (principalPow q Complex.I))

/-- Candidate `2847` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI2847_eq_q : nearIPowerI2847 = q := by
  dsimp [nearIPowerI2847]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

/--
Representative `idx = 3035` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^((i^i)^i))))^(i^((i^i)^i))`.
-/
def nearIPowerI3035 : ℂ :=
  principalPow
    (principalPow q
      (principalPow Complex.I (principalPow q (principalPow q Complex.I))))
    (principalPow Complex.I (principalPow q Complex.I))

/-- Candidate `3035` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3035_eq_q : nearIPowerI3035 = q := by
  dsimp [nearIPowerI3035]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_q_pow_qInv_eq_q]

/--
Representative `idx = 3057` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^(i^i))^((i^i)^i)))^((i^i)^(i^i))`.
-/
def nearIPowerI3057 : ℂ :=
  principalPow
    (principalPow q
      (principalPow (principalPow Complex.I q) (principalPow q Complex.I)))
    (principalPow q q)

/-- Candidate `3057` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3057_eq_q : nearIPowerI3057 = q := by
  dsimp [nearIPowerI3057]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_q_eq_u]
  rw [u_pow_neg_I_eq_qqInv]
  rw [q_pow_qqInv_pow_qq_eq_q]

/--
Representative `idx = 3058` from the n = 12 near-`i^i` probe class:

`((i^i)^(((i^i)^i)^(i^(i^i))))^(i^(i^(i^i)))`.
-/
def nearIPowerI3058 : ℂ :=
  principalPow
    (principalPow q (principalPow (principalPow q Complex.I) u))
    v

/-- Candidate `3058` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3058_eq_q : nearIPowerI3058 = q := by
  dsimp [nearIPowerI3058]
  rw [q_pow_I_eq_neg_I]
  change principalPow (principalPow q w) v = q
  exact q_pow_w_pow_v_eq_q

/--
Representative `idx = 3352` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^(i^i))^(i^((i^i)^i))))^((i^i)^i)`.
-/
def nearIPowerI3352 : ℂ :=
  principalPow
    (principalPow q
      (principalPow (principalPow Complex.I q)
        (principalPow Complex.I (principalPow q Complex.I))))
    (principalPow q Complex.I)

/-- Candidate `3352` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3352_eq_q : nearIPowerI3352 = q := by
  dsimp [nearIPowerI3352]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [neg_I_pow_neg_I_eq_q]

/--
Representative `idx = 3731` from the n = 12 near-`i^i` probe class:

`((i^i)^(i^((i^i)^((i^i)^((i^i)^i)))))^(i^i)`.
-/
def nearIPowerI3731 : ℂ :=
  principalPow
    (principalPow q
      (principalPow Complex.I
        (principalPow q (principalPow q (principalPow q Complex.I)))))
    q

/-- Candidate `3731` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI3731_eq_q : nearIPowerI3731 = q := by
  dsimp [nearIPowerI3731]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [q_pow_qInv_pow_q_eq_q]

/--
Representative `idx = 4549` from the n = 12 near-`i^i` probe class:

`((i^i)^((i^i)^((i^(i^i))^(i^((i^i)^i)))))^i`.
-/
def nearIPowerI4549 : ℂ :=
  principalPow
    (principalPow q
      (principalPow q
        (principalPow (principalPow Complex.I q)
          (principalPow Complex.I (principalPow q Complex.I)))))
    Complex.I

/-- Candidate `4549` in the n = 12 near-`i^i` class is exactly `i^i`. -/
theorem nearIPowerI4549_eq_q : nearIPowerI4549 = q := by
  dsimp [nearIPowerI4549]
  rw [q_pow_I_eq_neg_I]
  rw [I_pow_neg_I_eq_qInv]
  rw [I_pow_q_eq_u]
  rw [u_pow_qInv_eq_I]
  rw [q_pow_I_eq_neg_I]
  rw [q_pow_neg_I_eq_I]
  rw [I_pow_I_eq_q]

end

end A198683N12Symbolic

end LeanProofs
