import BoundedPAConsistency.Basic
import BoundedPAConsistency.CodedHierarchy
import BoundedPAConsistency.Internal
import BoundedPAConsistency.QuantifierFreeTarski
import BoundedPAConsistency.QuantifierFreeTruth
import BoundedPAConsistency.RestrictedConsistency
import BoundedPAConsistency.TermEvaluationTransport

/-!
# Kernel audit for bounded PA consistency, phase one

The checks below keep the public metatheoretic surface visible and ask Lean to
report the assumptions of the key hierarchy, erasure, cofinality, collapse,
and standard-model consistency theorems.
-/

open LeanProofs.BoundedPAConsistency

#check sigmaRank
#check piRank
#check quantifierGroups
#check hierarchyRanks_rename
#check hierarchyRanks_subst
#check quantifierGroups_mixed_branches
#check ProvTree
#check eraseProvTree
#check provTree_complete
#check proofOccurrenceRank
#check ProofAllBounded
#check RestrictedProv
#check RestrictedBProv
#check restrictedProv_erase
#check restrictedBProv_erase
#check restrictedProv_cofinal
#check restrictedBProv_cofinal
#check conclusionRestrictedProv_bot_iff
#check conclusionRestrictedBProv_bot_iff
#check restrictedPA_consistent_standard
#check LeanProofs.BoundedPAConsistency.Internal.inductionAtHierarchy
#check LeanProofs.BoundedPAConsistency.Internal.inductionInPeanoModel
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValues
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue.defined
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValues.defined
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_bvar_zero_seqCons
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_add
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_mul
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termShift_of_isFreeTail
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termSubst_of_isSubstitutionBound
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isSubstitutionEnvironment
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.quantifierGroupsCode
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.QuantifierBoundedCode
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_neg
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_shift
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_subst
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue_isBit
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.quantifierGroupsCode_eq_zero_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_and_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_eq_atom_iff
#check LeanProofs.BoundedPAConsistency.RestrictedDerivation
#check LeanProofs.BoundedPAConsistency.RestrictedProof
#check LeanProofs.BoundedPAConsistency.RestrictedConsistent
#check LeanProofs.BoundedPAConsistency.paRestrictedConsistencySentence
#check LeanProofs.BoundedPAConsistency.eval_paRestrictedConsistencySentence_iff

#print axioms hierarchyRanks_rename
#print axioms hierarchyRanks_subst
#print axioms provTree_complete
#print axioms restrictedBProv_erase
#print axioms restrictedBProv_cofinal
#print axioms conclusionRestrictedBProv_bot_iff
#print axioms restrictedPA_consistent_standard
#print axioms LeanProofs.BoundedPAConsistency.Internal.inductionAtHierarchy
#print axioms LeanProofs.BoundedPAConsistency.Internal.inductionInPeanoModel
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue.defined
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValues.defined
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_bvar_zero_seqCons
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_add
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_mul
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termShift_of_isFreeTail
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termSubst_of_isSubstitutionBound
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isSubstitutionEnvironment
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_neg
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_shift
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_subst
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue_isBit
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.quantifierGroupsCode_eq_zero_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_and_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_eq_atom_iff
#print axioms LeanProofs.BoundedPAConsistency.RestrictedDerivation.defined
#print axioms LeanProofs.BoundedPAConsistency.RestrictedProof.defined
#print axioms LeanProofs.BoundedPAConsistency.eval_paRestrictedConsistencySentence_iff
