import PAHF.PASyntax

/-!
# Quantifier-group-bounded PA derivations

This file fixes a polarity-aware syntactic meaning of "at most `n` quantifier
groups" and applies it to the natural-deduction calculus in `PAHF.PASyntax`.

`sigmaRank` and `piRank` are the least levels generated by the usual
arithmetical-hierarchy rules (without first converting a formula to prenex
form).  Conjunction and disjunction take componentwise maxima.  In an
implication the antecedent changes polarity.  A universal quantifier preserves
the Pi side and costs one extra level on the Sigma side; an existential does
the dual.  `quantifierGroups` is the smaller of the two ranks.  For example,
an existential formula and a universal formula can each have rank one, while
their conjunction normally has rank two.  This is a parse-tree hierarchy rank,
not a theorem asserting that a particular prenex-normalization procedure was
carried out.

The proof restriction is imposed at *every judgement node* of a derivation,
including its displayed context.  Restricting only the final formula would say
nothing for a contradiction: `bot` has rank zero, so conclusion-only restricted
consistency is definitionally ordinary consistency.
-/

namespace LeanProofs
namespace BoundedPAConsistency

open SetTheory

/-! ## Polarity-aware formula ranks -/

mutual
  /-- Least Sigma-hierarchy level generated compositionally with `piRank`. -/
  def sigmaRank : PA.Formula → Nat
    | .eq _ _ => 0
    | .bot => 0
    | .imp a b => Nat.max (piRank a) (sigmaRank b)
    | .and a b => Nat.max (sigmaRank a) (sigmaRank b)
    | .or a b => Nat.max (sigmaRank a) (sigmaRank b)
    | .all a => Nat.max 1 (piRank a) + 1
    | .ex a => Nat.max 1 (sigmaRank a)

  /-- Least Pi-hierarchy level generated compositionally with `sigmaRank`. -/
  def piRank : PA.Formula → Nat
    | .eq _ _ => 0
    | .bot => 0
    | .imp a b => Nat.max (sigmaRank a) (piRank b)
    | .and a b => Nat.max (piRank a) (piRank b)
    | .or a b => Nat.max (piRank a) (piRank b)
    | .all a => Nat.max 1 (piRank a)
    | .ex a => Nat.max 1 (sigmaRank a) + 1
end

/-- The least of the generated Sigma and Pi levels. -/
def quantifierGroups (phi : PA.Formula) : Nat :=
  Nat.min (sigmaRank phi) (piRank phi)

/-- A formula lies below the externally fixed hierarchy bound `n`. -/
def QuantifierBounded (n : Nat) (phi : PA.Formula) : Prop :=
  quantifierGroups phi ≤ n

/-- Renaming preserves both polarity ranks simultaneously.  Packaging the two
equalities together gives the induction hypotheses needed at implication and
at the two quantifiers, where Sigma and Pi refer to each other. -/
theorem hierarchyRanks_rename (r : Nat → Nat) (phi : PA.Formula) :
    sigmaRank (PA.Formula.rename r phi) = sigmaRank phi ∧
      piRank (PA.Formula.rename r phi) = piRank phi := by
  induction phi generalizing r with
  | eq a b => simp [PA.Formula.rename, sigmaRank, piRank]
  | bot => simp [PA.Formula.rename, sigmaRank, piRank]
  | imp a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha r
      obtain ⟨hbSigma, hbPi⟩ := ihb r
      simp [PA.Formula.rename, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | and a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha r
      obtain ⟨hbSigma, hbPi⟩ := ihb r
      simp [PA.Formula.rename, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | or a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha r
      obtain ⟨hbSigma, hbPi⟩ := ihb r
      simp [PA.Formula.rename, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | all a ih =>
      obtain ⟨haSigma, haPi⟩ := ih (SetTheory.up r)
      simp [PA.Formula.rename, sigmaRank, piRank, haPi]
  | ex a ih =>
      obtain ⟨haSigma, haPi⟩ := ih (SetTheory.up r)
      simp [PA.Formula.rename, sigmaRank, piRank, haSigma]

/-- Substitution preserves both polarity ranks simultaneously. -/
theorem hierarchyRanks_subst (sigma : Nat → PA.Term) (phi : PA.Formula) :
    sigmaRank (PA.Formula.subst sigma phi) = sigmaRank phi ∧
      piRank (PA.Formula.subst sigma phi) = piRank phi := by
  induction phi generalizing sigma with
  | eq a b => simp [PA.Formula.subst, sigmaRank, piRank]
  | bot => simp [PA.Formula.subst, sigmaRank, piRank]
  | imp a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha sigma
      obtain ⟨hbSigma, hbPi⟩ := ihb sigma
      simp [PA.Formula.subst, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | and a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha sigma
      obtain ⟨hbSigma, hbPi⟩ := ihb sigma
      simp [PA.Formula.subst, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | or a b iha ihb =>
      obtain ⟨haSigma, haPi⟩ := iha sigma
      obtain ⟨hbSigma, hbPi⟩ := ihb sigma
      simp [PA.Formula.subst, sigmaRank, piRank,
        haSigma, haPi, hbSigma, hbPi]
  | all a ih =>
      obtain ⟨haSigma, haPi⟩ := ih (PA.Term.upSubst sigma)
      simp [PA.Formula.subst, sigmaRank, piRank, haPi]
  | ex a ih =>
      obtain ⟨haSigma, haPi⟩ := ih (PA.Term.upSubst sigma)
      simp [PA.Formula.subst, sigmaRank, piRank, haSigma]

@[simp] theorem sigmaRank_rename (r : Nat → Nat) (phi : PA.Formula) :
    sigmaRank (PA.Formula.rename r phi) = sigmaRank phi :=
  (hierarchyRanks_rename r phi).1

@[simp] theorem piRank_rename (r : Nat → Nat) (phi : PA.Formula) :
    piRank (PA.Formula.rename r phi) = piRank phi :=
  (hierarchyRanks_rename r phi).2

@[simp] theorem sigmaRank_subst (sigma : Nat → PA.Term) (phi : PA.Formula) :
    sigmaRank (PA.Formula.subst sigma phi) = sigmaRank phi :=
  (hierarchyRanks_subst sigma phi).1

@[simp] theorem piRank_subst (sigma : Nat → PA.Term) (phi : PA.Formula) :
    piRank (PA.Formula.subst sigma phi) = piRank phi :=
  (hierarchyRanks_subst sigma phi).2

@[simp] theorem quantifierGroups_rename (r : Nat → Nat)
    (phi : PA.Formula) :
    quantifierGroups (PA.Formula.rename r phi) = quantifierGroups phi := by
  simp [quantifierGroups]

@[simp] theorem quantifierGroups_subst (sigma : Nat → PA.Term)
    (phi : PA.Formula) :
    quantifierGroups (PA.Formula.subst sigma phi) = quantifierGroups phi := by
  simp [quantifierGroups]

@[simp] theorem quantifierBounded_rename_iff (n : Nat) (r : Nat → Nat)
    (phi : PA.Formula) :
    QuantifierBounded n (PA.Formula.rename r phi) ↔
      QuantifierBounded n phi := by
  simp [QuantifierBounded]

@[simp] theorem quantifierBounded_subst_iff (n : Nat)
    (sigma : Nat → PA.Term) (phi : PA.Formula) :
    QuantifierBounded n (PA.Formula.subst sigma phi) ↔
      QuantifierBounded n phi := by
  simp [QuantifierBounded]

@[simp] theorem quantifierGroups_bot :
    quantifierGroups PA.Formula.bot = 0 := rfl

@[simp] theorem quantifierBounded_bot (n : Nat) :
    QuantifierBounded n PA.Formula.bot := by
  simp [QuantifierBounded]

theorem quantifierBounded_mono {m n : Nat} (hmn : m ≤ n)
    {phi : PA.Formula} (hphi : QuantifierBounded m phi) :
    QuantifierBounded n phi :=
  Nat.le_trans hphi hmn

/- Small reductions pin down the hierarchy convention. -/
def rankAtom : PA.Formula :=
  .eq (PA.Term.var 0) (PA.Term.var 0)

theorem quantifierGroups_existential_atom :
    quantifierGroups (.ex rankAtom) = 1 := rfl

theorem quantifierGroups_universal_atom :
    quantifierGroups (.all rankAtom) = 1 := rfl

theorem quantifierGroups_mixed_branches :
    quantifierGroups (.and (.ex rankAtom) (.all rankAtom)) = 2 := rfl

theorem quantifierGroups_implication_polarity :
    quantifierGroups (.imp (.ex rankAtom) (.all rankAtom)) = 1 := rfl

/-! ## Every-occurrence proof bounds -/

/-- Maximum hierarchy rank displayed in a proof context. -/
def contextRank : List PA.Formula → Nat
  | [] => 0
  | phi :: G => Nat.max (quantifierGroups phi) (contextRank G)

/-- Maximum of a node's ambient context and its explicit formula annotations. -/
def nodeRank (G annotations : List PA.Formula) : Nat :=
  Nat.max (contextRank G) (contextRank annotations)

/-- A data-carrying mirror of `PA.Formula.Prov`.

The library derivation relation lives in `Prop`.  Proof irrelevance therefore
prevents a faithful numeric recursion over its proof shape: two derivations of
the same judgement are indistinguishable as indices.  `ProvTree` lives in
`Type`, retains exactly the same rules, and can consequently be inspected to
enforce an every-occurrence complexity bound. -/
inductive ProvTree : List PA.Formula → PA.Formula → Type
  | ass : ∀ G a, a ∈ G → ProvTree G a
  | impI : ∀ G a b, ProvTree (a :: G) b → ProvTree G (.imp a b)
  | impE : ∀ G a b, ProvTree G (.imp a b) → ProvTree G a → ProvTree G b
  | botE : ∀ G a, ProvTree G .bot → ProvTree G a
  | lem : ∀ G a, ProvTree G (.or a (.imp a .bot))
  | andI : ∀ G a b, ProvTree G a → ProvTree G b → ProvTree G (.and a b)
  | andE1 : ∀ G a b, ProvTree G (.and a b) → ProvTree G a
  | andE2 : ∀ G a b, ProvTree G (.and a b) → ProvTree G b
  | orI1 : ∀ G a b, ProvTree G a → ProvTree G (.or a b)
  | orI2 : ∀ G a b, ProvTree G b → ProvTree G (.or a b)
  | orE : ∀ G a b c, ProvTree G (.or a b) → ProvTree (a :: G) c →
      ProvTree (b :: G) c → ProvTree G c
  | allI : ∀ G a, ProvTree (G.map (PA.Formula.rename Nat.succ)) a →
      ProvTree G (.all a)
  | allE : ∀ G a t, ProvTree G (.all a) →
      ProvTree G (PA.Formula.subst (PA.Formula.instTerm t) a)
  | exI : ∀ G a t,
      ProvTree G (PA.Formula.subst (PA.Formula.instTerm t) a) →
      ProvTree G (.ex a)
  | exE : ∀ G a c, ProvTree G (.ex a) →
      ProvTree (a :: G.map (PA.Formula.rename Nat.succ))
        (PA.Formula.rename Nat.succ c) → ProvTree G c
  | eqRefl : ∀ G t, ProvTree G (.eq t t)
  | eqElim : ∀ G s t a, ProvTree G (.eq s t) →
      ProvTree G (PA.Formula.subst (PA.Formula.instTerm s) a) →
      ProvTree G (PA.Formula.subst (PA.Formula.instTerm t) a)

namespace ProvTree

/-- Forget the data-carrying tree and recover the library derivation. -/
theorem erase : {G : List PA.Formula} → {phi : PA.Formula} →
    ProvTree G phi → PA.Formula.Prov G phi
  | _, _, .ass G a membership => .P_ass G a membership
  | _, _, .impI G a b premise => .P_impI G a b premise.erase
  | _, _, .impE G a b major minor => .P_impE G a b major.erase minor.erase
  | _, _, .botE G a premise => .P_botE G a premise.erase
  | _, _, .lem G a => .P_lem G a
  | _, _, .andI G a b left right => .P_andI G a b left.erase right.erase
  | _, _, .andE1 G a b premise => .P_andE1 G a b premise.erase
  | _, _, .andE2 G a b premise => .P_andE2 G a b premise.erase
  | _, _, .orI1 G a b premise => .P_orI1 G a b premise.erase
  | _, _, .orI2 G a b premise => .P_orI2 G a b premise.erase
  | _, _, .orE G a b c disjunction left right =>
      .P_orE G a b c disjunction.erase left.erase right.erase
  | _, _, .allI G a premise => .P_allI G a premise.erase
  | _, _, .allE G a t premise => .P_allE G a t premise.erase
  | _, _, .exI G a t premise => .P_exI G a t premise.erase
  | _, _, .exE G a c existential body => .P_exE G a c existential.erase body.erase
  | _, _, .eqRefl G t => .P_eqRefl G t
  | _, _, .eqElim G s t a equality instanceProof =>
      .P_eqElim G s t a equality.erase instanceProof.erase

/-- Maximum rank of every context, conclusion, rule annotation, and premise
subtree in a data-carrying derivation. -/
def occurrenceRank : {G : List PA.Formula} → {phi : PA.Formula} →
    ProvTree G phi → Nat
  | _, _, .ass G a _ => nodeRank G [a]
  | _, _, .impI G a b premise =>
      Nat.max (nodeRank G [.imp a b, a, b]) premise.occurrenceRank
  | _, _, .impE G a b major minor =>
      Nat.max (nodeRank G [b, a, .imp a b])
        (Nat.max major.occurrenceRank minor.occurrenceRank)
  | _, _, .botE G a premise =>
      Nat.max (nodeRank G [a, .bot]) premise.occurrenceRank
  | _, _, .lem G a => nodeRank G [.or a (.imp a .bot), a]
  | _, _, .andI G a b left right =>
      Nat.max (nodeRank G [.and a b, a, b])
        (Nat.max left.occurrenceRank right.occurrenceRank)
  | _, _, .andE1 G a b premise =>
      Nat.max (nodeRank G [a, b, .and a b]) premise.occurrenceRank
  | _, _, .andE2 G a b premise =>
      Nat.max (nodeRank G [b, a, .and a b]) premise.occurrenceRank
  | _, _, .orI1 G a b premise =>
      Nat.max (nodeRank G [.or a b, a, b]) premise.occurrenceRank
  | _, _, .orI2 G a b premise =>
      Nat.max (nodeRank G [.or a b, a, b]) premise.occurrenceRank
  | _, _, .orE G a b c disjunction left right =>
      Nat.max (nodeRank G [c, a, b, .or a b])
        (Nat.max disjunction.occurrenceRank
          (Nat.max left.occurrenceRank right.occurrenceRank))
  | _, _, .allI G a premise =>
      Nat.max (nodeRank G [.all a, a]) premise.occurrenceRank
  | _, _, .allE G a t premise =>
      Nat.max (nodeRank G [PA.Formula.subst (PA.Formula.instTerm t) a,
        .all a, a]) premise.occurrenceRank
  | _, _, .exI G a t premise =>
      Nat.max (nodeRank G [.ex a,
        PA.Formula.subst (PA.Formula.instTerm t) a, a]) premise.occurrenceRank
  | _, _, .exE G a c existential body =>
      Nat.max (nodeRank G [c, .ex a, a, PA.Formula.rename Nat.succ c])
        (Nat.max existential.occurrenceRank body.occurrenceRank)
  | _, _, .eqRefl G t => nodeRank G [.eq t t]
  | _, _, .eqElim G s t a equality instanceProof =>
      Nat.max (nodeRank G [PA.Formula.subst (PA.Formula.instTerm t) a,
        .eq s t, PA.Formula.subst (PA.Formula.instTerm s) a, a])
        (Nat.max equality.occurrenceRank instanceProof.occurrenceRank)

end ProvTree

/-- Public unnamespaced spelling matching the Rocq port. -/
def proofOccurrenceRank {G : List PA.Formula} {phi : PA.Formula}
    (proof : ProvTree G phi) : Nat :=
  proof.occurrenceRank

/-- Public erasure spelling matching the Rocq port. -/
theorem eraseProvTree {G : List PA.Formula} {phi : PA.Formula}
    (proof : ProvTree G phi) : PA.Formula.Prov G phi :=
  proof.erase

/-- Every formula occurrence in a concrete proof tree respects `n`. -/
def ProofAllBounded {G : List PA.Formula} {phi : PA.Formula}
    (n : Nat) (proof : ProvTree G phi) : Prop :=
  proofOccurrenceRank proof ≤ n

/-- There is a PA proof tree all of whose formula occurrences have at most
`n` quantifier groups.  The bound `n` is meta-theoretical. -/
def RestrictedProv (n : Nat) (G : List PA.Formula)
    (phi : PA.Formula) : Prop :=
  ∃ proof : ProvTree G phi, ProofAllBounded n proof

/-- Theory-relative restricted provability.  A finite list selects the
background axioms used, exactly as in `PA.Formula.BProv`. -/
def RestrictedBProv (n : Nat) (B : PA.Formula → Prop)
    (G : List PA.Formula) (phi : PA.Formula) : Prop :=
  ∃ L : List PA.Formula,
    (∀ x, x ∈ L → B x) ∧ RestrictedProv n (L ++ G) phi

/-- Erase the proof-tree complexity certificate. -/
theorem restrictedProv_erase {n : Nat} {G : List PA.Formula}
    {phi : PA.Formula} (h : RestrictedProv n G phi) :
    PA.Formula.Prov G phi :=
  h.choose.erase

/-- Erasing a restricted relative proof yields an ordinary relative proof. -/
theorem restrictedBProv_erase {n : Nat} {B : PA.Formula → Prop}
    {G : List PA.Formula} {phi : PA.Formula}
    (h : RestrictedBProv n B G phi) :
    PA.Formula.BProv B G phi := by
  rcases h with ⟨L, hL, proof, _⟩
  exact ⟨L, hL, proof.erase⟩

theorem proofAllBounded_mono {m n : Nat} (hmn : m ≤ n)
    {G : List PA.Formula} {phi : PA.Formula}
    {proof : ProvTree G phi} (hproof : ProofAllBounded m proof) :
    ProofAllBounded n proof :=
  Nat.le_trans hproof hmn

theorem restrictedProv_mono {m n : Nat} (hmn : m ≤ n)
    {G : List PA.Formula} {phi : PA.Formula}
    (h : RestrictedProv m G phi) : RestrictedProv n G phi := by
  rcases h with ⟨proof, hproof⟩
  exact ⟨proof, proofAllBounded_mono hmn hproof⟩

theorem restrictedBProv_mono {m n : Nat} (hmn : m ≤ n)
    {B : PA.Formula → Prop} {G : List PA.Formula} {phi : PA.Formula}
    (h : RestrictedBProv m B G phi) : RestrictedBProv n B G phi := by
  rcases h with ⟨L, hL, hproof⟩
  exact ⟨L, hL, restrictedProv_mono hmn hproof⟩

/-- Every library derivation has a data-carrying representative.  The result
is `Nonempty` because eliminating a `Prop`-valued derivation into `Type` would
violate proof irrelevance, while eliminating it into this proposition is sound. -/
theorem provTree_complete {G : List PA.Formula} {phi : PA.Formula}
    (proof : PA.Formula.Prov G phi) : Nonempty (ProvTree G phi) := by
  induction proof with
  | P_ass G a membership => exact ⟨.ass G a membership⟩
  | P_impI G a b _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.impI G a b premise⟩
  | P_impE G a b _ _ ihMajor ihMinor =>
      rcases ihMajor with ⟨major⟩
      rcases ihMinor with ⟨minor⟩
      exact ⟨.impE G a b major minor⟩
  | P_botE G a _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.botE G a premise⟩
  | P_lem G a => exact ⟨.lem G a⟩
  | P_andI G a b _ _ ihLeft ihRight =>
      rcases ihLeft with ⟨left⟩
      rcases ihRight with ⟨right⟩
      exact ⟨.andI G a b left right⟩
  | P_andE1 G a b _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.andE1 G a b premise⟩
  | P_andE2 G a b _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.andE2 G a b premise⟩
  | P_orI1 G a b _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.orI1 G a b premise⟩
  | P_orI2 G a b _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.orI2 G a b premise⟩
  | P_orE G a b c _ _ _ ihDisjunction ihLeft ihRight =>
      rcases ihDisjunction with ⟨disjunction⟩
      rcases ihLeft with ⟨left⟩
      rcases ihRight with ⟨right⟩
      exact ⟨.orE G a b c disjunction left right⟩
  | P_allI G a _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.allI G a premise⟩
  | P_allE G a t _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.allE G a t premise⟩
  | P_exI G a t _ ih =>
      rcases ih with ⟨premise⟩
      exact ⟨.exI G a t premise⟩
  | P_exE G a c _ _ ihExistential ihBody =>
      rcases ihExistential with ⟨existential⟩
      rcases ihBody with ⟨body⟩
      exact ⟨.exE G a c existential body⟩
  | P_eqRefl G t => exact ⟨.eqRefl G t⟩
  | P_eqElim G s t a _ _ ihEquality ihInstance =>
      rcases ihEquality with ⟨equality⟩
      rcases ihInstance with ⟨instanceProof⟩
      exact ⟨.eqElim G s t a equality instanceProof⟩

/-- Every finite ordinary derivation has some external hierarchy bound. -/
theorem restrictedProv_cofinal {G : List PA.Formula} {phi : PA.Formula}
    (proof : PA.Formula.Prov G phi) :
    ∃ n : Nat, RestrictedProv n G phi := by
  rcases provTree_complete proof with ⟨tree⟩
  exact ⟨tree.occurrenceRank, tree, Nat.le_refl _⟩

/-- Every finite theory-relative derivation has some external bound as well. -/
theorem restrictedBProv_cofinal {B : PA.Formula → Prop}
    {G : List PA.Formula} {phi : PA.Formula}
    (h : PA.Formula.BProv B G phi) :
    ∃ n : Nat, RestrictedBProv n B G phi := by
  rcases h with ⟨L, hL, proof⟩
  rcases restrictedProv_cofinal proof with ⟨n, hrestricted⟩
  exact ⟨n, L, hL, hrestricted⟩

/-! ## Why the restriction must cover the proof -/

/-- The deliberately inadequate restriction which inspects only the final
formula of a bare derivation. -/
def ConclusionRestrictedProv (n : Nat) (G : List PA.Formula)
    (phi : PA.Formula) : Prop :=
  PA.Formula.Prov G phi ∧ QuantifierBounded n phi

/-- The conclusion-only version of theory-relative provability. -/
def ConclusionRestrictedBProv (n : Nat) (B : PA.Formula → Prop)
    (G : List PA.Formula) (phi : PA.Formula) : Prop :=
  PA.Formula.BProv B G phi ∧ QuantifierBounded n phi

/-- Since falsity has no quantifiers, bounding only the conclusion does not
weaken a claim that falsity is derivable. -/
theorem conclusionRestrictedProv_bot_iff (n : Nat) (G : List PA.Formula) :
    ConclusionRestrictedProv n G PA.Formula.bot ↔
      PA.Formula.Prov G PA.Formula.bot := by
  simp [ConclusionRestrictedProv]

/-- The same collapse for proofs relative to an arbitrary background theory. -/
theorem conclusionRestrictedBProv_bot_iff (n : Nat)
    (B : PA.Formula → Prop) (G : List PA.Formula) :
    ConclusionRestrictedBProv n B G PA.Formula.bot ↔
      PA.Formula.BProv B G PA.Formula.bot := by
  simp [ConclusionRestrictedBProv]

/-! ## External standard-model consistency -/

/-- External (Lean-level) consistency of the restricted PA calculus, proved
by ordinary soundness in the standard natural-number model.  This theorem is
proved for every external `n` without assuming PA's consistency; it is
intentionally not yet the much stronger assertion that PA proves an
arithmetized restricted-consistency sentence. -/
theorem restrictedPA_consistent_standard (n : Nat) :
    ¬RestrictedBProv n PA.Formula.Ax_s [] PA.Formula.bot := by
  intro hrestricted
  have hproof : PA.Formula.BProv PA.Formula.Ax_s [] PA.Formula.bot :=
    restrictedBProv_erase hrestricted
  have hfalse : PA.Formula.Sat PA.natModel (fun _ => 0) PA.Formula.bot :=
    PA.Formula.soundness_BProv PA.natModel hproof (fun _ => 0)
      (fun ax hax => PA.Formula.sat_axiom_s PA.natModel (fun _ => 0) ax hax)
      (fun assumption membership => by cases membership)
  exact hfalse

end BoundedPAConsistency
end LeanProofs
