import Mathlib.Analysis.SpecialFunctions.Trigonometric.Arctan

/-!
# A quadratic arctangent identity

This module proves an exact integer-coefficient identity among squares of
arctangents.  The proof first linearizes all eleven arctangents in the
argument lattice generated by

* `u = π / 4`,
* `a = arctan (1 / 2)`,
* `b = arctan (2 / 3)`,
* `c = arctan (1 / 4)`.

The listed coefficients then have zero Gram matrix against the corresponding
integer coordinate vectors, so the final cancellation is polynomial algebra.
-/

namespace LeanProofs

noncomputable section

open Real

private abbrev u : ℝ := Real.pi / 4
private abbrev a : ℝ := Real.arctan ((1 : ℝ) / 2)
private abbrev b : ℝ := Real.arctan ((2 : ℝ) / 3)
private abbrev c : ℝ := Real.arctan ((1 : ℝ) / 4)

private lemma pi_div_two_eq_two_mul_u : Real.pi / 2 = 2 * u := by
  change Real.pi / 2 = 2 * (Real.pi / 4)
  ring

private lemma arctan_two : Real.arctan (2 : ℝ) = 2 * u - a := by
  have h := Real.arctan_inv_of_pos (x := (2 : ℝ)) (by norm_num)
  have h' : a = Real.pi / 2 - Real.arctan (2 : ℝ) := by
    simpa [a, one_div] using h
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_three : Real.arctan (3 : ℝ) = u + a := by
  change Real.arctan (3 : ℝ) = Real.pi / 4 + Real.arctan ((1 : ℝ) / 2)
  rw [← Real.arctan_one]
  rw [Real.arctan_add]
  · congr 1
    norm_num
  · norm_num

private lemma arctan_four : Real.arctan (4 : ℝ) = 2 * u - c := by
  have h := Real.arctan_inv_of_pos (x := (4 : ℝ)) (by norm_num)
  have h' : c = Real.pi / 2 - Real.arctan (4 : ℝ) := by
    simpa [c, one_div] using h
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_five : Real.arctan (5 : ℝ) = u + b := by
  change Real.arctan (5 : ℝ) = Real.pi / 4 + Real.arctan ((2 : ℝ) / 3)
  rw [← Real.arctan_one]
  rw [Real.arctan_add]
  · congr 1
    norm_num
  · norm_num

private lemma arctan_seven : Real.arctan (7 : ℝ) = 3 * u - 2 * a := by
  have hinv := Real.two_mul_arctan_inv_2_sub_arctan_inv_7
  have hinv' : 2 * a - Real.arctan ((1 : ℝ) / 7) = u := by
    simpa [a, u, one_div] using hinv
  have hrec := Real.arctan_inv_of_pos (x := (7 : ℝ)) (by norm_num)
  have hrec' : Real.arctan ((1 : ℝ) / 7) = Real.pi / 2 - Real.arctan (7 : ℝ) := by
    simpa [one_div] using hrec
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_eight : Real.arctan (8 : ℝ) = 2 * u + a - b := by
  have hsum : a + Real.arctan ((1 : ℝ) / 8) = b := by
    change Real.arctan ((1 : ℝ) / 2) + Real.arctan ((1 : ℝ) / 8) =
      Real.arctan ((2 : ℝ) / 3)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have hrec := Real.arctan_inv_of_pos (x := (8 : ℝ)) (by norm_num)
  have hrec' : Real.arctan ((1 : ℝ) / 8) = Real.pi / 2 - Real.arctan (8 : ℝ) := by
    simpa [one_div] using hrec
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_thirteen : Real.arctan (13 : ℝ) = u + a + c := by
  have h3 := arctan_three
  have hsum : Real.arctan (3 : ℝ) + c = Real.arctan (13 : ℝ) := by
    change Real.arctan (3 : ℝ) + Real.arctan ((1 : ℝ) / 4) =
      Real.arctan (13 : ℝ)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  linarith

private lemma arctan_eighteen : Real.arctan (18 : ℝ) = 2 * a + b := by
  have h2a : 2 * a = Real.arctan ((4 : ℝ) / 3) := by
    change 2 * Real.arctan ((1 : ℝ) / 2) = Real.arctan ((4 : ℝ) / 3)
    rw [Real.two_mul_arctan]
    · congr 1
      norm_num
    · norm_num
    · norm_num
  have hsum : Real.arctan ((4 : ℝ) / 3) + b = Real.arctan (18 : ℝ) := by
    change Real.arctan ((4 : ℝ) / 3) + Real.arctan ((2 : ℝ) / 3) =
      Real.arctan (18 : ℝ)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  linarith

private lemma arctan_twenty_one : Real.arctan (21 : ℝ) = 3 * u - b - c := by
  have hbc : b + c = Real.arctan ((11 : ℝ) / 10) := by
    change Real.arctan ((2 : ℝ) / 3) + Real.arctan ((1 : ℝ) / 4) =
      Real.arctan ((11 : ℝ) / 10)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have huinv : u + Real.arctan ((1 : ℝ) / 21) = Real.arctan ((11 : ℝ) / 10) := by
    change Real.pi / 4 + Real.arctan ((1 : ℝ) / 21) =
      Real.arctan ((11 : ℝ) / 10)
    rw [← Real.arctan_one]
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have hrec := Real.arctan_inv_of_pos (x := (21 : ℝ)) (by norm_num)
  have hrec' : Real.arctan ((1 : ℝ) / 21) = Real.pi / 2 - Real.arctan (21 : ℝ) := by
    simpa [one_div] using hrec
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_thirty_eight : Real.arctan (38 : ℝ) = 2 * u + a - 2 * c := by
  have h2c : 2 * c = Real.arctan ((8 : ℝ) / 15) := by
    change 2 * Real.arctan ((1 : ℝ) / 4) = Real.arctan ((8 : ℝ) / 15)
    rw [Real.two_mul_arctan]
    · congr 1
      norm_num
    · norm_num
    · norm_num
  have hsum : a + Real.arctan ((1 : ℝ) / 38) = Real.arctan ((8 : ℝ) / 15) := by
    change Real.arctan ((1 : ℝ) / 2) + Real.arctan ((1 : ℝ) / 38) =
      Real.arctan ((8 : ℝ) / 15)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have hrec := Real.arctan_inv_of_pos (x := (38 : ℝ)) (by norm_num)
  have hrec' : Real.arctan ((1 : ℝ) / 38) = Real.pi / 2 - Real.arctan (38 : ℝ) := by
    simpa [one_div] using hrec
  linarith [pi_div_two_eq_two_mul_u]

private lemma arctan_forty_seven : Real.arctan (47 : ℝ) = 3 * u - a - b + c := by
  have hab : a + b = Real.arctan ((7 : ℝ) / 4) := by
    change Real.arctan ((1 : ℝ) / 2) + Real.arctan ((2 : ℝ) / 3) =
      Real.arctan ((7 : ℝ) / 4)
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have huc : u + c = Real.arctan ((5 : ℝ) / 3) := by
    change Real.pi / 4 + Real.arctan ((1 : ℝ) / 4) =
      Real.arctan ((5 : ℝ) / 3)
    rw [← Real.arctan_one]
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have hsum : Real.arctan ((5 : ℝ) / 3) + Real.arctan ((1 : ℝ) / 47) =
      Real.arctan ((7 : ℝ) / 4) := by
    rw [Real.arctan_add]
    · congr 1
      norm_num
    · norm_num
  have hrec := Real.arctan_inv_of_pos (x := (47 : ℝ)) (by norm_num)
  have hrec' : Real.arctan ((1 : ℝ) / 47) = Real.pi / 2 - Real.arctan (47 : ℝ) := by
    simpa [one_div] using hrec
  linarith [pi_div_two_eq_two_mul_u]

/--
The requested quadratic arctangent identity.
-/
theorem arctan_square_identity :
    (2939 : ℝ) * Real.arctan (2 : ℝ) ^ 2 -
      1250 * Real.arctan (3 : ℝ) ^ 2 -
      252 * Real.arctan (4 : ℝ) ^ 2 -
      360 * Real.arctan (5 : ℝ) ^ 2 -
      870 * Real.arctan (7 : ℝ) ^ 2 +
      450 * Real.arctan (8 : ℝ) ^ 2 +
      84 * Real.arctan (13 : ℝ) ^ 2 +
      330 * Real.arctan (18 : ℝ) ^ 2 -
      210 * Real.arctan (21 : ℝ) ^ 2 +
      147 * Real.arctan (38 : ℝ) ^ 2 -
      210 * Real.arctan (47 : ℝ) ^ 2 = 0 := by
  rw [arctan_two, arctan_three, arctan_four, arctan_five, arctan_seven, arctan_eight,
    arctan_thirteen, arctan_eighteen, arctan_twenty_one, arctan_thirty_eight,
    arctan_forty_seven]
  ring

end

end LeanProofs
